<h1>Вакансии</h1>

<div class="section">
    <h3>Список вакансий</h3>
    <div class="addPanel">
        <button type="button" class="btn btn-default" id="add-entity">Добавить вакансию</button>

        <div class="form-inline" id="adding-form" style="display: none">
            <div class="form-group">
                <label class="sr-only" for="inputName">Название</label>
                <input type="text" class="form-control" id="inputName" placeholder="Введите название..."/>
            </div>

            <button type="button" class="btn btn-default" id="adding-complete">Добавить</button>
            <button type="button" class="btn btn-default" id="adding-cancel">Отмена</button>
        </div>
    </div>

    <table class="table admin-table  table-striped">
        <tr>
            <th>Id</th>
            <th>Название</th>
            <th>Управление</th>
        </tr>
        <tbody id="sortable">
        <? foreach($entities as $entity){ ?>
            <tr class="entity">
                <td><?= $entity->id; ?></td>
                <td><?= $entity->title; ?></td>
                <td>
                    <a href="#" class="editBtn">Редактировать</a>
                    <a href="#" class="deleteBtn">Удалить</a>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>

<? $vacancies = \Application\Service\ApplicationService::makeIdArrayFromObjectArray($entities);?>
<div class="section">
    <h3>Ответы на вакансии</h3>
    <table class="table admin-table  table-striped">
        <tr>
            <th>Id</th>
            <th>Вакансия</th>
            <th>Отправитель</th>
            <th>Почта</th>
            <th>Резюме</th>
            <th>Дата</th>
        </tr>
        <tbody id="sortable">
        <? foreach($requests as $req){ ?>
            <tr class="entity">
                <td><?= $req->id; ?></td>
                <td><?= $vacancies[$req->vacancy]->title; ?></td>
                <td><?= $req->name; ?></td>
                <td><?= $req->mail; ?></td>
                <td><a href="<?= $this->basePath() . '/images/vacancies/' .$req->file; ?>" target="_blank"><?= $req->file; ?></a></td>
                <td><?= $req->date; ?></td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>

<?
$sl = $this->getHelperPluginManager()->getServiceLocator();
echo \Info\Service\SeoService::renderSeoForm($sl, $seoData);
?>

<script type="text/javascript">
    $(document).ready(function(){
        catalog.baseUrl = '<?= $this->url('zfcadmin/vacancies') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/vacancies', array('action'=> 'view')) ?>';
        catalog.init();
    });
</script>