<h1>Вакансии</h1>

<? if (!$isDomainZoneBy) { ?>
<div class="section">
    <h3>Список вакансий</h3>
    <div class="addPanel">
        <button type="button" class="btn btn-default" id="add-entity">Добавить вакансию</button>

        <div class="form-inline" id="adding-form" style="display: none">
            <div class="form-group">
                <label class="sr-only" for="inputName">Название</label>
                <input type="text" class="form-control" id="inputName" placeholder="Введите название..."/>
            </div>

            <button type="button" class="btn btn-default" id="adding-complete">Добавить</button>
            <button type="button" class="btn btn-default" id="adding-cancel">Отмена</button>
        </div>
    </div>

    <table class="table admin-table table-striped">
        <tr>
            <th>Id</th>
            <th>Название</th>
			<th>Уровень зарплаты</th>
			<th>Город</th>
			<th>Требуемый опыт работы</th>
			<th>Тип занятости</th>
            <th>Управление</th>
        </tr>
        <tbody id="sortable">
        <? foreach($entities as $entity){ ?>
            <tr class="entity" <?= $entity->deleted ? 'style="color: #BBB"' : '' ?>>
                <td><?= $entity->id; ?></td>
                <td><?= $entity->title; ?></td>
				<td><?= $entity->salary; ?></td>
				<td><?= $entity->city; ?></td>
				<td><?= $entity->skill; ?></td>
				<td><?= $entity->hours; ?></td>
                <td>
                    <a href="#" class="editBtn">Редактировать</a>
                    <a href="#" class="deleteBtn">Удалить</a>
					<a href="#" class="showBtn" <?= $entity->deleted ? '' : 'style="display: none"' ?>>Показать</a>
                    <a href="#" class="hideBtn" <?= $entity->deleted ? 'style="display: none"' : '' ?>>Скрыть</a>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>
<? } ?>

<? $vacancies = \Application\Service\ApplicationService::makeIdArrayFromObjectArray($entities);?>
<div class="section">
    <h3>Ответы на вакансии</h3>
    <table class="table admin-table  table-striped">
        <tr>
            <th>Id</th>
            <th>Вакансия</th>
            <th>Отправитель</th>
			<th>Телефон</th>
            <th>Почта</th>
            <th>Резюме</th>
            <th>Дата</th>
        </tr>
        <tbody id="sortable">
        <? foreach($requests as $req){ ?>
            <tr class="entity">
                <td><?= $req->id; ?></td>
                <td><?= $req->vacancy ? $vacancies[$req->vacancy]->title : $req->custom_vacancy; ?></td>
                <td><?= $req->name; ?></td>
				<td><?= $req->phone; ?></td>
                <td><?= $req->mail; ?></td>
                <td><a href="<?= $this->basePath() . '/images/vacancies_request/' .$req->file; ?>" target="_blank" download><?= $req->file; ?></a></td>
                <td><?= $req->date; ?></td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>

<? if (!$isDomainZoneBy) {
$sl = $this->getHelperPluginManager()->getServiceLocator();
echo \Info\Service\SeoService::renderSeoForm($sl, $seoData);
} ?>

<script type="text/javascript">
    $(document).ready(function(){
        catalog.baseUrl = '<?= $this->url('zfcadmin/vacancies') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/vacancies', array('action'=> 'view')) ?>';
        catalog.init();
    });
</script>