<h1>
    <a href="<?= $this->url('zfcadmin/vacancies') ?>">Вакансии</a>
    >
    <span id="title"><?= $entity->title; ?></span>
</h1>

<h3>Основная информация</h3>
<table class="table admin-table table-striped">
    <tbody>
    <tr>
        <td>Название</td>
        <td>
            <a href="#" data-type="text" data-name="title" class="editable-param"><?= $entity->title; ?></a>
        </td>
    </tr>
    <tr>
        <td>Изображение</td>
        <td>
            <div class="admin-banner-img-container" <?= $entity->img ? '' : 'style="display:none"' ?>>
                <img style="height: 100%" src="<?= $entity->img ? $this->basePath() . '/images/vacancies/' . $entity->img : ''?>" alt=""/>
            </div>

            <button type="button" class="btn btn-default" id="add-img"> <?= $entity->img ? 'Редактировать' : 'Добавить' ?> изображение</button>

            <div class="form-inline" id="adding-form-img" style="display: none">
                <form id="img-form" method="post" enctype="multipart/form-data">
                    <p>
                        <input type="file" name="image"/>
                        <input type="hidden" name="id" value="<?= $entity->id ?>"/>
                    </p>

                    <p>
                        <input type="submit" class="btn btn-default"/>
                        <button type="button" class="btn btn-default" id="adding-cancel-img">Отмена</button>
                    </p>
                </form>
            </div>
        </td>
    </tr>
	<tr>
        <td>Уровень зарплаты</td>
        <td>
            <a href="#" data-type="text" data-name="salary" class="editable-param"><?= $entity->salary; ?></a>
        </td>
    </tr>
	<tr>
        <td>Город</td>
        <td>
            <a href="#" data-type="text" data-name="city" class="editable-param"><?= $entity->city; ?></a>
        </td>
    </tr>
	<tr>
        <td>Требуемый опыт работы</td>
        <td>
            <a href="#" data-type="text" data-name="skill" class="editable-param"><?= $entity->skill; ?></a>
        </td>
    </tr>
	<tr>
        <td>Обязанности</td>
        <td>
            <div class="editor-get-btn" data-name="duties"><?= $entity->duties; ?></div>
        </td>
    </tr>
	<tr>
        <td>Требования</td>
        <td>
            <div class="editor-get-btn" data-name="requirements"><?= $entity->requirements; ?></div>
        </td>
    </tr>
	<tr>
        <td>Условия</td>
        <td>
            <div class="editor-get-btn" data-name="conditions"><?= $entity->conditions; ?></div>
        </td>
    </tr>
	<tr>
        <td>Адрес</td>
        <td>
            <div class="editor-get-btn" data-name="address"><?= $entity->address; ?></div>
        </td>
    </tr>
    <tr>
        <td>Тип занятости</td>
        <td>
            <div class="editor-get-btn" data-name="hours"><?= $entity->hours; ?></div>
        </td>
    </tr>
    </tbody>
</table>

<?
$sl = $this->getHelperPluginManager()->getServiceLocator();
echo \Info\Service\SeoService::renderSeoForm($sl, $seoData);
?>

<script type="text/javascript">
    $(document).ready(function(){
        catalog.parentId = '<?= $entity->id ?>';
        catalog.baseUrl = '<?= $this->url('zfcadmin/vacancies') ?>';
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.editablesSave
        });

        imgUploader.init({
            type: 'single',
            imgUrl: '<?= $this->basePath() . '/images/vacancies/' ?>'
        });
    });
</script>