<div class="b-section__content">
    <div class="b-breadcrumbs">
        <a class="b-breadcrumbs__item" href="/">Главная</a>&nbsp;/
        <a class="b-breadcrumbs__item" href="/job/">Работа у нас</a>&nbsp;/

        <strong class="b-breadcrumbs__item b-breadcrumbs__item_active">Руководитель отдела продаж</strong>
    </div>
</div>
<div class="b-section  b-article  b-article_job">

    <div class="b-section__content">
	<h2 class="b-article__heading">Руководитель отдела продаж</h2>
	<hr class="dotted-separator b-article__separator b-article_job__separator">
	<img src="/images/job/img_1.jpg"
	/>
		<hr class="dotted-separator b-article__separator  b-article_job__separator">
	<p>Уровень зарплаты: з/п не указана</p>
    <p>Город: Санкт-Петербург</p>
    <p>Требуемый опыт работы: 3–6 лет</p>

<p class="b-article_job__section-heading">Обязанности:</p>
<ul>
<li>
Разработка стратегии продвижения продукции (двигатели, запчасти) на рынке;
</li>
<li>
Прогнозирование продаж, обеспечение условий для выполнения плана продаж;
</li>
<li>
Развитие и обучение менеджеров по продажам;
</li>
<li>
Развитие и оптимизация каналов сбыта по направлению;
</li>
<li>
Мониторинг рынка, анализ положения продукта на рынке относительно конкурентов;
</li>
<li>
Проведение переговоров с ключевыми клиентами;
</li>
<li>
Контроль ПДЗ и ДЗ, поступления ДС, отчетность.
</li>
<li>
 Участие в определении политики ценообразования, условий продажи;
</li>

<li>
Личные продажи;
</li>
</ul>

<p class="b-article_job__section-heading">Требования:</p>
<ul>
<li>
Образование высшее;
<li>Опыт работы на руководящих позициях в продажах обязателен;</li>
<li>Наличие личного успешного опыта продаж;</li>
<li>Умение вести переговоры на любом уровне;</li>
<li>Опытный пользователь (Windows, MS Office, 1С 8 УПП);</li>
<li>Профессиональны качества: ориентированность на результат, стрессоустойчивость, аналитические способности, умение расставлять приоритеты;</li>
<li>Желательны знания основ логистики, товародвижения, владение основами стратегического менеджмента, бизнес-планирования;</li>
<li>Необходимо знание рынка автомобильных запасных частей (спецтехника).</li>

<p class="b-article_job__section-heading">Условия:</p>
<li>Оформление согласно ТК РФ;</li>
<li>Местоположение офиса: ул. Парковая (ст.м. Московские Ворота);</li>
<li>Рабочий день с 8.00 до 17.00 (пт. и предпраздничные дни до 16.00);</li>
<li>Возможны командировки;</li>
<li>Компенсация мобильной связи, расходов на автомобиль.</li>

<p class="b-article_job__section-heading">Адрес:</p>
<p>Санкт-Петербург, Московский район, Парковая улица, 7</p>
<a href="/contacts" target="_blank">Показать на карте</a>
<p class="b-article_job__section-heading">Тип занятости:</p>
<p>Полная занятость, полный день</p>

	<a  href="javascript:void(0)" class="b-button  b-button_underlined b-button_gray-bordered b-article_job__button">
                <span class="b-button__text">Откликнуться на вакансию</span>
            </a>
	
	</div>
	
	

	
	</div>