<h1>
    <a href="<?= $this->url('zfcadmin/projects') ?>">Проекты</a>
    >
    <a href="<?= $this->url('zfcadmin/projects', array('action'=>'view', 'id'=>$project->id)) ?>"><?= $project->title; ?></a>
    >
    Участник: <span id="title"><?= $member->title; ?></span>
</h1>

<div class="section">
    <h3>Основная информация</h3>
    <table class="table admin-table ">
        <tbody>
        <tr>
            <td>Имя</td>
            <td>
                <a href="#" data-type="text" data-name="title" class="editable-param"><?= $member->title; ?></a>
            </td>
        </tr>
        <tr>
            <td>Роль</td>
            <td>
                <a href="#" data-type="text" data-name="role" class="editable-param"><?= $member->role; ?></a>
            </td>
        </tr>
        <tr>
            <td>Ссылка</td>
            <td>
                <a href="#" data-type="text" data-name="link" class="editable-param"><?= $member->link; ?></a>
            </td>
        </tr>
        <tr>
            <td>Текст ссылки</td>
            <td>
                <a href="#" data-type="text" data-name="link_text" class="editable-param"><?= $member->link_text; ?></a>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= $member->id ?>';
        catalog.parentType = '<?= $project->id ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::PROJECTS ?>';
        catalog.type = 'prmember';
        catalog.baseUrl = '<?= $this->url('zfcadmin/projects') ?>';
        catalog.initEditables();
    });
</script>