<div class="catalog-filter" ng-controller="SoloTableCtrl">
    <form id="f-form" class="form-horizontal" role="form">
        <div class="form-group" style="margin-bottom: 5px">
            <div class="checkbox " style="padding-left: 15px; padding-top: 0">
                <input type="checkbox" id="f-instock" ng-model="instock">
                <label for="f-instock">показать только в наличии</label>
            </div>
        </div>
        <div class="form-group" style="margin-bottom: 5px">
            <div class="checkbox " style="padding-left: 15px; padding-top: 0">
                <input type="checkbox" id="f-offers" ng-model="offers">
                <label for="f-offers">спецпредложения</label>
            </div>
        </div>
    </form>
</div>

<script>
    $(function(){
        var isTableFilter = $('.catalog-filter').parent().hasClass('tablefilter');

        filter.init({
            section_id: <?= $section->id ?>,
            subsection_id: <?= isset($subsection->id)? $subsection->id : 0 ?>,
            smallFilter: true,
            tableFilter: isTableFilter
        });
    });
</script>