<div class="catalog-filter b-filter">
    <div class="b-catalog__title b-title_filter">
        <h2 class="b-title-h2 b-catalog__title-h2">Выбор по параметрам</h2>
    </div>

    <form id="f-form" class="b-form b-filter-form" role="form">

        <div class="b-filter-form__panel filter-instock">
            <div class="b-checkbox">
                <input class="b-checkbox__input" type="checkbox" id="f-instock">
                <label class="b-checkbox__text" for="f-instock">показать только в наличии</label>
            </div>
        </div>

    <? foreach($filterData as $param){ ?>
        <div class="b-filter-form__panel" data-field="<?= $param->field ?>">

            <div class="panel-heading popupsmall-container wide-popup" data-type="filter">
                <a class="<?= $param->open ? '' : 'collapsed' ?> panel-title panel-heading__link" data-toggle="collapse"
                   href="#f-<?= $param->field ?>">
                    <div class="filter-arrow panel-heading__icon"></div>
                    <span class="panel-heading__title"><?= $param->title ?></span>
                </a>
                <span class="popupsmall-button panel-heading__icon filter-question pull-right" data-id="<?= $param->id ?>">?</span>
            </div>

            <div id="f-<?= $param->field ?>"
                 class="panel-body panel-collapse collapse<?= $param->open ? ' in force-open' : '' ?> <?= $param->is_slider ? 'panel-slider' : 'panel-checkbox' ?>"
                 data-type="<?= $param->is_slider ? 'slider' : 'checkbox' ?>">
                <? if($param->is_slider){  ?>
                    <div class="b-nouislider filter-slider">
                        <div class="b-nouislider-serialized">
                            <label for="f-<?= $param->field ?>-val-from"
                                   class="b-nouislider-serialized__label filter-nouislider-from">От</label>

                            <input id="f-<?= $param->field ?>-val-from"
                                       type="text"
                                       class="b-nouislider-serialized__input form-control" >

                            <label for="f-<?= $param->field ?>-val-to"
                                   class="b-nouislider-serialized__label filter-nouislider-to">До</label>
                            <input id="f-<?= $param->field ?>-val-to"
                                   class="b-nouislider-serialized__input form-control">

                            <span class="b-nouislider-serialized__measure filter-measure"><?= $param->post_value ?></span>
                        </div>
                    </div>
                    <div class="b-nouislider-graphics">
                        <div data-name="<?= $param->field ?>" class="noUiSlider"></div>
                    </div>
                <? } else { ?>
                    <? if(isset($param->values)){ ?>
                        <div class="b-checkbox-container filter-checkboxes">
                        <? foreach($param->values as $i=>$val){ ?>
                            <div class="b-checkbox b-checkbox_filter">
                                <input class="b-checkbox__input"
                                       id="f-<?= $param->field ?>-val-<?= $i ?>"
                                       type="checkbox"
                                       name="<?= $param->field ?>" value="<?= $i ?>" />

                                <label class="b-checkbox__text"
                                       for="f-<?= $param->field ?>-val-<?= $i ?>"><?= $param->pre_value ?> <?=$val ?> <?= $param->post_value ?></label>
                            </div>
                        <? } ?>
                        </div>
                    <? } ?>
                <? } ?>
            </div>
        </div>
    <? } ?>

        <div class="b-filter-form__panel filter-offers">
            <div class="b-checkbox">
                <input class="b-checkbox__input" type="checkbox" id="f-offers">
                <label class="b-checkbox__text" for="f-offers">спецпредложения</label>
            </div>
        </div>

        <div class="b-filter-form__panel">
            <div class="b-button b-button_filter" onclick="$('#f-form').submit()">
                <span class="b-button__text">Применить фильтр</span>
                <i class="b-button__icon"></i>
            </div>
        </div>
    </form>
</div>

<script>
    $(function(){

        filter.init({
            slidersData: <?= $this->slidersData ?>,
            postVals: <?= $this->postVals ?>,
            section_id: <?= $section->id ?>,
            subsection_id: <?= isset($this->subsection->id)? $this->subsection->id : 0 ?>
        });

        var content = [];
        content['filter'] = {
            content: <?= $this->qtexts; ?>,
            data: {
                placement: 'right',
                trigger: 'click'
            }
        };
        popupsmall.init({ content: content });

        $('.series-tile > a').click(function(e) {
            if ($.url().param('filter')) {
                e.preventDefault();
                var url = $(this).attr('href');
                url += '?filter=' + encodeURIComponent($.url().param('filter'));
                location.href = url;
            }
        });
    });
</script>