
<? if($entity->seo_title && $entity->seo_text){ ?>
    <div class="row row-second-big"><div class="col-xs-12"><div class="black-top"></div></div></div>
    <div class="row row-second-small" id="seo-title">
        <div class="col-xs-10"><?= $entity->seo_title ?></div>
        <div class="col-xs-2">
            <a class="show-btn" style="cursor: pointer">
                <div class="filter-arrow closed"></div>
                подробнее
            </a>
        </div>

    </div>
    <div class="row row-second-xs"><div class="col-xs-12"><div class="dotted-top"></div></div></div>
    <div class="row row-second-small">
        <div class="col-xs-12" id="seo-text" style="display: none"><span class="seo-body" ><?= $entity->seo_text ?></span></div>
    </div>


    <script type="text/javascript">
        $(function(){
            mainpage.initSeoTextBlock();
        })
    </script>
<? } ?>
