<h1>
    <a href="<?= $this->url('zfcadmin/blog') ?>">Блог</a>
    >
    Термины
</h1>

<h3>Список терминов</h3>

<div class="addPanel">
    <button type="button" class="btn btn-default" id="add-entity">Добавить термин</button>

    <div class="form-inline" id="adding-form" style="display: none">
        <div class="form-group">
            <label class="sr-only" for="inputName">Название</label>
            <input type="text" class="form-control" id="inputName" placeholder="Введите название..."/>
        </div>

        <button type="button" class="btn btn-default" id="adding-complete">Добавить</button>
        <button type="button" class="btn btn-default" id="adding-cancel">Отмена</button>
    </div>
</div>

<table class="table admin-table table-striped">
    <tr>
        <th>Id</th>
        <th>Название раздела</th>
        <th>Управление</th>
    </tr>
    <tbody>
    <? foreach($entities as $entity){ ?>
        <tr class="entity">
            <td><?= $entity->id; ?></td>
            <td><?= $entity->title; ?></td>
            <td>
                <a href="#" class="editBtn">Редактировать</a>
                <a href="#" class="deleteBtn">Удалить</a>
            </td>
        </tr>
    <? } ?>
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function(){
        catalog.baseUrl = '<?= $this->url('zfcadmin/terms') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/terms', array('action'=> 'view')) ?>';
        catalog.init();
    });
</script>