<h1>
    <a href="<?= $this->url('zfcadmin/blog') ?>">Блог</a>
    >
    <a href="<?= $this->url('zfcadmin/terms') ?>">Tермины</a>
    >
    <span id="title"><?= $entity->title; ?></span>
</h1>

<h3>Основная информация</h3>
<table class="table admin-table table-striped">
    <tbody>
    <tr>
        <td>Название</td>
        <td>
            <a href="#" data-type="text" data-name="title" class="editable-param"><?= $entity->title; ?></a>
        </td>
    </tr>
    <tr>
        <td>Буква</td>
        <td>
            <a href="#" data-type="select" data-name="letter" class="editable-param"><?= $letters[$entity->letter]; ?></a>
        </td>
    </tr>
    <tr>
        <td>Описание</td>
        <td>
            <div class="editor-get-btn" data-name="text"><?= $entity->text; ?></div>
        </td>
    </tr>
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function(){
        var letters = <?= json_encode($letters, JSON_FORCE_OBJECT);?>;
        $('a[data-name="letter"]').data('source', letters);

        catalog.parentId = '<?= $entity->id ?>';
        catalog.baseUrl = '<?= $this->url('zfcadmin/terms') ?>';
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.editablesSave
        })
    });
</script>