<? $sl = $this->getHelperPluginManager()->getServiceLocator(); ?>
<?
/** @var integer $scrollToSubsection */
/** @var integer $scrollToSeries */
/** @var integer $scrollToProduct */
$admin = $this->isAllowed('controller/CatalogAdmin');
$displayStyle = \Catalog\Service\CatalogService::DISPLAY_STYLE_LENTS;
?>

<!-- Эти стили нужны для сортировки -->
<style type="text/css">
    .solo-table-sort-asc > .solo-column-arrow
    {
        position: relative;
        top: 10px;
        margin-left: 5px;
        /*border-color: black transparent;*/
        /*border-style: solid;*/
        border-width: 5px 5px 0px 5px;
        height: 0px;
        width: 0px;
    }
    .solo-table-sort-desc > .solo-column-arrow
    {
        position: relative;
        top: -10px;
        margin-left: 5px;
        /*border-color: black transparent;*/
        /*border-style: solid;*/
        border-width: 0px 5px 5px 5px;
        height: 0px;
        width: 0px;
    }
</style>
<? include 'part/part/mobile-modal.phtml'; ?>
<div class="b-section__content breadcumbs_ontop">

    <div class="b-breadcrumbs">
        <? foreach ($breadCrumbs as $bc) { ?>
            <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
        <? } ?>
        <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
    </div>
</div>

<div class="section catalog b-section__content">

    <?
    $i = 0;
    $serNum = 1;
    foreach($subsections as $subsec){
		$index = $scrollToSubsection ? $scrollToSubsection : 30;
		if ($subsec->id != $index) continue;?>
        <div id="subsec-<?=$subsec->id?>">
		
		<? $seriesOne; foreach($seAgg->getSeries($subsec->id) as $series){ if (!$seriesOne) $seriesOne = $series; continue; } $series = $seriesOne; ?>
		
    <div style="display: none">
		<? $imgs = $sl->get('\Catalog\Model\SeriesImgTable')->fetchByCond('parent_id', $series->id, 'order asc'); ?>
        <? foreach($imgs as $img) { ?>
            <? if (!$series->preview && $series->img_gallery == $img->url) continue; ?>
            <? if (!$series->preview && $i++ == 0) continue; ?>

            <? $src = $img->url ? $this->basePath() . '/images/series/' . $img->url : $this->basePath() . '/images/empty-series.png' ?>

            <img style="display: none" src="<?= $src ?>" />

        <? } ?>
    </div>
    <div class="b-goods-gallery">
        <? $i = 0; ?>
        <? foreach($imgs as $img) { ?>
            <? if (!$series->preview && $series->img_gallery == $img->url) continue; ?>
            <? if (!$series->preview && $i++ == 0) continue; ?>
            <div class="b-goods-gallery-item"><i class="b-goods-gallery-item__layout" style="width: 1px"></i>
                <? $minUrl = 'min_' . $img->url ?>
                <? $src = $img->url ? $this->basePath() . '/images/series/' . $img->url : $this->basePath() . '/images/empty-series.png' ?>
                <? $minSrc = $img->url ? $this->basePath() . '/images/series/' . $minUrl : $this->basePath() . '/images/empty-series.png' ?>

                <a class="b-goods-gallery-item__link" href0="<?= $src ?>" rel="gallery">
                    <img class="b-goods-gallery-item__image" src="<?= file_exists($_SERVER['DOCUMENT_ROOT'] . '/images/series/min_' . $img->url) ? $minSrc : $src ?>" alt="<?= $series->visible_title; ?> url" />
                </a>
            </div>
        <? } ?>
    </div>

            <div class="row row-second-xs">
                <div class="col-xs-12">
				<div class="b-goods-flexiable-table">

            <div class="b-goods-flexiable-table__cell" align="left">
                <div class="b-goods-title"><?= $subsec->title ?></div>
            </div>

            <div class="b-goods-flexiable-table__cell"></div>
			</div>
			
			<div class="b-tabs-wrapper b-tabs-wrapper_goods "  role="tabpanel">
            <div class="b-goods-tabs">
                <ul class="b-tabs list-unstyled b-tabs_goods" role="tablist">
                    <li class="b-tabs__tab  active">
                        <a class="b-tabs__link " role="tab" href="#goods_1" data-toggle="tab" aria-controls="goods_1" >Цены и модификации</a>
                    </li>
                    <li class="b-tabs__tab">
                        <a class="b-tabs__link " role="tab" href="#goods_2"  data-toggle="tab" aria-controls="goods_2">Описание и комплектация</a>
                    </li>
                </ul>
            </div>
			<div class="b-tabs-content b-tabs-content_goods tab-content">
				<div class="b-tabs-content__item fade in active tab-pane" role="tabpanel" id="goods_1">
			
                    <? //$seriesOne; foreach($seAgg->getSeries($subsec->id) as $series){ if (!$seriesOne) $seriesOne = $series; ?>

                            <div class="series-block" data-id="<?= $series->id ?>">
                                <div class="row row-second-xs">
                                    <? $equalParameters = $series->equalParams; ?>
                                    <? $shownEqualParams = $series->shownEqualParams; ?>
                                    <? include 'part/part/equal-blocks-inline-lenti.phtml'; ?>
                                </div>
                                <?  $serNum++; ?>
                                <?  if(isset($pAgg)){
                                    $products = $pAgg->getProducts($series->id);
                                    $this->commercialMode = \User\Service\UserService::$commercialMode;
                                    ?>
                                    <div class="row row-second-small">
                                        <div class="col-xs-12" id="testApp_<?= $series->id ?>">
                                            <? include 'part/part/product-table-lenti.phtml'; ?>
                                        </div>
                                    </div>


                                    <? } ?>
                            </div>

                        <? //} $series = $seriesOne; ?>
				</div>
				<div class="b-tabs-content__item fade tab-pane series-description-block" role="tabpanel" id="goods_2" style="padding-left: 30px">
				<div class="row">
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div>
                                        <h2 class="series-description-block__title">Описание</h2>
                                    </div>
                                </div>
                            </div>
                            <div class="row row-second-xs">
                                <div class="col-xs-12 series-description">
                            <?= (($num = strpos('<p>&nbsp;</p>', $series->text)) < 5 && $num !== false) ?
                                substr($series->text, $num+13) : $series->text; ?>
                                </div>
                            </div>
                        </div>
                    </div>
					
                    <? if($series->text_charact = trim($series->text_charact)){ ?>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div>
                                            <h2 class="series-description-block__title">Характеристики</h2>
                                        </div>
                                    </div>
                                </div>
                                <div class="row row-second-xs">
                                    <div class="col-xs-12 series-description">
                                        <?= (($num = strpos('<p>&nbsp;</p>', $series->text_charact)) < 5 && $num !== false) ?
                                            substr($series->text_charact, $num+13) : $series->text_charact ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <? } ?>

                    <? if($series->text_exploit = trim($series->text_exploit)){ ?>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div>
                                            <h2 class="series-description-block__title">Комплектация и условия эксплуатации</h2>
                                        </div>
                                    </div>
                                </div>
                                <div class="row row-second-xs">
                                    <div class="col-xs-12 series-description">
                                        <?= (($num = strpos('<p>&nbsp;</p>', $series->text_exploit)) < 5 && $num !== false) ?
                                            substr($series->text_exploit, $num+13) : $series->text_exploit ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <? } ?>
					
                <? if($series->text_sphere = trim($series->text_sphere)){ ?>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div>
                                            <h2 class="series-description-block__title">Область применения</h2>
                                        </div>
                                    </div>
                                </div>
                                <div class="row row-second-xs">
                                    <div class="col-xs-12 series-description">
                                        <?= (($num = strpos('<p>&nbsp;</p>', $series->text_sphere)) < 5 && $num !== false) ?
                                            substr($series->text_sphere, $num+13) : $series->text_sphere ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <? } ?>

                    <? if($series->text_dimming = trim($series->text_dimming)){ ?>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div>
                                            <h2 class="series-description-block__title">Диммирование (Управление яркостью)</h2>
                                        </div>
                                    </div>
                                </div>
                                <div class="row row-second-xs">
                                    <div class="col-xs-12 series-description">
                                        <?= (($num = strpos('<p>&nbsp;</p>', $series->text_dimming)) < 5 && $num !== false) ?
                                            substr($series->text_dimming, $num+13) : $series->text_dimming ?>
                                    </div>
                                </div>
                                <div class="b-section-dimmers">
                                    <? foreach($dims as $dim){ ?>
                                        <div class="b-section-dimmers__item">
                                            <? $type = strtolower(substr($dim->url, -3)); ?>
                                            <a class="b-section-dimmers__item-link" href="<?= $dim->url ? $this->basePath() . '/images/series_docs/' . $dim->url . '?originalName=' . urlencode($dim->original_name) : ''?>"
                                               target="_blank"
                                                <? if ($type != 'jpg' && $type != 'png' && $type != 'bmp' && $type != 'pdf' ) { ?>

                                                <? } ?>
                                               onclick="ga('send', 'event', 'button', 'click', 'download', '<?= $dim->url ?>');"
                                                >


                                                <span class="pull-left icon-title b-section-dimmers__item-title" style="font-size: 11px; font-weight: bold"><?= $dim->title; ?> (<?= $type ?>)</span>
                                                <span class="pull-right icon-download icon-<?= $type?> b-section-dimmers__item-icon"></span>
                                            </a>
                                        </div>
                                    <? } ?>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12 series-description">
                                        <?= (($num = strpos('<p>&nbsp;</p>', $series->text_after_dimming)) < 5 && $num !== false) ?
                                            substr($series->text_after_dimming, $num+13) : $series->text_after_dimming ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <? } ?>
				</div>
			</div>
			</div>
        </div>
            </div>
        </div>
        <? $i++; ?>
    <? } ?>
    <?=
    $this->partial(
        "catalog/catalog/part/links-block.phtml",
        array(
            'links' => $this->links,
            'forWhat' => 'LED-лент'
        )
    );
    ?>
    <?= \Catalog\Service\CatalogService::renderSeoTextBlock($sl, $section); ?>
</div>

<script type="text/javascript">
    $(function() {
        popup.initCopyLinkBtns();
    });
    /**var screenWidth = $("html").width();
    $('.series-pics').css('width', screenWidth);
    $('.series-pics').css('margin-left', -(screenWidth-$('.catalog :first').width())/2-15);*/
    $(function(){
//        popup.initSeriesPopup();
        popup.renderCartedLines();
        catalogClient.scrollToSeries = <?= $scrollToSeries ? $scrollToSeries : 'false' ?>;
        catalogClient.scrollToProduct = <?= $scrollToProduct ? $scrollToProduct : 'false'  ?>;
        //catalogClient.scrollToSubsection = <?= $scrollToSubsection ? $scrollToSubsection : 'false' ?>;
        catalogClient.initUrl();
    })

    window.setTimeout( function(){
        mainpage.renderUrl();
    }, 100);



</script>