<? $sl = $this->getHelperPluginManager()->getServiceLocator(); ?>
<?
/**
 * @var \Catalog\Model\SubSection[] $subsections
 * @var \Catalog\Service\SeriesAggregator $seAgg
 */

?>

<div class="b-section__content catalog">


    <div class="row">
        <div class="col-md-3 row-second">
            <? include 'part/filter.phtml' ?>

            <? if($section->video){ ?>
                <div class="row row-second">
                    <div class="col-md-12">
                        <iframe width="250" height="200" src="<?= $section->video?>"></iframe>
                    </div>
                </div>
            <? } ?>
        </div>

        <div class="col-md-9">
            <div class="b-section__content-breadcrumbs">
                <div class="b-breadcrumbs">
                    <? foreach ($breadCrumbs as $bc) { ?>
                        <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
                    <? } ?>
                    <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
                </div>
            </div>
            <div id="catalog-filterbar-place"></div>

            <? foreach($subsections as $subsecId=>$subsec){ ?>
                <div class="row row-second" id="subsec-<?= $subsecId?>">
                    <div class="col-md-12">
                        <a class="catalog-section-bar" data-id="<?= $subsec->id ?>"
                           href="<?= empty($subsec->display_name) ?
                               $this->url('catalog', array('action'=>'subsection', 'id'=>$subsec->id)) :
                               $this->url('catalog', array('action'=>'subsection', 'id'=>$subsec->display_name));?>">
                            <h2 style=""><?= $subsec->title; ?></h2>
                        </a>
                    </div>
                </div>
                <div class="row row-second" data-type="catalog">
                        <?
                        if(isset($seAgg)){
                            $i = 0;
                            foreach($seAgg->getSeries($subsecId) as $ser){ ?>
                                <div class="col-md-3 series-tile" data-id="<?= $ser->id ?>">
                                    <?= \Catalog\Service\CatalogService::renderSeriesTile($sl, $ser);?>
                                </div>
                                <? if(($i+1)%4 == 0){ echo '</div><div class="row row-second-small" data-type="catalog">'; }
                                $i++;
                            }
                        }
                        ?>
                </div>
            <? } ?>
            <?=
            $this->partial(
                "catalog/catalog/part/links-block.phtml",
                array(
                    'links' => $this->links,
                    'forWhat' => 'продуктов'
                )
            );
            ?>
            <?= \Catalog\Service\CatalogService::renderSeoTextBlock($sl, $section); ?>
        </div>
    </div>

</div>


<script type="text/javascript">

    $(function(){
        mainpage.renderUrl();
        popup.init({ page: 'catalog', isSection: true });

    });
</script>