<? $sl = $this->getHelperPluginManager()->getServiceLocator(); ?>
<? include 'part/part/mobile-modal.phtml'; ?>
    <div class="b-mobile-catalog visible-xs visible-sm">
        <? foreach ($subsections as $subsecId=>$subsection) { ?>
            <div class="b-mobile-catalog__item">
                <a class="b-mobile-catalog__link text-uppercase"
                   data-target="#catalog_mobile_redirect"
                   data-toggle="modal"
                   data-href="<?= empty($subsection->display_name) ?
                       $this->url('catalog', array('action'=>'subsection', 'id'=>$subsection->id)) :
                       $this->url('catalog', array('action'=>'subsection', 'id'=>$subsection->display_name));?>">
                    <?= $subsection->title; ?>
                </a>
            </div>
        <? } ?>
    </div>
<div class="section b-section__content catalog hidden-xs hidden-sm">
    <div class="b-section__content b-section__content-breadcrumbs">

        <div class="b-breadcrumbs">
            <? foreach ($breadCrumbs as $bc) { ?>
                <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
            <? } ?>
            <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
        </div>

    </div>
    <div class="row row-second-xs">
        <div class="col-xs-6">
            <? include 'part/filter-small.phtml' ?>
        </div>
    </div>

    <div id="catalog-filterbar-place"></div>
    <? $num = 0; ?>
    <? foreach($subsections as $subsecId=>$subsection){ ?>
        <div class="row <?= ($num++ == 0) ? '': 'row-second' ?>" id="subsec-<?= $subsecId?>">
            <div class="col-xs-12">
                <div class="row">
                    <div class="col-xs-12">
                        <a class="catalog-section-bar" data-id="<?= $subsection->id ?>"
                           href="<?= empty($subsection->display_name) ?
                               $this->url('catalog', array('action'=>'subsection', 'id'=>$subsection->id)) :
                               $this->url('catalog', array('action'=>'subsection', 'id'=>$subsection->display_name));?>">
                            <h2><?= $subsection->title; ?></h2>
                        </a>
                    </div>
                </div>

                <div class="row row-second" data-type="catalog">
                    <?
                    if(isset($seAgg)){
                        $i = 0;
                        foreach($seAgg->getSeries($subsection->id) as $ser){ ?>
                            <div class="col-xs-2 series-tile" data-id="<?= $ser->id ?>">
                                <?= \Catalog\Service\CatalogService::renderSeriesTile($sl, $ser);?>
                            </div>
                            <?
                            if(($i+1)%6==0){ echo '</div><div class="row row-second" data-type="catalog">'; }
                            $i++;
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    <? } ?>
    <?=
    $this->partial(
        "catalog/catalog/part/links-block.phtml",
        array(
            'links' => $this->links,
            'forWhat' => 'профилей'
        )
    );
    ?>
    <?= \Catalog\Service\CatalogService::renderSeoTextBlock($sl, $section); ?>
</div>


<script type="text/javascript">
    $(function(){
        popup.init({
            page: 'catalog',
            isSection: true,
        view: '<?= \Catalog\Controller\CatalogController::POPUP_PROFILI ?>'
        });
    });
</script>