<? $sl = $this->getHelperPluginManager()->getServiceLocator(); ?>
<?
/**
 * @var \Catalog\Model\SubSection[] $subsections
 * @var \Catalog\Service\SeriesAggregator $seAgg
 */

?>
<? include 'part/part/mobile-modal.phtml' ?>
<div class="visible-xs visible-sm">
    <div class="b-section__content">

            <div class="b-breadcrumbs">
                <? foreach ($breadCrumbs as $bc) { ?>
                    <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
                <? } ?>
                <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
            </div>

    </div>
    <div class="b-mobile-catalog">

        <? foreach ($subsections as $subsecId => $subsec) { ?>
            <div class="b-mobile-catalog__item b-mobile-catalog__item_subsection"
                 style="background-image: url(<?= $this->basePath() . '/images/subsections/' . $subsec->url ?>)">
                <a class="b-mobile-catalog__link text-uppercase" data-id="<?= $subsec->id ?>"
                   data-target="#catalog_mobile_redirect"
                   data-toggle="modal"
                   data-href="<?= empty($subsec->display_name) ?
                       $this->url('catalog', array('action' => 'subsection', 'id' => $subsec->id)) :
                       $this->url('catalog', array('action' => 'subsection', 'id' => $subsec->display_name)); ?>">
                    <?= $subsec->title; ?>
                </a>

            </div>
        <? } ?>
    </div>
</div>
<div class="b-section__content b-section__content_catalog catalog hidden-xs hidden-sm">


    <div class="row row-second">
        <div class="col-xs-3">
            <? include 'part/filter.phtml' ?>

            <? if ($section->video) { ?>
                <div class="row row-second">
                    <div class="col-xs-12">
                        <iframe width="250" height="200" src="<?= $section->video ?>"></iframe>
                    </div>
                </div>
            <? } ?>
        </div>

        <div class="col-xs-9">
            <div class="b-section__content-breadcrumbs">
                <div class="b-breadcrumbs b-breadcrumbs_no-mt">
                    <? foreach ($breadCrumbs as $bc) { ?>
                        <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
                    <? } ?>
                    <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
                </div>
            </div>
            <div id="catalog-filterbar-place"></div>

            <? foreach ($subsections as $subsecId => $subsec) { ?>
                <div class="row row-second" id="subsec-<?= $subsecId ?>">
                    <div class="col-xs-12">
                        <a class="catalog-section-bar" data-id="<?= $subsec->id ?>"
                           href="<?= empty($subsec->display_name) ?
                               $this->url('catalog', array('action' => 'subsection', 'id' => $subsec->id)) :
                               $this->url('catalog', array('action' => 'subsection', 'id' => $subsec->display_name)); ?>">
                            <h2 style=""><?= $subsec->title; ?></h2>
                        </a>
                    </div>
                </div>
                <div class="row row-second" data-type="catalog">
                    <?
                    if (isset($seAgg)) {
                        $i = 0;
                        foreach ($seAgg->getSeries($subsecId) as $ser) { ?>
                            <div class="col-xs-3 series-tile" data-id="<?= $ser->id ?>">
                                <?= \Catalog\Service\CatalogService::renderSeriesTile($sl, $ser); ?>
                            </div>
                            <? if (($i + 1) % 4 == 0) {
                                echo '</div><div class="row row-second-small" data-type="catalog">';
                            }
                            $i++;
                        }
                    }
                    ?>
                </div>
            <? } ?>
            <?=
            $this->partial(
                "catalog/catalog/part/links-block.phtml",
                array(
                    'links' => $this->links,
                    'forWhat' => 'продуктов'
                )
            );
            ?>
            <?= \Catalog\Service\CatalogService::renderSeoTextBlock($sl, $section); ?>
        </div>
    </div>

</div>


<script type="text/javascript">

    $(function () {
        mainpage.renderUrl();
        popup.init({page: 'catalog', isSection: true});

    });
</script>