<? $sl = $this->getHelperPluginManager()->getServiceLocator(); ?>
<?
$admin = $this->isAllowed('controller/CatalogAdmin');
$displayStyle = \Catalog\Service\CatalogService::DISPLAY_STYLE_POWER;
?>
<?
/** @var integer $scrollToSubsection */
/** @var integer $scrollToSeries */
/** @var integer $scrollToProduct */

?>
<? include 'part/part/mobile-modal.phtml'; ?>
<div class="b-section__content b-section__content-breadcrumbs">

    <div class="b-breadcrumbs">
        <? foreach ($breadCrumbs as $bc) { ?>
            <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
        <? } ?>
        <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
    </div>
</div>

<div class="section catalog b-section__content">
    <div class="row catalog-submenu">
        <div class="col-xs-12" style="text-align: center">
            <div class="row no-tb-padding">
                <div class="col-xs-12 no-tb-padding">
                    <?
                    //todome: исправить это мракобесие
                    $i = 0;
                    foreach($subsections as $subsec){ ?>
                        <div class="catalog-submenu-item dotted-left">
                            <a href="<?= $this->url('home') ?>catalog/section/<?= $section->id ?>/?p=subsec-<?= $subsec->id?>"><?= $subsec->title; ?></a>
                        </div>
                        <?  if(($i+1)%4 == 0){echo'</div></div>
                    <div class="row no-tb-padding row-second-xxs"><div class="col-xs-12 no-tb-padding"><div class="dotted-top"></div></div></div>
                    <div class="row no-tb-padding"><div class="col-xs-12 no-tb-padding">';}
                        $i++;
                    } ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="black-bottom absolute-width"></div>
    </div>

<!--    <div class="row row-second">-->
<!--        <div class="col-xs-6 tablefilter">-->
<!--            --><?// include 'part/filter-small.phtml' ?>
<!--        </div>-->
<!--    </div>-->

    <div class="row row-second-xs">
        <div class="col-xs-12">
<!--            <div class=" dotted-top"></div>-->
        </div>
    </div>

    <div id="catalog-filterbar-place"></div>

    <?
    $i = 0;
    $serNum = 1;
    foreach($subsections as $subsec){ ?>
        <div id="subsec-<?=$subsec->id?>">
            <? if ($subsec->url) { ?>
            <div class="series-pics " style="position: relative">
                <img class="drivers_pic" src="<?= $this->basePath() . '/images/subsections/' . $subsec->url ?>" alt="<?= $subsec->title?>">
                <div class="absolute-banner-text-block absolute-banner-text-block-alt">
                    <div class="container">
                        <div class="banner-backgrounded-wrapper banner-backgrounded-wrapper-alt">
                            <? if ( $subsec->title) { ?>

                                <span class="banner-title backgrounded-alt" <?= !$subsec->title ? 'style="padding-bottom: 16px;"' : '' ?>><?= $subsec->title ?>&nbsp;&nbsp;</span><br />

                            <? } ?>
                            <? if ( $subsec->text) { ?>

                                <span class="banner-text backgrounded-alt"><?= $subsec->text ?>&nbsp;&nbsp;&nbsp;</span>

                            <? } ?>
                        </div>
                    </div>
                </div>
            </div>

    <? } else { ?>
        <div class="row">
            <div class="col-xs-12">
                <h1><?= $subsec->title ?></h1>
                <div class="grey-bottom"></div>
            </div>
        </div>
    <? }?>

            <div class="row row-second-xs">
                <div class="col-xs-12">
                    <?

                        foreach($seAgg->getSeries($subsec->id) as $series){ ?>

                            <div class="series-block" data-id="<?= $series->id ?>">
<!--                                <div class="row">-->
<!--                                    <div class="col-xs-12">-->
<!--                                        <div class="title-pitanie">-->
<!--                                            <h2>--><?//= $series->title ?><!--</h2>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                                <div class="row"><div class="col-xs-12"><div class="dotted-bottom"></div></div></div>-->
                                <div class="row row-second-xs">
                                    <? $equalParameters = $series->equalParams; ?>
                                    <? $shownEqualParams = $series->shownEqualParams; ?>
                                    <? include 'part/part/equal-blocks-inline.phtml'; ?>
                                </div>
                                <?  $serNum++; ?>
                                <?  if(isset($pAgg)){
                                    $products = $pAgg->getProducts($series->id);

                                    ?>
                                    <div class="row row-second-small">
                                        <div class="col-xs-12" id="testApp_<?= $series->id ?>">
                                            <? include 'part/part/product-table-pitaine.phtml'; ?>
                                        </div>
                                    </div>



                                    <script>
//                                        AppFactory("testApp_<?//= $series->id ?>//", "example<?//= $series->id ?>//", ["solo.table", "myFilters"]);
                                    </script>


                                    <? } ?>
                            </div>

                        <? } ?>
                </div>
            </div>
        </div>
        <? $i++; ?>
    <? } ?>
    <?=
    $this->partial(
        "catalog/catalog/part/links-block.phtml",
        array(
            'links' => $this->links,
            'forWhat' => 'блоков питания'
        )
    );
    ?>
    <?= \Catalog\Service\CatalogService::renderSeoTextBlock($sl, $section); ?>
</div>

<script type="text/javascript">
    var screenWidth = $("html").width();
    $('.series-pics').css('width', screenWidth);
    $('.series-pics').css('margin-left', -(screenWidth-$('.catalog :first').width())/2-15);
    $(function(){
        popup.initSeriesPopup();
        popup.renderCartedLines();
        catalogClient.scrollToSeries = <?= $scrollToSeries ? $scrollToSeries : 'false' ?>;
        catalogClient.scrollToProduct = <?= $scrollToProduct ? $scrollToProduct : 'false'  ?>;
        catalogClient.scrollToSubsection = <?= $scrollToSubsection ? $scrollToSubsection : 'false' ?>;
        catalogClient.initUrl();
    })

    window.setTimeout( function(){
        mainpage.renderUrl();
    }, 100);



</script>