<? $sl = $this->getHelperPluginManager()->getServiceLocator(); ?>
<div class="b-section__content b-section__content-breadcrumbs">

    <div class="b-breadcrumbs">
        <? foreach ($breadCrumbs as $bc) { ?>
            <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
        <? } ?>
        <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
    </div>
</div>
<div class="section b-section__content catalog">
    <div class="row">
        <div class="col-md-6">
            <? include 'part/filter-small.phtml' ?>
        </div>
    </div>

    <div id="catalog-filterbar-place"></div>

    <div class="row row-second" data-type="catalog"  data-action="series">
        <?
        if(isset($series)){
            $i = 0;
            foreach($series as $ser){ ?>
                <div class="col-md-2 series-tile" data-id="<?= $ser->id ?>">
                    <?= \Catalog\Service\CatalogService::renderSeriesTile($sl, $ser);?>
                </div>
                <?
                if(($i+1)%6==0){ echo '</div><div class="row row-second" data-type="catalog" data-action="series">'; }
                $i++;
            }
        }
        ?>
    </div>
    <?=
    $this->partial(
        "catalog/catalog/part/links-block.phtml",
        array(
            'links' => $this->links,
            'forWhat' => 'профилей'
        )
    );
    ?>
    <?= \Catalog\Service\CatalogService::renderSeoTextBlock($sl, $subsection); ?>
</div>


<script type="text/javascript">
    $(function(){
        popup.init({
            bid: <?= $this->bid ?>,
            pid : <?= $this->pid ? $this->pid : 0 ?>,
            btype: "<?= $this->btype ?>",
            baction: "<?= $this->baction ?>",
            parentUrl: "<?= $this->parentUrl ?>",
            page: 'catalog',
            view: '<?= \Catalog\Controller\CatalogController::POPUP_PROFILI ?>'
        });
    });
</script>