<? $sl = $this->getHelperPluginManager()->getServiceLocator(); ?>

<div class="b-section__content catalog">
    <div class="row">
        <div class="col-md-3">
            <? include 'part/filter.phtml' ?>

            <? if($subsection->video){ ?>
                <div class="row row-second">
                    <div class="col-md-12">
                        <iframe width="250" height="200" src="<?= $subsection->video?>"></iframe>
                    </div>
                </div>
            <? } ?>
        </div>

        <div class="col-md-9">
            <div id="catalog-filterbar-place"></div>
            <div class="b-section__content b-section__content-breadcrumbs">

                <div class="b-breadcrumbs">
                    <? foreach ($breadCrumbs as $bc) { ?>
                        <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
                    <? } ?>
                    <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
                </div>
            </div>
            <div class="row row-second" data-type="catalog" data-action="series">
                <? $i = 0; foreach($series as $ser){ ?>
                    <div class="col-md-3 series-tile" data-id="<?= $ser->id ?>">
                        <?= \Catalog\Service\CatalogService::renderSeriesTile($sl, $ser); ?>
                    </div>
                <? if(($i+1)%4==0){ echo '</div><div class="row row-second-small" data-type="catalog" data-action="series">'; }
                    $i++;
                } ?>
            </div>
            <?= \Catalog\Service\CatalogService::renderSeoTextBlock($sl, $subsection); ?>
        </div>
    </div>
</div>