<div class="container">
    <div class="row">
        <div class="col-md-12 text-center text-small">
            <?= \Application\Service\ApplicationService::getFormedDate($news->date) ?>
        </div>
    </div>
    <? if ($news->img) { ?>
    <div class="row">
        <div class="col-md-12 popup-gallery-img">
            <? $src = $this->basePath() . '/images/news/' . $news->img ?>
            <img style=" margin: 0 auto; width: auto; height: 360px;" src="<?= $src ?>" alt="<?= $news->title; ?>"/>
        </div>
    </div>
    <? } ?>
    <div class="row">
        <div class="col-md-12">
            <div class="row" style="margin-top: 20px">
                <div class="row">

                    <div class="col-md-12">
                        <h1><?=  $news->title; ?></h1>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="dotted-bottom"></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6 col-md-offset-3"><?= $news->text ?></div>
                </div>
            </div>
        </div>
    </div>



    <?= \Catalog\Service\CatalogService::renderPopupNav($sl, $prevNews, $nextNews, 'news'); //навигация ?>
</div>
<script>
    popup.pageTitle = "<?= $news->title ?>";
</script>