<h1>
    <a href="<?= $this->url('zfcadmin/blog') ?>">Блог</a>
    >
    Статьи
</h1>

<div class="section">
    <h3>Список статьей</h3>

    <div class="addPanel">
        <button type="button" class="btn btn-default" id="add-entity">Добавить статью</button>

        <div class="form-inline" id="adding-form" style="display: none">
            <div class="form-group">
                <label class="sr-only" for="inputName">Название</label>
                <input type="text" class="form-control" id="inputName" placeholder="Введите название..."/>
            </div>

            <button type="button" class="btn btn-default" id="adding-complete">Добавить</button>
            <button type="button" class="btn btn-default" id="adding-cancel">Отмена</button>
        </div>
    </div>

    <table class="table admin-table  table-striped">
        <tr>
            <th>Id</th>
            <th>Название</th>
            <th>Управление</th>
        </tr>
        <tbody id="sortable">
        <? foreach($entities as $entity){ ?>
            <tr class="entity">
                <td><?= $entity->id; ?></td>
                <td><?= $entity->title; ?></td>
                <td>
                    <a href="#" class="editBtn">Редактировать</a>
                    <a href="#" class="deleteBtn">Удалить</a>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    $(function(){
        catalog.baseUrl = '<?= $this->url('zfcadmin/articles') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/articles', array('action'=> 'view')) ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::ARTICLES ?>';
        catalog.init();
    });
</script>