<?
/**
 * @var array $members
 * @var \Developers\Model\Developer[] $developers
 * @varDevelopersts\Model\Developer $developer
 * @vDevelopersects\Model\Developer[] $rDevelopersojects
 * @var \Catalog\Model\Series[] $relatedSeries
 * @var $sl
 * @var Developers\Model\Developer $developer
 */
?>

<div class="b-brand b-section">
    <div class="b-section__content">
        <div class="b-breadcrumbs">
            <? foreach ($breadCrumbs as $bc) { ?>
                <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
            <? } ?>
            <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
        </div>
    </div>
    <div class="b-section__content b-section__content_brand">
        <img src="/images/developers/<?= $developer->imgName ?>" class="b-brand__main-image"/>

        <div class=" b-brand-info">
            <div class="b-brand-info__left">
                <img class="b-brand-info__logo" src="/images/developers/<?= $developer->previewName ?>"/>
            </div>
            <div class="b-brand-info__right">
                <a href="http://<?= $developer->url ?>" class="b-brand-info__link"><?= $developer->url ?></a>
            </div>
        </div>
        <div class="b-brand__text">
            <?= $developer->text ?>
        </div>


        <? if (count($this->catalogs)) { ?>
        <div class="b-brand-catalogs">
            <h2 class="b-brand-catalogs__heading text-center">Каталоги <?= $developer->title ?></h2>
            <div class="b-slider b-slider_brand-catalogs">
                <? foreach ($this->catalogs as $catalog) { ?>
                <div class="b-slider__item b-slider_brand-catalogs__item">
                    <div class="b-slider_brand-catalogs__item-inner">
                        <a href="/images/documents/<?= $catalog->file_name ?>"
                           class="b-slider_brand-catalogs__link"
                           target="_blank"
                            >
                            <div class="b-slider_brand-catalogs__item-title">
                                <div class="b-slider_brand-catalogs__item-title-inner">
                                    <?= $catalog->title ?>
                                </div>

                            </div>
                        </a>
                        <img class="b-slider_brand-catalogs__image" src="/images/documents/<?= $catalog->img_name ?>"/>

                    </div>
                </div>
                <? } ?>

            </div>
        </div>
        <? } ?>

    </div>  </div>
<script type="text/javascript">
    (function () {
        var $this = jQuery('.b-slider_brand-catalogs');
        $this.slick({
            dots: false,
            infinite: true,
            draggable: browser.mobile ? true : false,
            speed: browser.mobile ? 300 : 500,
            touchThreshold: browser.mobile ? 5 : 50,
            slidesToShow:3,
            variableWidth:false,
            arrows: browser.mobile ? false : true,
            prevArrow: "<a href=\"javascript:void(0)\"" +
            " class=\"b-simple-arrow  b-simple-arrow_prev b-slider_blog__arrow_prev\">" +
            "</a>",
            nextArrow: "<a href=\"javascript:void(0)\"" +
            " class=\"b-simple-arrow  b-simple-arrow_next b-slider_blog__arrow_next\">" +
            "</a>"
        });


    })();
</script>