<div class="row">
    <div class="col-md-12 text-center">
        <h1><?= $worker->title; ?></h1>
    </div>
</div>

<div class="row row-second">
    <div class="col-md-6">Должность:</div>
    <div class="col-md-6"><?= $worker->role; ?></div>
</div>

<? if($worker->phone){?>
    <div class="row">
        <div class="col-md-6">Телефон:</div>
        <div class="col-md-6"><?= $worker->phone; ?></div>
    </div>
<? } ?>

<? if($worker->mail){?>
    <div class="row">
        <div class="col-md-6">Почта:</div>
        <div class="col-md-6"><?= $worker->mail; ?></div>
    </div>
<? } ?>

<div class="row row-second">
    <div class="col-md-12">
        <?= $worker->text; ?>
    </div>
</div>