<div class="b-developers b-section">
    <div class="b-section__content">
        <div class="b-breadcrumbs">
            <a class="b-breadcrumbs__item" href="/">Главная</a>&nbsp;/

            <strong class="b-breadcrumbs__item b-breadcrumbs__item_active">Производители</strong>
        </div>
    </div>
    <div class="b-section__content b-section__content_developers">

        <div class="b-tabs-wrapper b-tabs-wrapper_developers">
            <div class="b-tabs-wrapper_developers__buttons">
                <br/>

                <h2 class="text-center">Светотехнические производители</h2><br/><br/>

                <ul class="b-tabs b-tabs_developers list-unstyled">
                    <li class="b-tabs__tab active">
                        <a class="b-tabs__link  text-center" href="#developers_1" data-toggle="tab">Складские
                            позиции</a>
                    </li>
                    <li class="b-tabs__tab">
                        <a class="b-tabs__link  text-center" href="#developers_2" data-toggle="tab">Проектные
                            партнеры</a>
                    </li>

                </ul>
            </div>
            <div class="b-tabs-content ng-cloak">
                <div class="b-tabs-content__item fade in active" id="developers_1">
                    <? foreach($this->developers[1] as $i=>$developer){ ?>
                    <div class="b-developer">
                        <div class="b-developer__left">
                            <a href="/brands/view/<?= $developer->id ?>">
                            <img src="/images/developers/<?= $developer->previewName ?>"/>
                            </a>
                        </div>
                        <div class="b-developer__right">
                            <hr class="dotted-separator"/>
                            <a href="/brands/view/<?= $developer->id ?>">
                            <h2 class="b-developer__heading"><?= $developer->title ?></h2>
                            </a>
                            <p><a href="htt://<?= $developer->url ?>"><?= $developer->url ?></a></p>

                            <p class="b-developer__text"
                               text-cut="{'lines':3, 'text' : '.b-developer__cutted-text'}">
                        <span class="b-developer__cutted-text">
                           <?= $developer->description ?>
                            </span><a href="/brands/view/<?= $developer->id ?>" class="b-developer__link-more">читать подробнее</a>
                            </p>
                        </div>
                    </div>
                    <? } ?>

                </div>
                <div class="b-tabs-content__item fade" id="developers_2">
                    <? foreach($this->developers[2] as $i=>$developer){ ?>
                    <div class="b-developer">
                        <div class="b-developer__left">
                            <a href="/brands/view/<?= $developer->id ?>">
                                <img src="/images/developers/<?= $developer->previewName ?>"/>
                            </a>
                        </div>
                        <div class="b-developer__right">
                            <hr class="dotted-separator"/>
                            <a href="/brands/view/<?= $developer->id ?>">
                                <h2 class="b-developer__heading"><?= $developer->title ?></h2>
                            </a>
                            <p><a href="htt://<?= $developer->url ?>"><?= $developer->url ?></a></p>

                            <p class="b-developer__text"
                               text-cut="{'lines':3, 'text' : '.b-developer__cutted-text'}">
                        <span class="b-developer__cutted-text">
                           <?= $developer->description ?>
                            </span><a href="/brands/view/<?= $developer->id ?>" class="b-developer__link-more">читать подробнее</a>
                            </p>
                        </div>
                    </div>
                    <? } ?>
                </div>

            </div>
        </div>
    </div>
</div>

<script type="application/javascript">
    $(function() {
        $('a.b-tabs__link').click(function (e) {
            e.preventDefault();
            var h = $(this).attr('href');
            if(history.pushState) {
                history.pushState(null, null, h);
            }
            else {
                location.hash = h;
            }
            //location.hash=h;
            $(this).tab('show');
        });

        var url = document.location.toString();
        if (url.match('#')) {
            var hash = "";
            if (url.split('#')[1].substring(0,1) == '/') {
                hash = url.split('#')[1].substring(1);
            } else {
                hash = url.split('#')[1];
            }

            $('a.b-tabs__link[href=#'+hash+']').tab('show') ;
        }
    });
</script>