<h1>
    <a href="<?= $this->url('zfcadmin/geobanners') ?>">Геобаннеры</a>
    >
    <? /** @var $entity \IPGeoBase\Model\GeoBanner */ ?>
    <span id="title"><?= $entity->title; ?></span>
</h1>

<div class="section">
    <h3>Основная информация</h3>
    <table class="table admin-table ">
        <tbody>
        <tr>
            <td>Название</td>
            <td>
                <a href="#" data-type="text" data-name="title" class="editable-param"><?= $entity->title; ?></a>
            </td>
        </tr>
		<tr>
            <td>Страна</td>
            <td>
                <a href="#" data-type="select" data-name="country_code"
					data-source='<?= \Zend\Json\Json::encode($countries); ?>'
					data-value='<?= $entity->country_code; ?>' class="editable-param">
						<?= $countries[$entity->country_code]; ?>
				</a>
            </td>
        </tr>
        <tr>
            <td>Регион</td>
            <td>
                <a href="#" data-type="select" data-name="region_code"
					data-source='<?= \Zend\Json\Json::encode($regions); ?>'
					data-value='<?= $entity->region_code; ?>' class="editable-param">
						<?= $regions[$entity->region_code]; ?>
				</a>
            </td>
        </tr>
        <tr>
            <td>Выберите тип раздела для баннера</td>
            <td>
                <? $sectionTypes = array('-1' => "Шапка сайта", '1' => "Раздел", '2' => "Подраздел", '3' => "Серия"); ?>
                <a href="#" data-type="select" data-name="section_type"
                   data-source='<?= \Zend\Json\Json::encode($sectionTypes); ?>'
                   data-value="<?= $entity->section_type; ?>" class="editable-param">
                    <?= $sectionTypes[$entity->section_type] ?>
                </a>
            </td>
        </tr>

        <tr>
            <td>ID раздела/подраздела/серии</td>
            <td>
                <a href="#" data-type="text" data-name="section_id" class="editable-param"><?= $entity->section_id; ?></a>
            </td>
        </tr>
        <tr>
            <td>Текст</td>
            <td>
                <div class="editor-get-btn" data-name="text"><?= $entity->text; ?></div>
            </td>
        </tr>
		<tr>
            <td>Адрес ссылки</td>
            <td>
				<a href="#" data-type="text" data-name="link" class="editable-param"><?= $entity->link; ?></a>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<div class="section" id="imageMapper">
    <!--div ng-controller="ImageCtrl">
        <h3>Изображение на баннере</h3>

        <div
            ng-single-image-upload
            parent-type="geoBanner"
            parent-id="<?= $entity->id ?>"
            folder="geobanners"
            field="img"
            img="<?= $entity->imgName ? $entity->imgName : "" ?>"
            img-id ="<?= $entity->img ? $entity->img : "" ?>"
            ></div>

        <script type="application/javascript">
            AppFactory("imageMapper", "images", ["imageMapper", "ur.file"]);
        </script>
    </div-->
</div>


<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= $entity->id ?>';
        catalog.type = 'prmember';
        catalog.baseUrl = '<?= $this->url('zfcadmin/geobanners') ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::IPGEOBASE ?>';
        catalog.init();
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.editablesSave
        });

    });
</script>