<div class="b-info-page b-section">
    <div class="b-section__content">
        <div class="b-breadcrumbs">
            <? foreach ($breadCrumbs as $bc) { ?>
                <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
            <? } ?>
            <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
        </div>
    </div>
    <div class="b-section__content b-delivery">
        <div class="b-tabs-wrapper b-tabs-wrapper_payment-nav">
            <ul class="b-tabs list-unstyled">
                <li class="b-tabs__tab active">
                    <a class="b-tabs__link  text-center" href="#paymentInfo_1" data-toggle="tab"><?= $entity->title1 ?></a>
                </li>
                <li class="b-tabs__tab">
                    <a class="b-tabs__link  text-center" href="#paymentInfo_2" data-toggle="tab"><?= $entity->title2 ?></a>
                </li>
                <li class="b-tabs__tab">
                    <a class="b-tabs__link  text-center" href="#paymentInfo_3" data-toggle="tab"><?= $entity->title3 ?></a>
                </li>
            </ul>
            <div class="b-tabs-content" style="padding: 18px">
                <div class="b-tabs-content__item fade in active" id="paymentInfo_1">
                    <?= $entity->text1 ?>
                </div>
                <div class="b-tabs-content__item fade" id="paymentInfo_2">
                    <?= $entity->text2 ?>
                    <div id="demo" class="collapse delivery-details"><?= $entity->text2_details ?></div>
                    <?= $entity->text2_part2 ?>
                </div>
                <div class="b-tabs-content__item fade" id="paymentInfo_3">
                    <?= $entity->text3 ?>
                </div>

            </div>
        </div>
    </div>
</div>