<div class="b-guarantee-page b-section">
    <div class="b-section__content">
        <br/>
        <h4><?= $entity->title ?></h4>
        <hr class="solid-separator"/>
        <div class="text-center" style="padding-left: 15%; padding-right: 15%">
            <br /><br />
            <?= $entity->text1 ?>
            <br />
            <br />
            <br />
        </div>
        <hr class="solid-separator" />
        <br/>
        <?= $entity->text2 ?>
        <br/>
        <h4><?= $entity->title2 ?></h4>
        <hr class="solid-separator" />
        <br/>
        <?= $entity->text3 ?>
    </div>
</div>
