<div class="b-guarantee-page b-section">

    <div class="b-section__content">
        <div class="b-breadcrumbs">
            <? foreach ($breadCrumbs as $bc) { ?>
                <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
            <? } ?>
            <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
        </div>
    </div>
    <div class="b-section__content b-guarantee">
        <div class="text-center" style="padding-left: 15%; padding-right: 15%">
            <br /><br />
            <?= $entity->text1 ?>
            <br />
            <br />
            <br />
        </div>
        <hr class="solid-separator" />
        <br/>
        <?= $entity->text2 ?>
        <br/>
        <h4><?= $entity->title2 ?></h4>
        <hr class="solid-separator" />
        <br/>
        <?= $entity->text3 ?>
    </div>
</div>
