<div class="b-partners-page">

    <div class="b-section__content">
        <div class="b-breadcrumbs">
            <? foreach ($breadCrumbs as $bc) { ?>
                <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
            <? } ?>
            <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
        </div>
    </div>
    <div class="b-section b-partners-page__1st-section">

        <div class="b-section__content">
            <div class=" b-business-proposal">
                <div class="b-business-proposal__inner">
                    <h1 class="b-business-proposal__heading">
                        <?= $entity->title1 ?>
                    </h1>
                    <br/>
                    <p>
                        <?= $entity->text1 ?>
                    </p>
                </div>
            </div>

            <div class="large-line text-center b-mt5">
                <p>
                    <span class="b-dotted-decorated b-dotted-decorated_upper">Если вы хотите стать нашим партнером и приобретать</span><br />

                    предлагаемую продукцию по специальным ценам,<br />
                    <span class="b-dotted-decorated b-dotted-decorated_downed">  то заполните карту партнера <a ng-controller="PopupController" href="javascript:void(0)" ng-click="getPopup(ALEDO_POPUP_PARTNER_CARD)">здесь</a></span>
                </p>
            </div>
        </div>
    </div>
    <div class="b-section b-partners-page__2nd-section">
        <div class="b-section__content">
            <div class=" b-business-proposal">
                <div class="b-business-proposal__inner">
                    <h1 class="b-business-proposal__heading">
                        <?= $entity->title2 ?>
                    </h1>
                    <br />

                    <p>
                        <?= $entity->text2 ?>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="b-section">
        <div class="b-section__content">
            <br /><br /><br />
            <h1 class="text-center"><?= $entity->title3 ?></h1>
            <br />
            <div class="b-tabs-wrapper b-tabs-wrapper_partners-tabs">
                <ul class="b-tabs list-unstyled">
                    <li class="b-tabs__tab active">
                        <a class="b-tabs__link  text-left" href="#partnersTab_1" data-toggle="tab"><?= $entity->tab1_head ?></a>
                    </li>
                    <li class="b-tabs__tab">
                        <a class="b-tabs__link  text-left" href="#partnersTab_2" data-toggle="tab"><?= $entity->tab2_head ?></a>
                    </li>
                    <li class="b-tabs__tab">
                        <a class="b-tabs__link  text-left" href="#partnersTab_3" data-toggle="tab">
                            <?= $entity->tab3_head ?>
                        </a>
                    </li>
                    <li class="b-tabs__tab">
                        <a class="b-tabs__link b-tabs__link_active text-left" href="#partnersTab_4" data-toggle="tab"><?= $entity->tab4_head ?></a>
                    </li>
                </ul>
                <div class="b-tabs-content">
                    <div class="b-tabs-content__item fade in active" id="partnersTab_1">
                        <?= $entity->tab1_body ?>
                    </div>
                    <div class="b-tabs-content__item fade" id="partnersTab_2">
                        <?= $entity->tab2_body ?>
                    </div>
                    <div class="b-tabs-content__item fade" id="partnersTab_3">
                        <?= $entity->tab3_body ?>
                    </div>
                    <div class="b-tabs-content__item fade" id="partnersTab_4">
                        <?= $entity->tab4_body ?>
                    </div>
                </div>
            </div>
            <hr class="dotted-separator" />
            <br /><br />
            <h1 class="text-center"><?= $entity->title4 ?></h1>
            <br />
            <div class="text-center">
                <img src="/Content/images/aledo-logo.svg" height="55" class="b-pl5" />
                <br /><br /><br />
                <div class="large-line">
                    <?= $entity->text4 ?>
                </div>
                <h3><strong><a href="/info/service" class="b-hover-yellow b-hover-decorated"><?= $entity->more ?></a></strong></h3>
            </div>
        </div>
    </div>
</div>