<div class="b-info-page b-section">

    <div class="b-section__content">
        <div class="b-breadcrumbs">
            <? foreach ($breadCrumbs as $bc) { ?>
                <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
            <? } ?>
            <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
        </div>
    </div>
    <div class="b-section__content">
        <br />
        <h4>ДОСТАВКА И ОПЛАТА</h4>
        <br />
        <div class="b-tabs-wrapper b-tabs-wrapper_payment-nav">
            <ul class="b-tabs list-unstyled">
                <li class="b-tabs__tab active">
                    <a class="b-tabs__link  text-center" href="#paymentInfo_1" data-toggle="tab">Как заказать</a>
                </li>
                <li class="b-tabs__tab">
                    <a class="b-tabs__link  text-center" href="#paymentInfo_2" data-toggle="tab">Как купить</a>
                </li>
                <li class="b-tabs__tab">
                    <a class="b-tabs__link  text-center" href="#paymentInfo_3" data-toggle="tab">Как оплатить</a>
                </li>
            </ul>
            <div class="b-tabs-content">
                <div class="b-tabs-content__item fade in active" id="paymentInfo_1">
                    <ul class="text-yellow" style="padding: 18px">
                        <li><h5 class="text-gray"><strong>Вы можете оофрмить заказ как Юридическое или Физическое лицо</strong></h5></li>
                        <li>
                            <h5 class="text-gray"><strong>Вы можете оформить заказ</strong></h5>
                            <ul class="text-gray list-unstyled">
                                <li>-По телефону</li>
                                <li>-По телефону</li>
                                <li>-По телефону</li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="b-tabs-content__item fade" id="paymentInfo_2">
                    о оборудоваwwwdwdwи решить эту проблему для себя и готовы предложить широкий ассо
                </div>
                <div class="b-tabs-content__item fade" id="paymentInfo_3">
                    о оборудования с хорошим соотношением цена-качество, которое можно было бы приобрести в России, здесь и сейчас.
                    Мы смогли решить эту проблему для себя и готовы предложить широкий ассо
                </div>

            </div>
        </div>
    </div>
</div>