<div class="b-service-page b-section">
    <script src="/Scripts/jquery.maskedinput.js"></script>

    <div class="b-section b-section_service">
        <div class="b-section__content">
            <img src="/Content/images/aledo-service/service-aledo.svg" height="480"/>
        </div>

    </div>
    <div class="b-section__content b-section__content_service-content text-center">
        <h1>Наш сервис экономит время</h1>
        <p class="text-bigger">
            Вам больше не нужно звонить и узнавать наличие товара на складе.<br />
            Наш склад всегда
        </p>
        <h4 class="b-service-page__advantages-phrases">ДОСТУПЕН ONLINE</h4>
        <br /><br /><br />
        <img src="/Content/images/aledo-service/image_1.png" />

    </div>
    <hr class="dotted-separator" />
    <div class="b-section__content b-section__content_service-content text-center b-pb9">
        <h1>Наш сервис считает ваши деньги</h1>
        <p class="text-bigger">Вы всегда видите ваши персональные </p>
        <h4 class="b-service-page__advantages-phrases">ЗАКУПОЧНЫЕ ЦЕНЫ</h4>
        <br /><br /><br />
        <img src="/Content/images/aledo-service/image_2.png" />

    </div>
    <hr class="dotted-separator" />
    <div class="b-section__content b-section__content_service-content text-center">
        <h1>Наш сервис помогает зарабатывать</h1>
        <p class="text-bigger">Вы быстрее, а значит</p>
        <h4 class="b-service-page__advantages-phrases">ЭФФЕКТИВНЕЕ КОНКУРЕНТОВ</h4>
        <br /><br /><br />
        <img src="/Content/images/aledo-service/image_3.png" />

    </div>
    <hr class="dotted-separator" />
    <div class="b-section__content b-section__content_service-content text-center b-pb9">
        <h1>Ваши клиенты всегда довольны</h1>
        <p class="text-bigger">
            Вы всегда быстро им отвечаете. Даже в выходные дни.<br />
            Даже если вы работаете
        </p>
        <h4 class="b-service-page__advantages-phrases">В ДРУГОМ ЧАСОВОМ ПОЯСЕ</h4>
        <br /><br /><br />
        <img src="/Content/images/aledo-service/image_4.png" />

    </div>
    <div class="b-section__content b-section__content_partnership text-center">
        <div class="b-partnership text-left">
            <div class="b-partnership__row">
                <div class="b-partnership__cell b-partnership__cell_left">
                    <p>
                        <strong>Вы уже являетесь нашим партнёром,</strong><br />
                        но еще не используете сервис aledo-pro:<br /><br />
                    </p>
                    <ul class="b-partnership__list list-unstyled">
                        <li class="b-partnership__list-item">
                            Пройдите регистрацию <strong><a data-toggle="modal" data-target="#registration_modal" href="javascript:void(0)">здесь</a></strong>
                            <i class="b-partnership__list-item-num">1</i>
                        </li>
                        <li class="b-partnership__list-item">
                            Мы предоставим Вам персональные цены
                            и открываем доступ к нашему складу<br />
                            <small>
                                <i>
                                    авторизация в нашей системе может
                                    занимать до 24 часов)
                                </i>
                            </small>
                            <i class="b-partnership__list-item-num">2</i>
                        </li>
                        <li class="b-partnership__list-item">
                            После получения уведомления на указанный
                            при регистрации email можно начинать
                            работу
                            <i class="b-partnership__list-item-num">3</i>
                        </li>
                    </ul>
                </div>
                <div class="b-partnership__cell b-partnership__cell_right">
                    <p>
                        <strong> Вы хотите стать нашим партнёром</strong><br />
                        и пользоваться сервисом<br />для профессионалов aledo-pro:
                    </p>
                    <ul class="b-partnership__list list-unstyled">
                        <li class="b-partnership__list-item">
                            Заполните карту партнёра <strong><a ng-controller="PopupController" href="javascript:void(0)" ng-click="getPopup(ALEDO_POPUP_PARTNER_CARD)">здесь</a></strong>
                            <i class="b-partnership__list-item-num">1</i>
                        </li>
                        <li class="b-partnership__list-item">
                            Мы рассмотрим вашу заявку и свяжемся<br />
                            с вами для уточнения условий сотрудничества<br />
                            <small>
                                <i>
                                    (рассмотрение может занимать до 24 часов)
                                </i>
                            </small>
                            <i class="b-partnership__list-item-num">2</i>
                        </li>
                        <li class="b-partnership__list-item">
                            При положительном решении мы пришлём вам уведомление на email.
                            После этого можно сразу же приступать к работе с сервисом aledo-pro
                            <i class="b-partnership__list-item-num">3</i>
                        </li>
                    </ul>
                </div>
            </div>
            <p>Если у вас возникли вопросы по нашему сервису aledo-pro, <strong><a data-toggle="collapse" href="#feedback">напишите нам</a></strong></p>
            <div class="b-service-feedback collapse" id="feedback">
                <form name="serviceFeedback" novalidate ng-controller="FeedbackController" ng-submit="submit()">
                    <div>
                        <div class=" b-form-group b-form-group_inline">
                            <label for="service_feedback_fio">ФИО*</label>
                            <input type="text" class="b-form-control b-form-control_small" id="service_feedback_fio" ng-model="fio" autocomplete="off" required />
                        </div>
                        <div class="b-form-group b-form-group_inline b-ml3">
                            <label for="service_feedback_email">E-mail*</label>

                            <input type="text" class="b-form-control b-form-control_small" id="service_feedback_email" ng-model="email" autocomplete="off" required />

                        </div>
                    </div>
                    <div class="b-form-group b-form-group_block">
                        <label for="service_feedback_text">
                            Текст сообщения
                        </label>
                        <textarea class="b-form-control b-form-control_small" ng-model="text" id="service_feedback_text" minlength="30" required></textarea>
                    </div>
                    <button class="b-button b-button_yellow-background b-button_small  b-button_gray-colored b-mb3 " ng-disabled="serviceFeedback.$invalid" id="service_feedback_button" type="submit">
                        <span class="b-button__text">
                            <strong>ОТПРАВИТЬ</strong>
                        </span>
                    </button>
                </form>
            </div>
        </div>
    </div>
    <hr class="dotted-separator" />
    <div class="b-section__content text-center">
        <br />
        <br />
        <h4>
            УДАЧИ В ПРОЕКТАХ!
            <img src="/Content/images/aledo-logo-small.svg" height="180" />
        </h4>
    </div>
</div>

