<?php
use \Catalog\Controller\AdminController;
$links = $this->links;
$forWhat = "LED-лент";
?>
<div class="section">
    <div class="row">
        <div class="col-xs-12">
            <h2>Блоки питания для <?=$forWhat?>:</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class=" dotted-bottom"></div>
        </div>
    </div>
    <div class="row">
        <? foreach ($links as $link) { ?>
            <div class="col-xs-2 ">
                <div class="row">
                    <div class="b-section__content-subsection-title col-xs-12" style="height: 50px">

                        <?= $link[1]->title ?>

                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12" style="padding-bottom: 10px">
                        <div class=" dotted-bottom"></div>
                    </div>
                </div>
            </div>
        <? } ?>
    </div>
</div>
