<?
/** @var \Catalog\Model\Section $section */
$section = $this->element;
$min = $this->min;
$hasBorder = $this->hasBorder;
$url = $this->url('catalog', array(
    'action' => 'section',
    'id' => $section->id
));
?>

<a href="<?= $url ?>">
    <div class="tile-title-series" style="padding-left: 0"><?= $section->title ?></div>
    <? $src = $section->url ? $this->basePath() . '/images/sections/' . $section->url : $this->basePath() . '/images/empty-series.png' ?>
    <div class="row">
        <? if ($min) { ?>
        <div class="col-md-12 <?= $hasBorder ? 'bordered-link-element' : '' ?>">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
        <? } else { ?>
        <div class="col-md-12">
        <? } ?>
            <img src="<?= $src ?>" alt="<?= $section->title ?>"/>

            <? if ($min) { ?>
                </div>
            </div>
            <? } ?>
        </div>
    </div>
</a>
