<h1>Коммерческие предложения</h1>

<h2>Список КП</h2>
<div id="entityMapper_catalog">
    <div ng-controller="EntitiesCtrl">
        <div nd-entities-list-data>
            <?= $commercialsJson ?>
        </div>
        <div nd-entities-list-pattern>
            {
                "title" : {
                    "type" : "text",
                    "default" : "",
                    "label" : "Название"
                },
                "datetime" : {
                    "type" : "hidden",
                    "default" : "now",
                    "label" : "Дата создания"
                }
            }
        </div>
        <div
            ng-entities-list
            parent-type="0"
            parent-id="0"
            controller="commercials"
            type="<?= \Catalog\Controller\AdminController::COMMERCIALS_TABLE?>"
            rights="00111"
            ></div>

        <script type="application/javascript">
            AppFactory("entityMapper_catalog", "entityMapper2", ["entitiesMapper"]);
        </script>
    </div>
</div>
<!---->
<!--<div class="section">-->
<!--    <h3>Список отчётов</h3>-->
<!---->
<!--    <table class="table admin-table table-striped">-->
<!--        <tr>-->
<!--            <th>Id</th>-->
<!--            <th>Название</th>-->
<!--            <th>Управление</th>-->
<!--        </tr>-->
<!--        <tbody id="sortable">-->
<!--        --><?// foreach($entities as $entity){ ?>
<!--            <tr class="entity">-->
<!--                <td>--><?//= $entity->id; ?><!--</td>-->
<!--                <td>--><?//= $entity->name; ?><!--</td>-->
<!--                <td>-->
<!--                    <a href="#" class="editBtn">Редактировать</a>-->
<!--                    <a href="#" class="deleteBtn">Удалить</a>-->
<!--                </td>-->
<!--            </tr>-->
<!--        --><?// } ?>
<!--        </tbody>-->
<!--    </table>-->
<!--</div>-->

<script type="text/javascript">
    $(document).ready(function(){
        catalog.baseUrl = '<?= $this->url('zfcadmin/commercials') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/commercials', array('action'=> 'view')) ?>';
        catalog.init();
    });
</script>