<h1>
    <a href="<?= $this->url('zfcadmin/commercials') ?>">Отчёты</a>
    >
    <? /** @var \Reports\Model\Report $entity */ ?>
    <span id="title"><?= $entity->name; ?></span>
</h1>

<h2>Каталоги</h2>

<div class="section">
    <div class="row">
        <div class="col-md-12">
            <a href="/admin/commercials/exportFile/<?= $entity->id ?>/" target="_blank">
            <button type="button" class="btn btn-default" id="exportCommercial">Экспорт XLS</button>
            </a>
        </div>
    </div>
</div>

<div class="section">
    <h3>Основная информация</h3>
    <div id="entityMapper">
        <div ng-controller="EntityCtrl">

            <div
                ng-entity
                entity-id="<?= $entity->id ?>"
                entity-type="<?= \Catalog\Controller\AdminController::COMMERCIALS_TABLE?>"
                >

                <div ng-entity-data>
                    <?= $commercialJson ?>
                </div>
                <div ng-entity-schema>
                    [
                        {
                            "title" : "title",
                            "type" : "text",
                            "default" : "",
                            "label" : "Название"
                        }
                    ]
                </div>

                <table class="table admin-table table-striped">
                    <tbody>
                    <tr ng-repeat="description in schema">
                        <td>{{description.label}}</td>
                        <td>
                            <div ng-if="description.type == 'text'">
                                <div ng-text-field></div>
                            </div>
                            <div ng-if="description.type == 'image'">
                                <div ng-controller="ImageCtrl">
                                    <div
                                        ng-single-image-upload
                                        parent-type="commercial"
                                        folder="commercials"
                                        field="img"
                                        ></div>
                                </div>
                            </div>
                            <div ng-if="description.type == 'file'">
                                <div>
                                    <div
                                        ng-single-file-upload
                                        parent-type="commercial"
                                        folder="commercials"
                                        field="file"
                                        ></div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>


            </div>

            <script type="application/javascript">
                AppFactory("entityMapper", "entityMapper2", ["entityMapper", "imageMapper", "fileMapper"]);
            </script>
        </div>
    </div>
</div>

<h2>Помещения в КП</h2>
<div id="entityMapper_catalog">
    <div ng-controller="EntitiesCtrl">
        <div nd-entities-list-data>
            <?= $roomsJson ?>
        </div>
        <div nd-entities-list-pattern>
            {
                "title" : {
                    "type" : "text",
                    "default" : "",
                    "label" : "Название"
                },
                "commercial_id" : {
                    "type" : "hidden",
                    "default" : "<?= $entity->id ?>",
                    "label" : "Айди КП"
                }
            }
        </div>
        <div
            ng-entities-list
            parent-type="0"
            parent-id="0"
            controller="commercials"
            action="viewRoom"
            type="<?= \Catalog\Controller\AdminController::COMMERCIAL_ROOMS_TABLE?>"
            rights="00111"
            ></div>

        <script type="application/javascript">
            AppFactory("entityMapper_catalog", "entityMapper2", ["entitiesMapper"]);
        </script>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= $entity->id ?>';
        catalog.type = 'prmember';
        catalog.baseUrl = '<?= $this->url('zfcadmin/commercials') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/commercials', array('action'=> 'view')) ?>';
        catalog.init();
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.editablesSave,
            config: 'config-info'
        });

//        $('#exportCommercial').on('click', function() {
//            $.get('/admin/commercials/exportFile/<?//= $entity->id ?>///');
//        })
    });


</script>