<h1>
    <a href="<?= $this->url('zfcadmin/reports') ?>">Отчёты</a>
    >
    <? /** @var \Reports\Model\Report $entity */ ?>
    <span id="title"><?= $entity->name; ?></span>
</h1>

<div class="section">
    <h3>Основная информация</h3>
    <table class="table admin-table ">
        <tbody>
        <tr>
            <td>Название</td>
            <td>
                <a href="#" data-type="text" data-name="name" class="editable-param"><?= $entity->name; ?></a>
            </td>
        </tr>
        <tr>
            <td>Тип отчёта</td>
            <td>
                <?= $type; ?>
            </td>
        </tr>
        <tr>
            <td>Текст отчёта</td>
            <td>
                <a href="#" data-type="textarea" data-name="text" class="editable-param"><?= $entity->text; ?></a>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<div class="section">
    <h3>Элементы в отчёте</h3>

    <table class="table  admin-table table-striped">
        <tr>
            <th>Id</th>
            <th>Id элемента</th>
            <th>Название</th>
            <th>Управление</th>
        </tr>
        <tbody>
        <? foreach($entity->items as $item){ ?>
            <tr>
                <td><?= $item->id; ?></td>
                <td><?= $item->linked_id; ?></td>
                <td><?= $item->title; ?></td>
                <td>
                    <a href="<?= $item->url; ?>"><div class="btn btn-default">Перейти</div></a>
                    <a href="#" class="deleteBtn">Удалить</a>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>


<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= $entity->id ?>';
        catalog.type = 'prmember';
        catalog.baseUrl = '<?= $this->url('zfcadmin/reports') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/reports', array('action'=> 'view')) ?>';
        catalog.page_info_type = "report_item";
        catalog.init();
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.editablesSave,
            config: 'config-info'
        });
    });


</script>