<h1>
    <a href="<?= $this->url('zfcadmin/banner') ?>">Баннер</a>
    >
    <span id="title"><?= $entity->title; ?></span>
</h1>

<div class="section">
    <h3>Основная информация</h3>
    <table class="table admin-table ">
        <tbody>
        <tr>
            <td>Название</td>
            <td>
                <a href="#" data-type="text" data-name="title" class="editable-param"><?= $entity->title; ?></a>
            </td>
        </tr>
        <tr>
            <td>Текст надписи</td>
            <td>
                <a href="#" data-type="text" data-name="text" class="editable-param"><?= $entity->text; ?></a>
            </td>
        </tr>
        <tr>
            <td>Ссылка</td>
            <td>
                <a href="#" data-type="text" data-name="link" class="editable-param"><?= $entity->link; ?></a>
            </td>
        </tr>
		<tr>
            <td>Поведение ссылки</td>
            <td>
               <? $targets = array('1' => 'Открыть в новом окне', '2' => 'Открыть в текущем окне'); ?>
				<a href="#" data-type="select" data-name="target"
					data-source='<?= \Zend\Json\Json::encode($targets); ?>'
					data-value='<?= $entity->target; ?>' class="editable-param">
						<?= $targets[$entity->target]; ?>
				</a>
            </td>
        </tr>
        <tr>
            <td>Расположение</td>
            <td>
                <a href="#" data-value="<?= $this->position ?>" data-source="{'0': 'Слева', '1':'По центру', '2': 'Справа'}" data-type="select" data-name="position" class="editable-param"><?= \Application\Service\ApplicationService::getBannerPositionName($entity->position); ?></a>
            </td>
        </tr>
        <tr>
            <td>Изображение</td>
            <td>
                <div class="admin-banner-img-container" <?= $entity->img ? '' : 'style="display:none"' ?>>
                    <img style="height: 100%" src="<?= $entity->img ? $this->basePath() . '/images/banner/' . $entity->img : ''?>" alt=""/>
                </div>

                <button type="button" class="btn btn-default" id="add-img"> <?= $entity->img ? 'Редактировать' : 'Добавить' ?> изображение</button>

                <div class="form-inline" id="adding-form-img" style="display: none">
                    <form id="img-form" method="post" enctype="multipart/form-data">
                        <p>
                            <input type="file" name="image"/>
                            <input type="hidden" name="id" value="<?= $entity->id ?>"/>
                        </p>

                        <p>
                            <input type="submit" class="btn btn-default"/>
                            <button type="button" class="btn btn-default" id="adding-cancel-img">Отмена</button>
                        </p>
                    </form>
                </div>
            </td>
        </tr>

        </tbody>
    </table>
</div>

<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= $entity->id ?>';
        catalog.baseUrl = '<?= $this->url('zfcadmin/banner') ?>';
        catalog.initEditables();

        imgUploader.init({
            type: 'single',
            imgUrl: '<?= $this->basePath() . '/images/banner/' ?>'
        });
    });
</script>