
<div class="b-main">
    <? $banner = reset($this->bannerImages) ?>
    <div class="b-main-banner">
        <a href="<?= $banner->link ?>">
            <img class="b-main-banner__image"
                 image-responsive="{
                             default : {
                                 src:'/images/banner/<?= $banner->img ?>'
                             },
                             768 : {
                                 src: '/images/banner/<?= $banner->img ?>',
                             },
                             992 : {
                                 src: '/images/banner/<?= $banner->img ?>',
                             }
                 }"/>
        </a>
    </div>
    <? if (isset($this->blocks[0])) { ?>
    <div class="b-section b-main-grid b-clearfix">
        <div class="col-xs-12 col-md-7 b-main-grid-item "
             image-responsive="{
                             default : {
             src: '/images/blockimages/<?= $this->blocks[0]->images[0]->imgName ?>',
                                 css : {
                                'background-position':'50% 50%',
                                 'background-repeat': 'no-repeat',
                                 'background-size': 'cover'

                                }
                             },
              1400 : {
              src: '/images/blockimages/<?= $this->blocks[0]->images[0]->imgName ?>',
                  css : {
             'background-position':'50% 50%',
                                 'background-repeat': 'no-repeat',
                                 'background-size': 'cover'


             }
                 }
             }">
            <a class="b-main-grid-item__link" href="<?= $this->blocks[0]->images[0]->link ?>">

                <div class="b-button b-button_main">
                    <span class="b-button__text"><?= $this->blocks[0]->images[0]->title ?></span>
                    <i class="b-button__icon"></i>
                </div>
            </a>
        </div>
        <? } ?>
        <? if (isset($this->blocks[1])) { ?>
        <div class=" col-xs-6 col-md-5 b-main-grid-item"
             image-responsive="{
                             default : {
             src: '/images/blockimages/<?= $this->blocks[1]->images[0]->imgName ?>',
                                 css : {
                                'background-position':'50% 50%',
                                 'background-repeat': 'no-repeat',
                                 'background-size': 'cover'
                                }
                             },
              1400 : {
              src: '/images/blockimages/<?= $this->blocks[1]->images[0]->imgName ?>',
                  css : {
             'background-position':'50% 50%',
                                 'background-repeat': 'no-repeat',
                                 'background-size': 'cover'

             }
                 }
             }">
            <a class="b-main-grid-item__link" href="<?= $this->blocks[1]->images[0]->link ?>">

                <div class="b-button b-button_main">
                    <span class="b-button__text"><?= $this->blocks[1]->images[0]->title ?></span>
                    <i class="b-button__icon"></i>
                </div>
            </a>
        </div>
        <? } ?>
        <? if (isset($this->blocks[2])) { ?>
        <div class="col-xs-6 col-md-4 b-main-grid-item"
             image-responsive="{
                             default : {
             src: '/images/blockimages/<?= $this->blocks[2]->images[0]->imgName ?>',
                                 css : {
                                'background-position':'50% 50%',
                                 'background-repeat': 'no-repeat',
                                 'background-size': 'cover'
                                }
                             },
              1400 : {
              src: '/images/blockimages/<?= $this->blocks[2]->images[0]->imgName ?>',
                  css : {
             'background-position':'50% 50%',
                                 'background-repeat': 'no-repeat',
                                 'background-size': 'cover'

             }
                 }
             }">
            <a class="b-main-grid-item__link" href="<?= $this->blocks[2]->images[0]->link ?>">

                <div class="b-button b-button_main">
                    <span class="b-button__text"><?= $this->blocks[2]->images[0]->title ?></span>
                    <i class="b-button__icon"></i>
                </div>
            </a>
        </div>
        <? } ?>
        <? if (isset($this->blocks[3])) { ?>
        <div class="col-xs-7  col-md-4 b-main-grid-item"
             image-responsive="{
                             default : {
             src: '/images/blockimages/<?= $this->blocks[3]->images[0]->imgName ?>',
                                 css : {
                                'background-position':'50% 50%',
                                 'background-repeat': 'no-repeat',
                                 'background-size': 'cover'
                                }
                             },
              1400 : {
              src: '/images/blockimages/<?= $this->blocks[3]->images[0]->imgName ?>',
                  css : {
             'background-position':'50% 50%',
                                 'background-repeat': 'no-repeat',
                                 'background-size': 'cover'

             }
                 }
             }">
            <a class="b-main-grid-item__link" href="<?= $this->blocks[3]->images[0]->link ?>">

                <div class="b-button b-button_main">
                    <span class="b-button__text"><?= $this->blocks[3]->images[0]->title ?></span>
                    <i class="b-button__icon"></i>
                </div>
            </a>
        </div>
        <? } ?>
        <? if (isset($this->blocks[4])) { ?>
        <div class="col-xs-5 col-md-4 b-main-grid-item"
             image-responsive="{
                             default : {
             src: '/images/blockimages/<?= $this->blocks[4]->images[0]->imgName ?>',
                                 css : {
                                'background-position':'50% 50%',
                                 'background-repeat': 'no-repeat',
                                 'background-size': 'cover',
                                }
                             }, 1400 : {
              src: '/images/blockimages/<?= $this->blocks[4]->images[0]->imgName ?>',
                  css : {
             'background-position':'50% 50%',
                                 'background-repeat': 'no-repeat',
                                 'background-size': 'cover'

             }
                 }}">
            <a class="b-main-grid-item__link" href="<?= $this->blocks[4]->images[0]->link ?>">

                <div class="b-button b-button_main">
                    <span class="b-button__text"><?= $this->blocks[4]->images[0]->title ?></span>
                    <i class="b-button__icon"></i>
                </div>
            </a>
        </div>
        <? } ?>
    </div>
</div>

<script src="http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU" type="text/javascript"></script>