<div class="b-main">
    <? $banner = reset($this->bannerImages) ?>
    <div class="b-main-banner b-slider_banners">
        <? foreach ($this->bannerImages as $banner) { ?>
        <a href="<?= $banner->link ?>">
            <div class="b-slider__item b-slider_banners__item">
                <i class="b-slider-item-layout"></i>

                    <img class="b-main-banner__image"
                         src="/images/banner/<?= $banner->img ?>" alt="<?= $banner->title ?>" />

            </div>
        </a>
        <? } ?>

    </div>

    <script type="text/javascript">
        $('.b-slider_banners__item').width($(window).width());

        window.onresize = function(event) {
            $('.b-slider_banners__item').width($(window).width());
        };

        (function () {
            var $this = jQuery('.b-slider_banners');
            $this.slick({
                dots: false,
                infinite: true,
                draggable: browser.mobile ? true : false,
                speed: browser.mobile ? 300 : 700,
                touchThreshold: browser.mobile ? 5 : 50,
                slidesToShow: 1,
                centerMode: true,
                autoplay: true,
                autoplaySpeed: 4000,
                variableWidth: true,
                arrows: browser.mobile ? false : true,
                prevArrow: "<a class=\"left carousel-control\" href=\"javascript:void(0)\"><div class=\"aledo-banner-chevron left\"></div></a>",
                nextArrow: "<a class=\"right carousel-control\" href=\"javascript:void(0)\"><div class=\"aledo-banner-chevron right\"></div></a>"
//                nextArrow: "<a href=\"javascript:void(0)\" class=\"b-simple-arrow  b-simple-arrow_next b-slider_banners__arrow b-slider_blog__arrow_next\">" +
//                "</a>"
            });
        })();
    </script>
    <div class="b-section b-our-services b-main__section">

        <h2 class="b-main__section-heading">Наши услуги</h2>

        <div class="b-services-table-wrapper">
            <div class="b-services-table">
                <div class="b-services-table__cell">
                    Проектирование систем  <br/> LED-освещения
                </div>
                <div class="b-services-table__cell">
                    Проектирование систем  <br/> управления светом
                </div>
                <div class="b-services-table__cell">
                    Профессиональный монтаж <br/> LED-освещения
                </div>
                <div class="b-services-table__cell">
                    Производство LED-светильников <br/>по Вашим эскизам
                </div>
            </div>
        </div>
    </div>
    <div class="b-section b-our-clients b-main__section">
        <div class="b-section__content">
            <h2 class="b-main__section-heading">Наши клиенты</h2>

            <hr class="dotted-separator dotted-separator_clients-slider"/>
            <div class="b-slider b-slider_clients">
                <? foreach ($this->clients as $client) { ?>
                    <div class="b-slider__item b-slider_clients__item">
                        <i class="b-slider-item-layout"></i>
                        <img src="/images/clients/<?= $client->img ?>" alt="<?= $client->title ?>" class="b-slider_clients__image"/>
                    </div>
                <? } ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        (function () {
            var $this = jQuery('.b-slider_clients');
            $this.slick({
                dots: false,
                infinite: true,
                draggable: browser.mobile ? true : false,
                speed: browser.mobile ? 300 : 500,
                touchThreshold: browser.mobile ? 5 : 50,
                slidesToShow: 3,
                
                variableWidth: true,
                arrows: browser.mobile ? false : true,
                prevArrow: "<a href=\"javascript:void(0)\" class=\"b-simple-arrow  b-simple-arrow_prev b-slider_clients__arrow b-slider_blog__arrow_prev\">" +
                "</a>",
                nextArrow: "<a href=\"javascript:void(0)\" class=\"b-simple-arrow  b-simple-arrow_next b-slider_clients__arrow b-slider_blog__arrow_next\">" +
                "</a>"
            });


        })();
    </script>
    <div class="b-section b-our-projects b-main__section">
        <div class="b-section__content">
            <h1 class="b-main__section-heading">Наши проекты</h1>

            <hr class="dotted-separator dotted-separator_projects-slider"/>
            <div class="b-slider b-slider_projects">
                <? foreach($this->projects as $i=>$project){ ?>

                        <div class="b-slider__item b-slider_projects__item">
                        <a href="/projects/view/<?= $project->id ?>">
                            <i class="b-slider-item-layout"></i>
                            <img src="/images/projects/<?= $project->img ?>" alt="<?= $project->title ?>" class="b-slider_projects__image"/>
                            <span class="b-slider_projects__title"><?= $project->title ?></span>
                        </a>
                        </div>

                <? } ?>
            </div>
            <script type="text/javascript">
                (function () {
                    var $this = jQuery('.b-slider_projects');
                    $this.slick({
                        dots: false,
                        infinite: true,
                        draggable: browser.mobile ? true : false,
                        speed: browser.mobile ? 300 : 500,
                        touchThreshold: browser.mobile ? 5 : 50,
                        slidesToShow: 1,
                        centerMode: true,
                        variableWidth: true,
                        arrows: browser.mobile ? false : true,
                        prevArrow: "<a href=\"javascript:void(0)\" class=\"b-simple-arrow  b-simple-arrow_prev b-slider_blog__arrow b-slider_blog__arrow_prev\">" +
                        "</a>",
                        nextArrow: "<a href=\"javascript:void(0)\" class=\"b-simple-arrow  b-simple-arrow_next b-slider_blog__arrow b-slider_blog__arrow_next\">" +
                        "</a>"
                    });


                })();
            </script>
        </div>
    </div>

<!--    <div class="b-section b-our-blog b-main__section">-->
<!--        <div class="b-section__content">-->
<!--            <h2 class="b-main__section-heading">Наш блог</h2>-->
<!---->
<!--            <hr class="dotted-separator dotted-separator_blog-slider"/>-->
<!--            <div class="b-slider-outer">-->
<!--                <div class="b-slider b-slider_blog">-->
<!---->
<!--                    <div class="b-slider__item b-slider_blog__item">-->
<!--                        <i class="b-slider-item-layout"></i>-->
<!--                        <img src="/images/projects/img_54f0631d9bde9.jpg" class="b-slider_blog__image"/>-->
<!--                        <span class="b-slider_blog__title">Коэффициент светопередачи: <br/> важнее, чем раньше</span>-->
<!--                    </div>-->
<!--                    <div class="b-slider__item b-slider_blog__item">-->
<!--                        <i class="b-slider-item-layout"></i>-->
<!--                        <img src="/images/projects/img_549bfca923686.jpg" class="b-slider_blog__image"/>-->
<!--                        <span class="b-slider_blog__title">Освещение витрин</span>-->
<!--                    </div>-->
<!--                    <div class="b-slider__item b-slider_blog__item">-->
<!--                        <i class="b-slider-item-layout"></i>-->
<!--                        <img src="/images/projects/img_549c01f942a3e.jpg" class="b-slider_blog__image"/>-->
<!--                        <span class="b-slider_blog__title">Коэффициент светопередачи: <br/> важнее, чем раньше</span>-->
<!--                    </div>-->
<!--                    <div class="b-slider__item b-slider_blog__item">-->
<!--                        <i class="b-slider-item-layout"></i>-->
<!--                        <img src="/images/projects/img_549c17480b756.jpg" class="b-slider_blog__image"/>-->
<!--                        <span class="b-slider_blog__title">Освещение витрин</span>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--            <script type="text/javascript">-->
<!--                (function () {-->
<!--                    var $this = jQuery('.b-slider_blog');-->
<!--                    $this.slick({-->
<!--                        dots: false,-->
<!--                        infinite: true,-->
<!--                        draggable: browser.mobile ? true : false,-->
<!--                        speed: browser.mobile ? 300 : 500,-->
<!--                        touchThreshold: browser.mobile ? 5 : 50,-->
<!--                        slidesToShow: 1,-->
<!--                        centerMode: true,-->
<!--                        variableWidth: true,-->
<!--                        arrows: browser.mobile ? false : true,-->
<!--                        prevArrow: "<a href=\"javascript:void(0)\" class=\"b-simple-arrow  b-simple-arrow_prev b-slider_blog__arrow b-slider_blog__arrow_prev\">" +-->
<!--                        "</a>",-->
<!--                        nextArrow: "<a href=\"javascript:void(0)\" class=\" b-simple-arrow  b-simple-arrow_next b-slider_blog__arrow b-slider_blog__arrow_next\">" +-->
<!--                        "</a>"-->
<!--                    });-->
<!---->
<!---->
<!--                })();-->
<!--            </script>-->
<!--        </div>-->
<!--    </div>-->
</div>

