<?php
$i = $this->i;
/** @var Catalog\Model\Section $section */
$section = $this->section;

if (isset($this->subsections[$section->id])) {
    ?>
    <div class="row row-second">
        <? foreach($this->subsections[$section->id] as $i => $subsec){
            if(($i+1)%5==0){ echo'</div><div class="row row-second">'; }
            ?>
            <div class="col-xs-3 mobile-left-margin-2">
                <?=
                $this->partial(
                    "catalog/catalog/part/catalog-index-part/part/subsec-tile.phtml",
                    array(
                        'subsec' => $subsec,
                        'showPic' => true,
                    )
                );
                ?>
            </div>
        <? } ?>
    </div>
<? } ?>
