<div class=" about-company">
    <div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="section-title">
            <h2 class="about-title ">Почему вообще мы решили связаться со светодиодами?</h2>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="dotted-top"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 about-text">
                Просто, на сегодняшний день это наиболее современные осветительные устройства,
                а&nbsp;мы любим, когда вокруг светло, технологично и&nbsp;экологично.
                Светодиодное освещение превосходит аналоги по&nbsp;целому ряду параметров на&nbsp;годы, а&nbsp;может
                и&nbsp;десятилетия вперед. Судите сами:
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <div class="dotted-top"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 about-text">
                        Во-первых, экономичность — светодиоды намного выгоднее традиционных источников света,
                        что&nbsp;позволяет значительно сократить расходы на&nbsp;электроэнергию.
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="bottom-bold-grey-line"></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10 about-image" style="margin-left: -22%">
                        <img src="/images/info/info-1.jpg" alt="Экологичность" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="dotted-top"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 about-text">
                        В-третьих, экологичность — светодиодная лампа не&nbsp;содержит ртути и&nbsp;не&nbsp;требует специальной утилизации.
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-12">
                        <div class="bottom-bold-grey-line"></div>
                    </div>
                </div>

            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-4 about-image">
                        <img src="/images/info/info-2.png" alt="Долговечность" />
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="dotted-top"></div>
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-12 about-text">
                        Во-вторых, долговечность — срок службы светового прибора на&nbsp;базе светодиодов составляет
                        от&nbsp;25&nbsp;до&nbsp;40&nbsp;тысяч часов (в&nbsp;зависимости от&nbsp;типа и&nbsp;конструкции прибора),
                        что в&nbsp;несколько раз выше, чем у&nbsp;галогеновых ламп и&nbsp;в&nbsp;несколько десятков раз выше,
                        чем у&nbsp;традиционных источников света.
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-12">
                        <div class="bottom-bold-grey-line"></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8 about-image">
                        <img src="/images/info/info-3.jpg" alt="Качество освещения" />
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="dotted-top"></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 about-text">
                        Наконец, в-четвёртых, качество освещения — светодиоды освещают помещение на&nbsp;порядок лучше,
                        чем аналоги, а&nbsp;правильный свет способствует увеличению продаж
                        (особенно в&nbsp;сфере розничной торговли).
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-12">
                        <div class="bottom-bold-grey-line"></div>
                    </div>
                </div>
            </div>

        </div>

        <div class="row" style="padding-top: 30px">
            <div class="col-md-12">
                <div class="dotted-top"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 col-md-offset-5" >
                <div class="about-talk-left-arrow dialog-center" style="margin: -3px auto"></div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-2 about-text-yellow">
                Всё это в&nbsp;комплексе ведёт к&nbsp;увеличению рентабельности бизнеса и&nbsp;повышению эффективности работы компании.
            </div>
        </div>


        <div class="row">
            <div class="col-md-12">
                <div class="bottom-bold-grey-line"></div>
            </div>
        </div>

        <div class="row" style="padding-top: 30px">
            <div class="col-md-12">
                <div class="row">

                    <div class="col-md-8 about-talk-left">
                        <div class="row">
                            <div class="col-md-12">
                        — Да мало ли кто занимается светодиодами, вы что — особенные?
                            </div>
                        </div>

                    </div>

                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="about-talk-left-arrow dialog-left"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-4 about-talk-right-bold">
                        — М-м-м-м, дайте-ка подумать. Пожалуй, что да. Особенные.
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-1 col-md-offset-11">
                        <div class="about-talk-left-arrow dialog-right-bold"></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8 col-md-offset-4 about-subtitle">
                        <h2>
                            Доказательство географическое
                        </h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-4 about-talk-right">
                        работаем по всем регионам России, не забываем про СНГ, держим в уме страны ближнего зарубежья,
                        готовы, при необходимости расти и развиваться дальше.
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-1 col-md-offset-11">
                        <div class="about-talk-left-arrow dialog-right"></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8 col-md-offset-4 about-subtitle">
                        <h2>
                             Доказательство технологичное
                        </h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-4 about-talk-right">
                        освещение для бизнес-центров, автосалонов и кинотеатров, точек продаж, гостиничного или
                        ресторанного бизнеса, жилых домов и других объектов — в нашем каталоге продукции представлен
                        впечатляющий ассортимент профессиональных ламп и светильников для решения широкого спектра задач.
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-1 col-md-offset-11">
                        <div class="about-talk-left-arrow dialog-right"></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8 col-md-offset-4 about-subtitle">
                        <h2>
                           Доказательство экономическое
                        </h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-4 about-talk-right">
                        напрямую работаем с лучшими производителями светодиодного оборудования, благодаря чему
                        способны предлагать своим партнёрам и клиентам весьма приятные цены и интересные условия сотрудничества.
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-1 col-md-offset-11">
                        <div class="about-talk-left-arrow dialog-right"></div>
                    </div>
                </div>

                <div class="row" style="padding-bottom: 40px">
                    <div class="col-md-8 col-md-offset-4">
                    <div class="row">
                    <div class="bottom-bold-grey-line"></div>
                    </div>
                    <div class="row about-title">
                        <div class="col-md-12 about-title">
                        Aledo — правильный подход к светодиодному освещению, нерушимые принципы, дружелюбное отношение к клиентам
                        </div>
                    </div>

                        <div class="row">
                            <div class="bottom-bold-grey-line"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    </div>
</div>