<h1>
    <a href="<?= $this->url('zfcadmin/catalog') ?>">Каталог</a>
    >
    <a href="<?= $this->url('zfcadmin/catalog', array('action'=> 'section', 'id'=>$section->id));?>"><?= $section->title; ?></a>
    >
    <span id="title"><?= $subsection->title; ?></span>
</h1>

<div class="section">
    <h3>Основная информация</h3>
    <table class="table  admin-table table-striped">
        <tbody>
        <tr>
            <td>Название</td>
            <td>
                <a href="#" data-type="text" data-name="title" class="editable-param">
                    <?= $subsection->title; ?>
                </a>
            </td>
        </tr>
        <tr>
            <td>Изображение</td>
            <td>
                <div class="admin-banner-img-container" <?= $subsection->url ? '' : 'style="display:none"' ?>>
                    <div class="admin-img-del">
                        <button class="btn btn-xs btn-default"><i class="glyphicon glyphicon-remove"></i></button>
                    </div>
                    <img style="height: 100%" src="<?= $subsection->url ? $this->basePath() . '/images/subsections/' . $subsection->url : ''?>" alt=""/>
                </div>

                <button type="button" class="btn btn-default" id="add-img"> <?= $subsection->url ? 'Редактировать' : 'Добавить' ?> изображение</button>
                <button type="button" class="btn btn-default" id="del-img"> Удалить изображение</button>

                <div class="form-inline" id="adding-form-img" style="display: none">
                    <form action="" id="img-form" method="post" enctype="multipart/form-data">
                        <p>
                            <input type="file" name="image"/>
                            <input type="hidden" name="id" value="<?= $subsection->id ?>"/>
                            <input type="hidden" name="type" value="subsection"/>
                        </p>

                        <p>
                            <input type="submit" class="btn btn-default"/>
                            <button type="button" class="btn btn-default" id="adding-cancel-img">Отмена</button>
                        </p>
                    </form>
                </div>
            </td>
        </tr>
        <tr>
            <td>URL</td>
            <td>
                <a href="#" data-type="text" data-name="display_name" class="editable-param">
                    <?= $subsection->display_name; ?>
                </a>
            </td>
        </tr>
        <tr>
            <td>Видео</td>
            <td>
                <a href="#" data-type="text" data-name="video" class="editable-param">
                    <?= $subsection->video; ?>
                </a>
            </td>
        </tr>
        <tr>
            <td>Сео-заголовок</td>
            <td class="col-md-8">
                <div class="editor-get-btn"  data-name="seo_title">
                    <?= $subsection->seo_title; ?>
                </div>
            </td>
        </tr>
        <tr>
            <td>Сео-текст</td>
            <td class="col-md-8">
                <div class="editor-get-btn" data-name="seo_text">
                    <?= $subsection->seo_text; ?>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<div class="section">
    <h3>Список серий</h3>
    <div class="addPanel">
        <button type="button" class="btn btn-default" id="add-entity">Создать новую серию</button>

        <div class="form-inline" id="adding-form" style="display: none">
            <div class="form-group">
                <label class="sr-only" for="inputName">Название серии</label>
                <input type="text" class="form-control" id="inputName" placeholder="Введите название..."/>
            </div>

            <button type="button" class="btn btn-default" id="adding-complete">Добавить</button>
            <button type="button" class="btn btn-default" id="adding-cancel">Отмена</button>
        </div>
    </div>

    <div class="addPanel">
        <button type="button" class="btn btn-default" id="tagit-add">Добавить существующую серию</button>

        <div id="tagit-form" style="display: none">
            <ul id="tagit-series" ></ul>
            <input type="hidden" id="tagit-series-res" name="seriesIds"/>

            <button type="button" class="btn btn-default" id="tagit-save">Добавить</button>
            <button type="button" class="btn btn-default" id="tagit-cancel">Отмена</button>
        </div>
    </div>

    <table class="table admin-table  table-striped">
        <tr>
            <th>Id</th>
            <th>Название</th>
            <th>Управление</th>
        </tr>
        <tbody id="sortable">
        <? foreach($series as $ser){ ?>
            <tr class="entity" <?= $ser->deleted ? 'style="color: #BBB"' : '' ?>>
                <td><?= $ser->id; ?></td>
                <td><?= $ser->visible_title; ?></td>
                <td>
                    <a href="#" class="editBtn">Редактировать</a>
                    <a href="#" class="removeBtn">Открепить</a>
                    <a href="#" class="showBtn" <?= $ser->deleted ? '' : 'style="display: none"' ?>>Показать</a>
                    <a href="#" class="hideBtn" <?= $ser->deleted ? 'style="display: none"' : '' ?>>Скрыть</a>
                    <!--                    <a href="#" class="deleteBtn">Удалить</a>-->
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>


<div class="section">
    <h3>Связи</h3>
    <div class="row" style="margin-bottom: 20px">
        <div class="col-md-3">
            <label for="linkType">Тип элемента</label>
            <select name="linkType" class="form-control" onchange="catalog.getTagsByType($(this).val())">
                <option value="<?=\Catalog\Controller\AdminController::PRODUCT_TABLE ?>">Продукт</option>
                <option value="<?=\Catalog\Controller\AdminController::SERIES_TABLE ?>">Серия</option>
                <option value="<?=\Catalog\Controller\AdminController::SUBSECTION_TABLE ?>">Подраздел</option>
                <option value="<?=\Catalog\Controller\AdminController::SECTION_TABLE ?>" selected>Раздел</option>
                <option value="<?=\Catalog\Controller\AdminController::SOLUTION_TABLE ?>">Решение</option>
                <option value="<?=\Catalog\Controller\AdminController::PROJECT_TABLE ?>">Проект</option>
            </select>
        </div>
    </div>
    <div class="addPanel">
        <button type="button" class="btn btn-default" id="linktagit-add">Добавить существующий элемент</button>

        <div id="linktagit-form" style="display: none">
            <ul id="tagit-links" ></ul>
            <input type="hidden" id="tagit-links-res" name="linksIds"/>

            <button type="button" class="btn btn-default" id="linktagit-save">Добавить</button>
            <button type="button" class="btn btn-default" id="linktagit-cancel">Отмена</button>
        </div>
    </div>
    <table class="table admin-table  table-striped">
        <tr>
            <th>Id</th>
            <th>Тип</th>
            <th>Название</th>
            <th>Управление</th>
        </tr>
        <tbody id="sortable3">

        <? /** @var $links array */
        foreach($links as $link){ ?>
            <tr class="entity" data-linktype="<?= $link[0] ?>">
                <td><?= $link[1]->id ?></td>
                <td><?= $link[3] ?></td>
                <td><?= $link[1]->title ?></td>
                <td>
                    <a href="#" class="removeLinkBtn">Открепить</a>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>


<div class="section" ng-app="dflTree">
    <div ng-controller="DflTreeCtrl">
        <h3>Фильтры</h3>
        <dfl-tree section-id="<?= $subsection->id ?>" section-type="2">
            <div class="row" ng-show="isPersonalFilter(2)">
                <div class="col-md-12 alert alert-warning">
                    Для этого раздела установлены отдельные фильтры.<br>
                    <span ng-click="clearAll(23, 1)" style="color: #666666; cursor: pointer">Вернуть фильтры по умолчанию</span>
                </div>
            </div>
        <div class="row">
        <div class="col-md-6">

                <div dfl-tree-data ng-cloak><?= $treeDataByLvlJson ?></div>

                <div dfl-tree-hierarchy ng-cloak>[]</div>
                <div ng-init="list = items[23];"></div>
                <style>
                    #sortable2 { list-style-type: none; margin: 0; padding: 0; max-width: 500px; }

                </style>
                <ul id="sortable2">
                    <li ng-repeat="(key, item) in items[23]" data-id="{{item.id}}">
                        <div class="row tree-row">
                            <div class="col-md-9" ng-click="item.shown = !item.shown" ng-bind="item.title"></div>
                            <div class="col-md-1" style="text-align: right;">
                                <span
                                    class="glyphicon glyphicon-folder-open"
                                    ng-show="item.open == 1"
                                    ng-click="changeField('<?= \Catalog\Controller\AdminController::FILTER_FIELD_TABLE ?>', item.id, 'open', 0, {sectionId:<?= $subsection->id?>, sectionType:2}, 'filterCallback')"></span>
                                <span
                                    class="glyphicon glyphicon-folder-close"
                                    ng-show="item.open == 0"
                                    ng-click="changeField('<?= \Catalog\Controller\AdminController::FILTER_FIELD_TABLE ?>', item.id, 'open', 1, {sectionId:<?= $subsection->id?>, sectionType:2}, 'filterCallback')"></span>
                            </div>
                            <div class="col-md-1" style="text-align: right;">
                                <span
                                    class="glyphicon glyphicon-eye-open"
                                    ng-show="item.hidden == 0"
                                    style="color: #B5BD26"
                                    ng-click="changeField('<?= \Catalog\Controller\AdminController::FILTER_FIELD_TABLE ?>', item.id, 'hidden', 1, {sectionId:<?= $subsection->id?>, sectionType:2}, 'filterCallback')"></span>
                                <span
                                    class="glyphicon glyphicon-eye-close"
                                    style="color: #BBBBBB"
                                    ng-show="item.hidden > 0"
                                    ng-click="changeField('<?= \Catalog\Controller\AdminController::FILTER_FIELD_TABLE ?>', item.id, 'hidden', 0, {sectionId:<?= $subsection->id?>, sectionType:2}, 'filterCallback')"></span>
                            </div>
                            <div class="col-md-1" style="text-align: right;0">
                                <span
                                    class="glyphicon kp-icon"
                                    ng-show="item.cart_param == 0"
                                    style="color: #BBBBBB"
                                    ng-click="changeField('<?= \Catalog\Controller\AdminController::FILTER_FIELD_TABLE ?>', item.id, 'cart_param', 1, {sectionId:<?= $subsection->id?>, sectionType: 2}, 'filterCallback')">КП</span>
                                <span
                                    class="glyphicon kp-icon"
                                    style="color: #c09853"
                                    ng-show="item.cart_param == 1"
                                    ng-click="changeField('<?= \Catalog\Controller\AdminController::FILTER_FIELD_TABLE ?>', item.id, 'cart_param', 0, {sectionId:<?= $subsection->id?>, sectionType: 2}, 'filterCallback')">КП</span>
                            </div>
                        </div>
                    </li>
                </ul>


        </div>
        </div>
        </dfl-tree>
        <script type="application/javascript">
            AppFactory("dflTree", "trees", ["dflTree"]);
        </script>
    </div>
</div>

<?
$sl = $this->getHelperPluginManager()->getServiceLocator();
echo \Info\Service\SeoService::renderSeoForm($sl, $seoData);
?>

<script type="text/javascript">
    $(function(){
        catalog.type = '<?= \Catalog\Controller\AdminController::SERIES_TABLE ?>';
        catalog.parentType = '<?= \Catalog\Controller\AdminController::SUBSECTION_TABLE ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService:: CATALOG_SUBSECTION ?>';
        catalog.parentId = '<?= $subsection->id ?>';
        catalog.link_type_1 = '<?= \Catalog\Controller\AdminController::SUBSECTION_TABLE ?>';
        catalog.baseUrl = '<?= $this->url('zfcadmin/catalog') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/catalog', array('action'=> 'series')) ?>';
        catalog.init();
        catalog.initEditables();

        imgUploader.init({
            type: 'single',
            delFunction: imgUploader.entityImgDel,
            imgUrl: '<?= $this->basePath() . '/images/subsections/' ?>'
        });

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.editablesSave
        });

        tagit.init({
            tags: <?= $tags; ?>,
            inputField: $("#tagit-series"),
            outputField: $('#tagit-series-res'),
            placeholder: 'Введите название или ID серии'
        });

        catalog.getTagsByType(<?= \Catalog\Controller\AdminController::SECTION_TABLE ?>);
    });
</script>