<h1>Партнёрский раздел</h1>


<div class="section" id="userTable">

    <solo-table make-sortable="3" items-on-page="20">
        <h3>Список партнёров</h3>
        <div class="addPanel">
            <button type="button" class="btn btn-default" id="tagit-add">Добавить партнёра</button>

            <div id="tagit-form" style="display: none">
                <ul id="tagit-users" ></ul>
                <input type="hidden" id="tagit-users-res" name="usersIds"/>

                <button type="button" class="btn btn-default" id="tagit-save">Добавить</button>
                <button type="button" class="btn btn-default" id="tagit-cancel">Отмена</button>
            </div>
        </div>

        <div solo-table-data ng-cloak>
            <?= $usersJson ?>
        </div>

        <span ng-show="false" ng-init="getSelectFor(['city', 'group_name', 'manager_name'])"></span>


        <div class="row">
            <div class="col-md-12" style="text-align: right">
                <div class="btn btn-default" ng-click="sendNotifyToFiltered()">Уведомить всех о скидках</div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="text-align: right; margin-bottom: 20px">
                <!-- Постраничная навигация -->
                <ul class="pagination pagination-sm" ng-show="pageNums.length > 1">
                    <li ng-class="{active: $index == pager.currentPage - 1}" ng-model="pageNums" ng-repeat="i in pageNums track by $index" ><a href="#"  ng-click="gotoPage($index+1)">{{$index+1}}</a> </li>
                </ul>
            </div>
        </div>

        <table class="table admin-table table-striped">
            <thead>
            <tr>
                <th sort-by='user_id'>Id</th>
                <th sort-by='username'>Имя</th>
                <th sort-by='email'>Почта</th>
                <th sort-by='alias'>Псевдоним</th>
                <th sort-by='group_name'>Группа</th>
                <th sort-by='city'>Город</th>
                <th sort-by='manager_name'>Менеджер</th>
                <th>Управление</th>
                <th></th>
            </tr>
            <tr class="filter-input-row">
                <th></th>
                <th><input type="text" class="form-control" ng-model="filterModelUsername" name="username" placeholder="Имя пользователя" /></th>
                <th><input type="text" class="form-control" ng-model="filterModelEmail" name="email" placeholder="Почта" /></th>
                <th><input type="text" class="form-control" ng-model="filterModelAlias" name="alias" placeholder="Псевдоним" /></th>
                <th>
                    <select ng-model="filterModelGroup" class="input form-control">
                        <option value="">Все</option>
                        <option ng-repeat="group in selects.group_name" ng-value="group">{{group}}</option>
                    </select>
                </th>
                <th>
                    <select ng-model="filterModelCity" class="input form-control">
                        <option value="">Все города</option>
                        <option ng-repeat="town in selects.city" ng-value="town">{{town}}</option>
                    </select>
                </th>
                <th>
                    <select ng-model="filterModelManager" class="input form-control">
                        <option value="">Все</option>
                        <option ng-repeat="manager in selects.manager_name" ng-value="manager">{{manager}}</option>
                    </select>
                </th>

                <th></th>
                <th></th>
            </tr>
            </thead>


            <tbody>
            <!--            --><?// foreach($entities as $entity){ ?>
            <tr class="entity" ng-repeat="item in filtered = (original | filterByFields:filterModelUsername:['username'] | filterByFields:filterModelEmail:['email'] | filterByFields:filterModelAlias:['alias'] | filterByFields:filterModelCity:['city'] | filterByFields:filterModelManager:['manager_name'] | filterByFields:filterModelGroup:['group_name'])">
                <td>{{item.user_id}}</td>
                <td>{{item.username}}</td>
                <td>{{item.email}}</td>
                <td>{{item.alias}}</td>
                <td>
                    <span ng-if="item.partner_group > 0">
                        <a ng-href="/admin/discounts/viewGroup/{{item.partner_group}}/">
                        {{item.group_name}}
                        </a>
                    </span>
                    <span ng-if="item.partner_group == 0">
                        {{item.group_name}}
                    </span>
                </td>
                <td>{{item.city}}</td>
                <td>{{item.manager_name}}</td>

                <td>
                    <a ng-href="/admin/discounts/partners/{{item.user_id}}/" class="editBtn">Редактировать</a>

                </td>
                <td>
                    <a href="#" class="removeBtn">Открепить</a>
                </td>
            </tr>
            </tbody>
        </table>

    </solo-table>
</div>
<script>
    AppFactory("userTable", "example1", ["solo.table"]);
</script>
<!---->
<!--<div class="section">-->
<!---->
<!---->
<!--    <table class="table admin-table  table-striped">-->
<!--        <tr>-->
<!--            <th>Id</th>-->
<!--            <th>Имя</th>-->
<!--            <th>Псевдоним</th>-->
<!--            <th>Группа</th>-->
<!--            <th>Город</th>-->
<!--            <th>Менеджер</th>-->
<!--            <th>Управление</th>-->
<!--        </tr>-->
<!--        <tbody id="sortable">-->
<!--        --><?// foreach($entities as $entity){ ?>
<!--            <tr class="entity">-->
<!--                <td>--><?//= $entity->user_id; ?><!--</td>-->
<!--                <td>--><?//= $entity->username; ?><!--</td>-->
<!--                <td>--><?//= $entity->alias; ?><!--</td>-->
<!--                <td>-->
<!--                    --><?// if ($entity->partner_group) { ?>
<!--                        <a href="/admin/discounts/viewGroup/--><?//= $entity->partner_group ?><!--">-->
<!--                            --><?//= $groupsNamesById[$entity->partner_group]; ?>
<!--                        </a>-->
<!--                    --><?// } ?>
<!--                </td>-->
<!--                <td>--><?//= $entity->city; ?><!--</td>-->
<!--                <td>--><?//= $managers[$entity->manager_id] ?><!--</td>-->
<!---->
<!--                <td>-->
<!--                    <a href="#" class="editBtn">Редактировать</a>-->
<!--                    <a href="#" class="removeBtn">Открепить</a>-->
<!--                </td>-->
<!--            </tr>-->
<!--        --><?// } ?>
<!--        </tbody>-->
<!--    </table>-->
<!---->
<!--</div>-->


<div class="section">
    <h3>Группы партнёров</h3>

    <div class="addPanel">
        <button type="button" class="btn btn-default" id="add-group">Добавить группу</button>

        <div class="form-inline" id="adding-form-group" style="display: none">
            <div class="form-group">
                <label class="sr-only" for="inputGroupName">Название продукта</label>
                <input type="text" class="form-control" id="inputGroupName" placeholder="Введите название..."/>
            </div>

            <button type="button" class="btn btn-default" id="adding-group-complete">Добавить</button>
            <button type="button" class="btn btn-default" id="adding-group-cancel">Отмена</button>
        </div>
    </div>

    <table class="table admin-table  table-striped">
        <tr>
            <th>Id</th>
            <th>Название</th>
            <th>Управление</th>
        </tr>
        <tbody id="group-container">
        <? foreach($partnerGroups as $pg){ ?>
            <tr class="entity-group">
                <td><?= $pg->id; ?></td>
                <td><?= $pg->name; ?></td>
                <td>
                    <a href="#" class="editGroupBtn">Редактировать</a>
                    <a href="#" class="deleteGroupBtn">Удалить</a>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>


<script type="text/javascript">
    $(document).ready(function(){
        catalog.type = '<?= \Catalog\Controller\AdminController::USERS_TABLE ?>';
        catalog.parentId = '<?= \Catalog\Controller\AdminController::USERS_TABLE ?>';
        catalog.baseUrl = '<?= $this->url('zfcadmin/discounts') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/discounts', array('action'=> 'partners')) ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INDEX ?>';
        catalog.init();
    });

    tagit.init({
        tags: <?= $tags; ?>,
        type: '<?= \Catalog\Controller\AdminController::USERS_TABLE ?>',
        inputField: $("#tagit-users"),
        outputField: $('#tagit-users-res'),
        placeholder: 'Введите имя пользователя'
    });

    partnerGroups.init();
</script>