<h1>
    <a href="<?= $this->url('zfcadmin/info') ?>">О компании</a>
    >
    <? /** @var \Info\Model\About $entity */ ?>
    <?= $entity->title ?>
</h1>

<table class="table admin-table ">
    <tbody>
    <tr>
        <td>Название</td>
        <td>
            <a href="#" data-type="text" data-name="title1" class="editable-param"><?= $entity->title1; ?></a>
        </td>
    </tr>
    <tr>
        <td>Левая вкладка</td>
        <td>
            <a href="#" data-type="text" data-name="btn_1_header" class="editable-param"><?= $entity->btn_1_header; ?></a>
        </td>
    </tr>
    <tr>
        <td>Правая вкладка</td>
        <td>
            <a href="#" data-type="text" data-name="btn_2_header" class="editable-param"><?= $entity->btn_2_header; ?></a>
        </td>
    </tr>
    <tr>
        <td>Левый текстовый блок</td>
        <td>
            <div class="editor-get-btn" data-wid="text_1" data-id="<?= \Info\Service\SeoService::ABOUT ?>">
                <?= $entity->text_1; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Правый текстовый блок. Заголовок 1</td>
        <td>
            <a href="#" data-type="text" data-name="text_2_header_1" class="editable-param"><?= $entity->text_2_header_1; ?></a>
        </td>
    </tr>
    <tr>
        <td>Правый текстовый блок. Текст 1</td>
        <td>
            <div class="editor-get-btn" data-wid="text_2_text_1" data-id="<?= \Info\Service\SeoService::ABOUT ?>">
                <?= $entity->text_2_text_1; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Правый текстовый блок. Заголовок 2</td>
        <td>
            <a href="#" data-type="text" data-name="text_2_header_2" class="editable-param"><?= $entity->text_2_header_2; ?></a>
        </td>
    </tr>
    <tr>
        <td>Правый текстовый блок. Текст 2</td>
        <td>
            <div class="editor-get-btn" data-wid="text_2_text_2" data-id="<?= \Info\Service\SeoService::ABOUT ?>">
                <?= $entity->text_2_text_2; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Правый текстовый блок. Заголовок 3</td>
        <td>
            <a href="#" data-type="text" data-name="text_2_header_3" class="editable-param"><?= $entity->text_2_header_3; ?></a>
        </td>
    </tr>
    <tr>
        <td>Правый текстовый блок. Текст 3</td>
        <td>
            <div class="editor-get-btn" data-wid="text_2_text_3" data-id="<?= \Info\Service\SeoService::ABOUT ?>">
                <?= $entity->text_2_text_3; ?>
            </div>
        </td>
    </tr>

    <tr>
        <td>Название</td>
        <td>
            <a href="#" data-type="text" data-name="title2" class="editable-param"><?= $entity->title2; ?></a>
        </td>
    </tr>

    <tr>
        <td>Наши принципы работы. Текст слева</td>
        <td>
            <div class="editor-get-btn" data-wid="block_2_text_1" data-id="<?= \Info\Service\SeoService::ABOUT ?>">
                <?= $entity->block_2_text_1; ?>
            </div>
        </td>
    </tr>
    <tr id="imageMapper1">
        <td>Наши принципы работы. Изображение слева</td>
        <td ng-controller="ImageCtrl">
            <div
                ng-single-image-upload
                parent-type="about"
                parent-id="<?= $entity->id ?>"
                folder="about"
                field="block_2_img_1"
                img="<?= $entity->block_2_img_1_name ? $entity->block_2_img_1_name : "" ?>"
                img-id ="<?= $entity->block_2_img_1 ? $entity->block_2_img_1 : "" ?>"
                ></div>

            <script type="application/javascript">
                AppFactory("imageMapper1", "images3", ["imageMapper", "ur.file"]);
            </script>
        </td>
    </tr>

    <tr>
        <td>Наши принципы работы. Текст по центру</td>
        <td>
            <div class="editor-get-btn" data-wid="block_2_text_2" data-id="<?= \Info\Service\SeoService::ABOUT ?>">
                <?= $entity->block_2_text_2; ?>
            </div>
        </td>
    </tr>
    <tr id="imageMapper2">
        <td>Наши принципы работы. Изображение по центру</td>
        <td ng-controller="ImageCtrl">
            <div
                ng-single-image-upload
                parent-type="about"
                parent-id="<?= $entity->id ?>"
                folder="about"
                field="block_2_img_2"
                img="<?= $entity->block_2_img_2_name ? $entity->block_2_img_2_name : "" ?>"
                img-id ="<?= $entity->block_2_img_2 ? $entity->block_2_img_2 : "" ?>"
                ></div>

            <script type="application/javascript">
                AppFactory("imageMapper2", "images3", ["imageMapper", "ur.file"]);
            </script>
        </td>
    </tr>

    <tr>
        <td>Наши принципы работы. Текст справа</td>
        <td>
            <div class="editor-get-btn" data-wid="block_2_text_3" data-id="<?= \Info\Service\SeoService::ABOUT ?>">
                <?= $entity->block_2_text_3; ?>
            </div>
        </td>
    </tr>
    <tr id="imageMapper3">
        <td>Наши принципы работы. Изображение по центру</td>
        <td ng-controller="ImageCtrl">
            <div
                ng-single-image-upload
                parent-type="about"
                parent-id="<?= $entity->id ?>"
                folder="about"
                field="block_2_img_3"
                img="<?= $entity->block_2_img_3_name ? $entity->block_2_img_3_name : "" ?>"
                img-id ="<?= $entity->block_2_img_3 ? $entity->block_2_img_3 : "" ?>"
                ></div>

            <script type="application/javascript">
                AppFactory("imageMapper3", "images3", ["imageMapper", "ur.file"]);
            </script>
        </td>
    </tr>

    <tr id="imageMapper4">
        <td>Фоновое изображение</td>
        <td ng-controller="ImageCtrl">
            <div
                ng-single-image-upload
                parent-type="about"
                parent-id="<?= $entity->id ?>"
                folder="about"
                field="img"
                img="<?= $entity->img_name ? $entity->img_name : "" ?>"
                img-id ="<?= $entity->img ? $entity->img : "" ?>"
                ></div>

            <script type="application/javascript">
                AppFactory("imageMapper4", "images3", ["imageMapper", "ur.file"]);
            </script>
        </td>
    </tr>

    <tr id="imageMapper5">
        <td>Фоновое изображение (для низкого разрешения)</td>
        <td ng-controller="ImageCtrl">
            <div
                ng-single-image-upload
                parent-type="about"
                parent-id="<?= $entity->id ?>"
                folder="about"
                field="img_min"
                img="<?= $entity->img_min_name ? $entity->img_min_name : "" ?>"
                img-id ="<?= $entity->img_min ? $entity->img_min : "" ?>"
                ></div>

            <script type="application/javascript">
                AppFactory("imageMapper5", "images3", ["imageMapper", "ur.file"]);
            </script>
        </td>
    </tr>
    </tbody>
</table>


<?
$sl = $this->getHelperPluginManager()->getServiceLocator();
echo \Info\Service\SeoService::renderSeoForm($sl, $seoData);
?>

<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= \Info\Service\SeoService::ABOUT ?>';
        catalog.type = 'prmember';
        catalog.baseUrl = '<?= $this->url('zfcadmin/info') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/info', array('action'=> 'viewMember')) ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INFO ?>';
        catalog.init();
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.infoSave,
            config: 'config-info'
        });
    });
</script>