<h1>
    <a href="<?= $this->url('zfcadmin/info') ?>">Информация</a>
    > Доставка и оплата
</h1>

<table class="table admin-table ">
    <tbody>
    <tr>
        <td>Название 1</td>
        <td>
            <a href="#" data-type="text" data-name="title1" class="editable-param"><?= $entity->title1; ?></a>
        </td>
    </tr>
    <tr>
        <td>Текст 1</td>
        <td>
            <div class="editor-get-btn" data-wid="text1" data-id="<?= \Info\Service\SeoService::DELIVERY ?>">
                <?= $entity->text1; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Название 2</td>
        <td>
            <a href="#" data-type="text" data-name="title2" class="editable-param"><?= $entity->title2; ?></a>
        </td>
    </tr>
    <tr>
        <td>Текст 2 (до реквизитов)</td>
        <td>
            <div class="editor-get-btn" data-wid="text2" data-id="<?= \Info\Service\SeoService::DELIVERY ?>">
                <?= $entity->text2; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Реквизиты</td>
        <td>
            <div class="editor-get-btn" data-wid="text2_details" data-id="<?= \Info\Service\SeoService::DELIVERY ?>">
                <?= $entity->text2_details; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Текст 2 (после реквизитов)</td>
        <td>
            <div class="editor-get-btn" data-wid="text2_part2" data-id="<?= \Info\Service\SeoService::DELIVERY ?>">
                <?= $entity->text2_part2; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Название 3</td>
        <td>
            <a href="#" data-type="text" data-name="title3" class="editable-param"><?= $entity->title3; ?></a>
        </td>
    </tr>
    <tr>
        <td>Текст 3</td>
        <td>
            <div class="editor-get-btn" data-wid="text3" data-id="<?= \Info\Service\SeoService::DELIVERY ?>">
                <?= $entity->text3; ?>
            </div>
        </td>
    </tr>

    </tbody>
</table>


<? if (!$isDomainZoneBy) {
$sl = $this->getHelperPluginManager()->getServiceLocator();
echo \Info\Service\SeoService::renderSeoForm($sl, $seoData);
} ?>

<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= \Info\Service\SeoService::DELIVERY ?>';
        catalog.type = 'prmember';
        catalog.baseUrl = '<?= $this->url('zfcadmin/info') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/info', array('action'=> 'viewMember')) ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INFO ?>';
        catalog.init();
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.infoSave,
            config: 'config-info'
        });
    });
</script>