<h1>
    <a href="<?= $this->url('zfcadmin/info') ?>">Информация</a>
    >
    <? /** @var \Info\Model\Files $entity */ ?>
    <?= $entity->title ?>
</h1>

<table class="table admin-table ">
    <tbody>
    <tr>
        <td>Название</td>
        <td>
            <a href="#" data-type="text" data-name="title1" class="editable-param"><?= $entity->title; ?></a>
        </td>
    </tr>
    <tr id="imageMapper1">
        <td>Каталоги. Фон</td>
        <td ng-controller="ImageCtrl">
            <div
                ng-single-image-upload
                parent-type="infoFiles"
                parent-id="<?= $entity->id ?>"
                folder="files"
                field="img_1"
                img="<?= $entity->img_1_name ? $entity->img_1_name : "" ?>"
                img-id ="<?= $entity->img_1 ? $entity->img_1 : "" ?>"
                ></div>

            <script type="application/javascript">
                AppFactory("imageMapper1", "images3", ["imageMapper", "ur.file"]);
            </script>
        </td>
    </tr>

    <tr id="imageMapper2">
        <td>Каталоги. Фон для мобильной версии</td>
        <td ng-controller="ImageCtrl">
            <div
                ng-single-image-upload
                parent-type="infoFiles"
                parent-id="<?= $entity->id ?>"
                folder="files"
                field="img_1_1000"
                img="<?= $entity->img_1_1000_name ? $entity->img_1_1000_name : "" ?>"
                img-id ="<?= $entity->img_1_1000 ? $entity->img_1_1000 : "" ?>"
                ></div>

            <script type="application/javascript">
                AppFactory("imageMapper2", "images3", ["imageMapper", "ur.file"]);
            </script>
        </td>
    </tr>
    <tr id="imageMapper3">
        <td>Сертификаты. Фон</td>
        <td ng-controller="ImageCtrl">
            <div
                ng-single-image-upload
                parent-type="infoFiles"
                parent-id="<?= $entity->id ?>"
                folder="files"
                field="img_2"
                img="<?= $entity->img_2_name ? $entity->img_2_name : "" ?>"
                img-id ="<?= $entity->img_2 ? $entity->img_2 : "" ?>"
                ></div>

            <script type="application/javascript">
                AppFactory("imageMapper3", "images3", ["imageMapper", "ur.file"]);
            </script>
        </td>
    </tr>

    <tr id="imageMapper4">
        <td>Сертификаты. Фон для мобильной версии</td>
        <td ng-controller="ImageCtrl">
            <div
                ng-single-image-upload
                parent-type="infoFiles"
                parent-id="<?= $entity->id ?>"
                folder="files"
                field="img_2_1000"
                img="<?= $entity->img_2_1000_name ? $entity->img_2_1000_name : "" ?>"
                img-id ="<?= $entity->img_2_1000 ? $entity->img_2_1000 : "" ?>"
                ></div>

            <script type="application/javascript">
                AppFactory("imageMapper4", "images3", ["imageMapper", "ur.file"]);
            </script>
        </td>
    </tr>

    </tbody>
</table>


<?
$sl = $this->getHelperPluginManager()->getServiceLocator();
echo \Info\Service\SeoService::renderSeoForm($sl, $seoData);
?>

<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= \Info\Service\SeoService::FILES ?>';
        catalog.type = 'prmember';
        catalog.baseUrl = '<?= $this->url('zfcadmin/info') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/info', array('action'=> 'viewMember')) ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INFO ?>';
        catalog.init();
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.infoSave,
            config: 'config-info'
        });
    });
</script>