<h1>
    <a href="<?= $this->url('zfcadmin/info') ?>">Сервис и гарантия</a>
    >
    <? /** @var \Info\Model\Pluses $entity */ ?>
    <?= $entity->title ?>
</h1>

<table class="table admin-table ">
    <tbody>
    <tr>
        <td>Название</td>
        <td>
            <a href="#" data-type="text" data-name="title" class="editable-param"><?= $entity->title; ?></a>
        </td>
    </tr>
    <tr>
        <td>Текст 1</td>
        <td>
            <div class="editor-get-btn" data-wid="text1" data-id="<?= \Info\Service\SeoService::GUARANTEE ?>">
                <?= $entity->text1; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Текст 2</td>
        <td>
            <div class="editor-get-btn" data-wid="text2" data-id="<?= \Info\Service\SeoService::GUARANTEE ?>">
                <?= $entity->text2; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Название 2</td>
        <td>
            <a href="#" data-type="text" data-name="title2" class="editable-param"><?= $entity->title2; ?></a>
        </td>
    </tr>
    <tr>
        <td>Текст 3</td>
        <td>
            <div class="editor-get-btn" data-wid="text3" data-id="<?= \Info\Service\SeoService::GUARANTEE ?>">
                <?= $entity->text3; ?>
            </div>
        </td>
    </tr>
    </tbody>
</table>


<?
$sl = $this->getHelperPluginManager()->getServiceLocator();
echo \Info\Service\SeoService::renderSeoForm($sl, $seoData);
?>

<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= \Info\Service\SeoService::GUARANTEE ?>';
        catalog.type = 'prmember';
        catalog.baseUrl = '<?= $this->url('zfcadmin/info') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/info', array('action'=> 'viewMember')) ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INFO ?>';
        catalog.init();
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.infoSave,
            config: 'config-info'
        });
    });
</script>