<h1>Информация</h1>

<div class="row">
	<a href="<?= $this->url('zfcadmin/info', array('action' => 'about')) ?>" class="admin-tile">О компании</a>
	<a href="<?= $this->url('zfcadmin/info', array('action' => 'guarantee')) ?>" class="admin-tile">Сервис и гарантия</a>
	<a href="<?= $this->url('zfcadmin/info', array('action' => 'partner')) ?>" class="admin-tile">Партнерам</a>
	<a href="<?= $this->url('zfcadmin/info', array('action' => 'service')) ?>" class="admin-tile">Наш сервис</a>
</div>
<div class="row" style="margin-top: 30px;">
	<a href="<?= $this->url('zfcadmin/info', array('action' => 'pluses')) ?>" class="admin-tile">Преимущества</a>
	<a href="<?= $this->url('zfcadmin/info', array('action' => 'delivery')) ?>" class="admin-tile">Доставка и оплата</a>
	<a href="<?= $this->url('zfcadmin/info', array('action' => 'files')) ?>" class="admin-tile">Скачать</a>
	<a href="<?= $this->url('zfcadmin/info', array('action' => 'job')) ?>" class="admin-tile">Работа у нас</a>
</div>