<? $isDomainZoneBy = \Application\Service\ApplicationService::isDomainZone('by'); ?>
<h1>Информация</h1>

<div class="row">
	<a href="<?= $this->url('zfcadmin/info', array('action' => 'about')) ?>" class="admin-tile">О компании</a>
	<? if (!$isDomainZoneBy) { ?><a href="<?= $this->url('zfcadmin/info', array('action' => 'guarantee')) ?>" class="admin-tile">Сервис и гарантия</a><? } ?>
	<? if (!$isDomainZoneBy) { ?><a href="<?= $this->url('zfcadmin/info', array('action' => 'partner')) ?>" class="admin-tile">Партнерам</a><? } ?>
	<? if (!$isDomainZoneBy) { ?><a href="<?= $this->url('zfcadmin/info', array('action' => 'service')) ?>" class="admin-tile">Наш сервис</a><? } ?>
<? if (!$isDomainZoneBy) { ?></div>
<div class="row" style="margin-top: 30px;"><? } ?>
	<? if (!$isDomainZoneBy) { ?><a href="<?= $this->url('zfcadmin/info', array('action' => 'pluses')) ?>" class="admin-tile">Преимущества</a><? } ?>
	<a href="<?= $this->url('zfcadmin/info', array('action' => 'delivery')) ?>" class="admin-tile">Доставка и оплата</a>
	<? if (!$isDomainZoneBy) { ?><a href="<?= $this->url('zfcadmin/info', array('action' => 'files')) ?>" class="admin-tile">Скачать</a><? } ?>
	<? if (!$isDomainZoneBy) { ?><a href="<?= $this->url('zfcadmin/info', array('action' => 'job')) ?>" class="admin-tile">Работа у нас</a><? } ?>
</div>