<h1>
    <a href="<?= $this->url('zfcadmin/info') ?>">Информация</a>
    > Партнерам
</h1>

<table class="table admin-table ">
    <tbody>
    <tr>
        <td>Заголовок</td>
        <td>
            <a href="#" data-type="text" data-name="title" class="editable-param"><?= $entity->title; ?></a>
        </td>
    </tr>
    <tr>
        <td>Заголовок 1</td>
        <td>
            <a href="#" data-type="text" data-name="title1" class="editable-param"><?= $entity->title1; ?></a>
        </td>
    </tr>
    <tr>
        <td>Текст 1</td>
        <td>
            <div class="editor-get-btn" data-wid="text1" data-id="<?= \Info\Service\SeoService::PARTNERS ?>">
                <?= $entity->text1; ?>
            </div>
        </td>
    </tr>
<!--    <tr id="imageMapper1">-->
<!--        <td>Фоновое изображение</td>-->
<!--        <td ng-controller="ImageCtrl">-->
<!--            <div-->
<!--                ng-single-image-upload-->
<!--                parent-type="partners"-->
<!--                parent-id="--><?//= $entity->id ?><!--"-->
<!--                folder="partners"-->
<!--                field="img1"-->
<!--                img="--><?//= $entity->img1_name ? $entity->img1_name : "" ?><!--"-->
<!--                img-id ="--><?//= $entity->img1 ? $entity->img1 : "" ?><!--"-->
<!--                ></div>-->
<!---->
<!--            <script type="application/javascript">-->
<!--                AppFactory("imageMapper1", "images3", ["imageMapper", "ur.file"]);-->
<!--            </script>-->
<!--        </td>-->
<!--    </tr>-->
<!---->
<!--    <tr id="imageMapper2">-->
<!--        <td>Фоновое изображение (для низкого разрешения)</td>-->
<!--        <td ng-controller="ImageCtrl">-->
<!--            <div-->
<!--                ng-single-image-upload-->
<!--                parent-type="partners"-->
<!--                parent-id="--><?//= $entity->id ?><!--"-->
<!--                folder="partners"-->
<!--                field="img1_min"-->
<!--                img="--><?//= $entity->img1_min_name ? $entity->img1_min_name : "" ?><!--"-->
<!--                img-id ="--><?//= $entity->img1_min ? $entity->img1_min : "" ?><!--"-->
<!--                ></div>-->
<!---->
<!--            <script type="application/javascript">-->
<!--                AppFactory("imageMapper2", "images3", ["imageMapper", "ur.file"]);-->
<!--            </script>-->
<!--        </td>-->
<!--    </tr>-->
    <tr>
        <td>Заголовок 2</td>
        <td>
            <a href="#" data-type="text" data-name="title2" class="editable-param"><?= $entity->title2; ?></a>
        </td>
    </tr>
    <tr>
        <td>Текст 2</td>
        <td>
            <div class="editor-get-btn" data-wid="text2" data-id="<?= \Info\Service\SeoService::PARTNERS ?>">
                <?= $entity->text2; ?>
            </div>
        </td>
    </tr>

<!---->
<!--    <tr id="imageMapper4">-->
<!--        <td>Фоновое изображение (для низкого разрешения)</td>-->
<!--        <td ng-controller="ImageCtrl">-->
<!--            <div-->
<!--                ng-single-image-upload-->
<!--                parent-type="partners"-->
<!--                parent-id="--><?//= $entity->id ?><!--"-->
<!--                folder="partners"-->
<!--                field="img2_min"-->
<!--                img="--><?//= $entity->img2_min_name ? $entity->img2_min_name : "" ?><!--"-->
<!--                img-id ="--><?//= $entity->img2_min ? $entity->img2_min : "" ?><!--"-->
<!--                ></div>-->
<!---->
<!--            <script type="application/javascript">-->
<!--                AppFactory("imageMapper4", "images3", ["imageMapper", "ur.file"]);-->
<!--            </script>-->
<!--        </td>-->
<!--    </tr>-->
    <tr>
        <td>Заголовок 3</td>
        <td>
            <a href="#" data-type="text" data-name="title3" class="editable-param"><?= $entity->title3; ?></a>
        </td>
    </tr>
    <tr>
        <td>Вкладка 1. Заголовок</td>
        <td>
            <a href="#" data-type="text" data-name="tab1_head" class="editable-param"><?= $entity->tab1_head; ?></a>
        </td>
    </tr>
    <tr>
        <td>Вкладка 1. Текст</td>
        <td>
            <div class="editor-get-btn" data-wid="tab1_body" data-id="<?= \Info\Service\SeoService::PARTNERS ?>">
                <?= $entity->tab1_body; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Вкладка 2. Заголовок</td>
        <td>
            <a href="#" data-type="text" data-name="tab2_head" class="editable-param"><?= $entity->tab2_head; ?></a>
        </td>
    </tr>
    <tr>
        <td>Вкладка 2. Текст</td>
        <td>
            <div class="editor-get-btn" data-wid="tab2_body" data-id="<?= \Info\Service\SeoService::PARTNERS ?>">
                <?= $entity->tab2_body; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Вкладка 3. Заголовок</td>
        <td>
            <a href="#" data-type="text" data-name="tab3_head" class="editable-param"><?= $entity->tab3_head; ?></a>
        </td>
    </tr>
    <tr>
        <td>Вкладка 3. Текст</td>
        <td>
            <div class="editor-get-btn" data-wid="tab3_body" data-id="<?= \Info\Service\SeoService::PARTNERS ?>">
                <?= $entity->tab3_body; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Вкладка 4. Заголовок</td>
        <td>
            <a href="#" data-type="text" data-name="tab4_head" class="editable-param"><?= $entity->tab4_head; ?></a>
        </td>
    </tr>
    <tr>
        <td>Вкладка 4. Текст</td>
        <td>
            <div class="editor-get-btn" data-wid="tab4_body" data-id="<?= \Info\Service\SeoService::PARTNERS ?>">
                <?= $entity->tab4_body; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Заголовок 4</td>
        <td>
            <a href="#" data-type="text" data-name="title4" class="editable-param"><?= $entity->title4; ?></a>
        </td>
    </tr>
    <tr>
        <td>Текст 4</td>
        <td>
            <div class="editor-get-btn" data-wid="text4" data-id="<?= \Info\Service\SeoService::PARTNERS ?>">
                <?= $entity->text4; ?>
            </div>
        </td>
    </tr>

    <tr>
        <td>Смотреть подробнее</td>
        <td>
            <a href="#" data-type="text" data-name="more" class="editable-param"><?= $entity->more; ?></a>
        </td>
    </tr>

    </tbody>
</table>


<?
$sl = $this->getHelperPluginManager()->getServiceLocator();
echo \Info\Service\SeoService::renderSeoForm($sl, $seoData);
?>

<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= \Info\Service\SeoService::PARTNERS ?>';
        catalog.type = 'prmember';
        catalog.baseUrl = '<?= $this->url('zfcadmin/info') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/info', array('action'=> 'viewMember')) ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INFO ?>';
        catalog.init();
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.infoSave,
            config: 'config-info'
        });
    });
</script>