<h1>
    <a href="<?= $this->url('zfcadmin/info') ?>">Информация</a>
    > Преимущества
</h1>

<table class="table admin-table ">
    <tbody>
    <tr>
        <td>Название</td>
        <td>
            <a href="#" data-type="text" data-name="title" class="editable-param"><?= $entity->title; ?></a>
        </td>
    </tr>
    <tr>
        <td>Преимущество 1. Заголовок</td>
        <td>
            <a href="#" data-type="text" data-name="title1" class="editable-param"><?= $entity->title1; ?></a>
        </td>
    </tr>
    <tr>
        <td>Преимущество 1. Текст</td>
        <td>
            <div class="editor-get-btn" data-wid="text1" data-id="<?= \Info\Service\SeoService::PLUSES ?>">
                <?= $entity->text1; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Преимущество 2. Заголовок</td>
        <td>
            <a href="#" data-type="text" data-name="title2" class="editable-param"><?= $entity->title2; ?></a>
        </td>
    </tr>
    <tr>
        <td>Преимущество 2. Текст</td>
        <td>
            <div class="editor-get-btn" data-wid="text2" data-id="<?= \Info\Service\SeoService::PLUSES ?>">
                <?= $entity->text2; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Преимущество 3. Заголовок</td>
        <td>
            <a href="#" data-type="text" data-name="title3" class="editable-param"><?= $entity->title3; ?></a>
        </td>
    </tr>
    <tr>
        <td>Преимущество 3. Текст</td>
        <td>
            <div class="editor-get-btn" data-wid="text3" data-id="<?= \Info\Service\SeoService::PLUSES ?>">
                <?= $entity->text3; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Преимущество 4. Заголовок</td>
        <td>
            <a href="#" data-type="text" data-name="title4" class="editable-param"><?= $entity->title4; ?></a>
        </td>
    </tr>
    <tr>
        <td>Преимущество 4. Текст</td>
        <td>
            <div class="editor-get-btn" data-wid="text4" data-id="<?= \Info\Service\SeoService::PLUSES ?>">
                <?= $entity->text4; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>Преимущество 5. Заголовок</td>
        <td>
            <a href="#" data-type="text" data-name="title5" class="editable-param"><?= $entity->title5; ?></a>
        </td>
    </tr>
    <tr>
        <td>Преимущество 5. Текст</td>
        <td>
            <div class="editor-get-btn" data-wid="text5" data-id="<?= \Info\Service\SeoService::PLUSES ?>">
                <?= $entity->text5; ?>
            </div>
        </td>
    </tr>


    <tr id="imageMapper4">
        <td>Фоновое изображение</td>
        <td ng-controller="ImageCtrl">
            <div
                ng-single-image-upload
                parent-type="pluses"
                parent-id="<?= $entity->id ?>"
                folder="pluses"
                field="img"
                img="<?= $entity->img_name ? $entity->img_name : "" ?>"
                img-id ="<?= $entity->img ? $entity->img : "" ?>"
                ></div>

            <script type="application/javascript">
                AppFactory("imageMapper4", "images3", ["imageMapper", "ur.file"]);
            </script>
        </td>
    </tr>

    </tbody>
</table>


<?
$sl = $this->getHelperPluginManager()->getServiceLocator();
echo \Info\Service\SeoService::renderSeoForm($sl, $seoData);
?>

<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= \Info\Service\SeoService::PLUSES ?>';
        catalog.type = 'prmember';
        catalog.baseUrl = '<?= $this->url('zfcadmin/info') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/info', array('action'=> 'viewMember')) ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INFO ?>';
        catalog.init();
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.infoSave,
            config: 'config-info'
        });
    });
</script>