<?
/**
 * @var \Articles\Model\Article $article
 * @var \Catalog\Model\Series[] $relatedSeries
 * @var $sl
 * @var \Articles\Model\Article $prevProd
 * @var \Articles\Model\Article $nextProd
 */
?>
<div class="b-section b-article">

    <div class="b-section__content">
        <? if ($article->title) { ?>
            <h2 class="b-article__heading"><?= $article->title ?></h2>
        <? } ?>
            <hr class="dotted-separator b-article__separator"/>
        <? if ($article->img) { ?>
            <img src="/images/articles/<?= $article->img ?>"/>
        <? } ?>
        <? if ($article->text) { ?>
            <?= $article->text ?>
        <? } ?>

        <? foreach ($article->blocks as $block) { ?>
            <? if (!$block->title && !$block->text && !$block->img_name) continue; ?>
                <hr class="dotted-separator b-article__separator"/>
            <? if ($block->title) { ?>
                <h2 class="b-article__heading"><?= $block->title ?></h2>
            <? } ?>
            <? if ($block->text) { ?>
                <?= $block->text ?>
            <? } ?>
            <? if ($block->img_name) { ?>
                <img src="/images/articles/<?= $block->img_name ?>"/>
            <? } ?>
        <? } ?>

    </div>
</div>

<script>
    popup.pageTitle = '<?= $this->seoData->title ? $this->seoData->title : $news->title ?>';

</script>