<?
/**
 * @var \Articles\Model\Article $article
 * @var \Catalog\Model\Series[] $relatedSeries
 * @var $sl
 * @var \Articles\Model\Article $prevProd
 * @var \Articles\Model\Article $nextProd
 */
?>
<div class="b-section__content">
    <div class="b-breadcrumbs">
        <a class="b-breadcrumbs__item" href="/">Главная</a>&nbsp;/
        <a class="b-breadcrumbs__item" href="/blog/">Блог</a>&nbsp;/

        <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $article->title ?></strong>
    </div>
</div>
<div class="b-section b-article">

    <div class="b-section__content">
	    <? if ($article->header1 || $article->header2) { ?>
            <h2 class="b-article__heading"><?= $article->header1 ? $article->header1 : '' ?><?= $article->header2 ? '<br>'.$article->header2 : '' ?></h2>
        <? } ?>
        <? if ($article->title && !$article->header1 && !$article->header2) { ?>
            <h2 class="b-article__heading"><?= $article->title ?></h2>
        <? } ?>
            <hr class="dotted-separator b-article__separator"/>
        <? if ($article->img) { ?>
            <img src="/images/articles/<?= $article->img ?>" class="pinit-image"<?= $article->video ? ' style="display: none !important;"' : '' ?>/>
        <? } ?>
		<? if ($article->video) { ?>
			<iframe width="560" height="315" ng-iframe src="<?= $article->video ?>" frameborder="0" allowfullscreen></iframe>
		<? } ?>
        <? if ($article->text) { ?>
            <?= $article->text ?>
        <? } ?>

        <? foreach ($article->blocks as $block) { ?>
            <? if (!$block->title && !$block->text && !$block->img_name) continue; ?>
                <hr class="dotted-separator b-article__separator"/>
            <? if ($block->title) { ?>
                <h2 class="b-article__heading"><?= $block->title ?></h2>
            <? } ?>
            <? if ($block->text) { ?>
                <?= $block->text ?>
            <? } ?>
			<div style="white-space: nowrap;">
            <? if ($block->img_name) { ?>
                <img src="/images/articles/<?= $block->img_name ?>" class="pinit-image"<?= ($article->id==6 && $block->order==1) ? ' style="display: inline; width: 50%; height: auto;"' : '' ?>/>
            <? } ?>
			<? if ($block->img2_name) { ?>
                <img src="/images/articles/<?= $block->img2_name ?>" class="pinit-image"<?= ($article->id==6 && $block->order==1) ? ' style="display: inline; width: 50%; height: auto;"' : '' ?>/>
            <? } ?>
			<? if ($block->video) { ?>
				<iframe width="560" height="315" ng-iframe src="<?= $block->video ?>" frameborder="0" allowfullscreen></iframe>
			<? } ?>
			</div>
            <? if ($block->textafter) { ?>
                <?= $block->textafter ?>
            <? } ?>
        <? } ?>
		
		<hr class="dotted-separator b-article__separator">
		<center>
			<script type="text/javascript">
				function getShareWindow(url) {
					var width = 554;
					var height = 349;
					var left = (screen.width - width) / 2;
					var top = (screen.height - height) / 2;
					var popupParams = 'scrollbars=0, resizable=1, menubar=0, left=' + left + ', top=' + top + ', width=' + width + ', height=' + height + ', toolbar=0, status=0';
					window.open(url, 'shareWindow', popupParams);
				}
			</script>
			
			<a class="b-blog-social-link-nav" href="#" onclick="getShareWindow('http://www.facebook.com/share.php?u='+ window.location +'&title=' + document.title);return false;">
                <img src="/Content/images/social/blog_f_.svg"/>
                <img src="/Content/images/social/blog_f_hover.svg" />
            </a>
			
			<script type="text/javascript" src="http://vk.com/js/api/share.js?92" charset="windows-1251"></script>
			<script type="text/javascript">
				document.write(VK.Share.button(false, {type: 'custom', text: '<div class="b-blog-social-link-nav"><img src="/Content/images/social/blog_vk_.svg""/><img src="/Content/images/social/blog_vk_hover.svg" /></div>'}));
			</script>
			
			<a class="b-blog-social-link-nav" href="#" onclick="getShareWindow('http://www.linkedin.com/shareArticle?mini=true&url='+ window.location +'&title=' + document.title + '&source=Aledo');return false;">
                <img src="/Content/images/social/blog_L_in.svg"/>
                <img src="/Content/images/social/blog_L_in_hover.svg" />
            </a>
			<a class="b-blog-social-link-nav" href="#" onclick="getShareWindow('http://pinterest.com/pin/create/button/?media=http://aledo-pro.ru' + $('.pinit-image:first').attr('src') + '&url='+ window.location +'&description=' + document.title);return false;">
                <img src="/Content/images/social/blog_pin.svg"/>
                <img src="/Content/images/social/blog_pin_hover.svg" />
            </a>
        </center>

    </div>
</div>

<script>
    popup.pageTitle = '<?= $this->seoData->title ? $this->seoData->title : $news->title ?>';

</script>