<?
use \User\Service\UserService;
/**
 * @var $actions array()
 * @var $daysCount
 * @var $weekFirstDayNum
 * @var $today
 * @var $userId
 * @var $year
 * @var $month
 */

?>
<h1>Календарь</h1>
<div class="row">
    <div class="col-md-12">
        <h2>
            <a style="color: #AAAAAA" href="/admin/user/calendar/<?=$userId?>/?year=<?= $year-1 ?>&month=<?= $month ?>">
                <?= $year-1 ?>
            </a>
            &nbsp;[&nbsp;<?= $year ?>&nbsp;]&nbsp;
            <a style="color: #AAAAAA" href="/admin/user/calendar/<?=$userId?>/?year=<?= $year+1 ?>&month=<?= $month ?>">
                <?= $year+1 ?>
            </a>
        </h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2>
            <a style="color: #AAAAAA" href="/admin/user/calendar/<?=$userId?>/?year=<?= $year ?>&month=<?= $month == 1 ? 12 : $month-1 ?>">
                <?= UserService::monthName($month == 1 ? 12 : $month-1) ?>
            </a>
            &nbsp;[&nbsp;<?= UserService::monthName($month) ?>&nbsp;]&nbsp;
            <a style="color: #AAAAAA" href="/admin/user/calendar/<?=$userId?>/?year=<?= $year ?>&month=<?= $month == 12 ? 1 : $month+1 ?>">
                <?= UserService::monthName($month == 12 ? 1 : $month+1) ?>
            </a>
        </h2>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table width="100%" class="table-bordered">
            <thead>
                <tr class="">
                    <th class="calendar-day-name">Пн</th>
                    <th class="calendar-day-name">Вт</th>
                    <th class="calendar-day-name">Ср</th>
                    <th class="calendar-day-name">Чт</th>
                    <th class="calendar-day-name">Пт</th>
                    <th class="calendar-day-name">Сб</th>
                    <th class="calendar-day-name">Вс</th>
                </tr>
            </thead>
            <tbody>
            <? $num = 0; ?>
            <? for ($i = 0; $i < 6; $i++) { ?>
                <? if ($num > $daysCount) continue; ?>
                <tr class="calendar-week">
                    <? for ($j = 1; $j <= 7; $j++) { ?>
                        <? $num = $i*7 + $j - $weekFirstDayNum + 1; ?>
                        <? if (($i == 0 && $j < $weekFirstDayNum) || $num > $daysCount) { ?>
                            <td class="calendar-day disabled">
                                <h2></h2>
                            </td>
                        <? } else { ?>
                            <? if ($today !== false && $num == $today) { ?>
                                <td class="calendar-day active" style="">
                                    <a href="/admin/user/history/<?= $userId ?>?year=<?= $year ? $year : '0' ?>&month=<?= $month ? $month : '0' ?>&day=<?= $num ?>">
                                    <h2><?= $num ?></h2>
                                    <div class="row">
                                        <div class="col-md-12">

                                                <? if (count($actions[$num]) > 0) { ?>
                                                    <span><?= count($actions[$num]) ?> <?= UserService::_d(count($actions[$num]), 'действий') ?></span>
                                                <? } else { ?>
                                                    <span>Нет активностей</span>
                                                <? } ?>
                                        </div>
                                    </div>
                                    </a>
                                </td>

                            <? } else { ?>
                                <td class="calendar-day">
                                    <a href="/admin/user/history/<?= $userId ?>?year=<?= $year ? $year : '0' ?>&month=<?= $month ? $month : '0' ?>&day=<?= $num ?>">
                                    <h2><?= $num ?></h2>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <? if ($num <= $today || $today === false) { ?>
                                                <? if (count($actions[$num]) > 0) { ?>
                                                    <span><?= count($actions[$num]) ?> <?= UserService::_d(count($actions[$num]), 'действий') ?></span>
                                                <? } else { ?>
                                                    <span>—</span>
                                                <? } ?>

                                            <? } else {?>
                                            <span>&nbsp;</span>
                                            <? } ?>
                                        </div>
                                    </div>

                                    </a>
                                </td>
                            <? } ?>
                        <? } ?>
                    <? } ?>
                </tr>
            <? } ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

</script>