<?
use \User\Service\UserService;
/**
 * @var $history \User\Model\UserHistory[]
 */

?>
<h1>История активности</h1>
<div class="row">
    <div class="col-md-12">
        <form name="historyForm" action="/admin/user/history/<?= $userId ?>/" method="post">
            <div class="col-md-3">
                <label for="period">Период:</label>
                <select name="period" class="form-control">
                    <option value="0" <?= $this->period ? "" : 'selected = "selected"' ?>>За всё время</option>
                    <option
                        <?= $this->period == UserService::USER_HISTORY_HOUR ? 'selected = "selected"' : '' ?>
                        value="<?= UserService::USER_HISTORY_HOUR ?>">Час</option>
                    <option
                        <?= $this->period == UserService::USER_HISTORY_DAY ? 'selected = "selected"' : '' ?>
                        value="<?= UserService::USER_HISTORY_DAY ?>">День</option>
                    <option
                        <?= $this->period == UserService::USER_HISTORY_WEEK ? 'selected = "selected"' : '' ?>
                        value="<?= UserService::USER_HISTORY_WEEK ?>">Неделя</option>
                    <option
                        <?= $this->period == UserService::USER_HISTORY_MONTH_30 ? 'selected = "selected"' : '' ?>
                        value="<?= UserService::USER_HISTORY_MONTH_30 ?>">Месяц</option>
                    <option
                        <?= $this->period == UserService::USER_HISTORY_YEAR ? 'selected = "selected"' : '' ?>
                        value="<?= UserService::USER_HISTORY_YEAR ?>">Год</option>

                </select>
            </div>

            <div class="col-md-3">
                <label for="period">Тип действия:</label>
                <select name="type" class="form-control">
                    <option
                        <?= !$this->type ? 'selected = "selected"' : '' ?>
                        value="0">Всё действия</option>
                    <? foreach (UserService::$actionTypes as $actionType => $actionDescription) { ?>
                        <option
                            <?= $this->type == $actionType ? 'selected = "selected"' : '' ?>
                            value="<?= $actionType ?>"><?= $actionDescription ?></option>
                    <? } ?>
                </select>
            </div>
            <div class="col-md-3">
                <label>&nbsp;</label>
                <input type="submit" class="btn btn-default form-control" value="Обновить" />
            </div>
            <div class="col-md-3">
                <label>&nbsp;</label>
                <a href="/admin/user/calendar/<?= $userId ?>/"> <div class="btn btn-default form-control">Календарь</div></a>
            </div>
        </form>
    </div>
</div>
<div class="section">
    <table class="table admin-table table-striped">
        <tr>
            <th>Время</th>
            <th>Действие</th>
            <th>Ссылка</th>
            <th></th>
        </tr>
        <tbody id="sortable">
        <? foreach($history as $key => $action){ ?>
            <tr class="entity">
                <td><?= date("Y-m-d H:i:s", $action->timer); ?></td>
                <td><?= UserService::$actionTypes[$action->actionType]; ?></td>
                <td>
                    <? if ($action->url) { ?>
                        <? $url = UserService::formatHistoryUrl($action->url); ?>
                        <a href="<?= $url ?>" target="_blank">
                            <?= UserService::$urlDescription[$action->actionType] ?>
                        </a>
                    <? } ?>
                </td>
                <td><?= $action->to_user_id ?></td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">

</script>