<?= $this->doctype(); ?>

<html lang="ru">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle($this->translate('aledo'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>

    <!-- Le styles -->
    <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/Content/css/admin.css')

        ->prependStylesheet($this->basePath() . '/Content/css/libs/jquery-ui.min.css')
        ->prependStylesheet($this->basePath() . '/Content/css/libs/jquery.tagit.css')
        ->prependStylesheet($this->basePath() . '/Content/css/libs/bootstrap-editable.css')
        ->prependStylesheet($this->basePath() . '/Content/css/libs/bootstrap.css')
        ->prependStylesheet($this->basePath() . '/Content/css/libs/ng-tags-input.css')
        ->prependStylesheet($this->basePath() . '/Content/css/libs/ng-tags-input.bootstrap.css')
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath() . '/js/libs/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/libs/admin.js')
//        ->prependFile($this->basePath() . '/js/libs/angular-1.1.5.js')
        ->prependFile($this->basePath() . '/Scripts/angular.js')
//        ->appendFile($this->basePath() . '/js/libs/angular.min.js')
        ->appendFile($this->basePath() . '/js/angular-file.js')
        ->appendFile($this->basePath() . '/js/dfl-tree.js')

        ->appendFile($this->basePath() . '/js/libs/angular-route.js')

        ->appendFile($this->basePath() . '/js/solo.table.js')
        ->appendFile($this->basePath() . '/js/popups.js')
        ->appendFile($this->basePath() . '/js/main.js')
        ->appendFile($this->basePath() . '/js/app.factory.js')
        ->prependFile($this->basePath() . '/ckeditor/ckeditor.js')
        ->appendFile($this->basePath() . '/js/ng-single-image-upload.js')
        ->appendFile($this->basePath() . '/js/ng-single-file-upload.js')
        ->appendFile($this->basePath() . '/js/ng-entities-list.js')
        ->appendFile($this->basePath() . '/js/ng-entity.js')
        ->prependFile($this->basePath() . '/js/libs/tag-it.js')
        ->prependFile($this->basePath() . '/js/libs/jquery.form.js')
        ->appendFile($this->basePath() . '/js/libs/jquery.cookie.js')
        ->prependFile($this->basePath() . '/js/libs/bootstrap-wysiwyg.js')
        ->prependFile($this->basePath() . '/js/libs/bootstrap-editable.min.js')
        ->prependFile($this->basePath() . '/js/libs/bootstrap.js')
//        ->prependFile($this->basePath() . '/js/libs/jquery-ui.min.js')
        ->prependFile($this->basePath() . '/Scripts/libs/jquery-ui.min.js')
        ->prependFile($this->basePath() . '/js/libs/jquery-1.10.2.min.js')
//        ->prependFile($this->basePath() . '/js/libs/jquery-1.10.2.min.js')
        ->appendFile($this->basePath() . '/js/libs/ng-tags-input.js')
    ?>
</head>

<body>

<div id="wrap">
    <header class="navbar navbar-inverse" role="banner">
        <div class="container">
            <nav class="collapse navbar-collapse" role="navigation">
                <ul class="nav navbar-nav">
                    <li><a href="<?= $this->url('home'); ?>">На сайт</a></li>
                    <li><a href="<?= $this->url('zfcadmin/index'); ?>">Главная</a></li>

                    <li style="clear: left"><a href="<?= $this->url('zfcadmin/catalog'); ?>">Каталог</a></li>
                    <li><a href="<?= $this->url('zfcadmin/blog'); ?>">Блог</a></li>
                    <li><a href="<?= $this->url('zfcadmin/info'); ?>">Информация</a></li>
                    <li><a href="<?= $this->url('zfcadmin/solutions'); ?>">Решения</a></li>
                    <li><a href="<?= $this->url('zfcadmin/projects'); ?>">Проекты</a></li>
                    <li><a href="<?= $this->url('zfcadmin/services'); ?>">Услуги</a></li>
                    <li><a href="<?= $this->url('zfcadmin/offers'); ?>">Спец предложения</a></li>
                    <li><a href="<?= $this->url('zfcadmin/vacancies'); ?>">Вакансии</a></li>
                    <li><a href="<?= $this->url('zfcadmin/team'); ?>">Команда</a></li>
                    <li><a href="<?= $this->url('zfcadmin/clients'); ?>">Клиенты</a></li>
                    <li><a href="<?= $this->url('zfcadmin/contacts'); ?>">Контакты</a></li>
                    <li><a href="<?= $this->url('zfcadmin/banner'); ?>">Баннер</a></li>
                    <li><a href="<?= $this->url('zfcadmin/showroom'); ?>">Шоурум</a></li>
                    <li><a href="<?= $this->url('zfcadmin/user'); ?>">Юзеры</a></li>
                    <li><a href="<?= $this->url('zfcadmin/requests'); ?>">Заявки</a></li>
                    <li><a href="<?= $this->url('zfcadmin/market'); ?>">Яндекс.Маркет</a></li>
                    <li><a href="<?= $this->url('zfcadmin/discounts'); ?>">Партнёрский раздел</a></li>
                    <li><a href="<?= $this->url('zfcadmin/reports'); ?>">Отчёты</a></li>
                    <li><a href="<?= $this->url('zfcadmin/commercials'); ?>">КП</a></li>
                    <li><a href="<?= $this->url('zfcadmin/documents'); ?>">Документы</a></li>
                    <li><a href="<?= $this->url('zfcadmin/brands'); ?>">Производители</a></li>
                    <li><a href="<?= $this->url('zfcadmin/geobanners'); ?>">Геобаннеры</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <main class="container admin-container" id="content" role="main">
        <?= $this->content; ?>
        <div class="clearfix"></div>
    </main>
</div>

<footer class="panel-footer"></footer>

<?= $this->inlineScript() ?>
</body>
</html>