<div class="row">
    <div class="col-md-12 text-center text-small">
        <?= \Application\Service\ApplicationService::getFormedDate($article->date) ?>
    </div>
</div>

<div class="row">
    <div class="col-md-12 text-center"><h1><?= $article->title; ?></h1></div>
</div>

<div class="row">
    <div class="col-md-6 col-md-offset-3"><?= $article->text ?></div>
</div>

<?= \Catalog\Service\CatalogService::renderPopupNav($sl, $prevArt, $nextArt, 'articles'); //навигация ?>

<div class="row row-second">
    <div class="col-md-6 col-md-offset-3">
        <div class="row">
            <div class="col-md-12"><div class="title-line"></div></div>
            <div class="col-md-12 text-center">
                <h2>Упомянутые серии</h2>
            </div>
        </div>
        <div class="row">
            <? foreach($relatedSeries as $series){ ?>
                <div class="col-md-4 series-tile news-popup" data-id="<?= $series->id; ?>">
                    <?= \Catalog\Service\CatalogService::renderSeriesTile(
                        $sl,$series,$this->url('catalog', array('action'=>'subsection', 'id'=>$series->subsection_id))
                    ) ?>
                </div>
            <? }?>
        </div>
    </div>
</div>