<h1>Контакты</h1>

<div class="section">
    <table class="table admin-table  table-striped">
        <tbody>
        <tr>
            <td>Адрес</td>
            <td>
                <div class="editor-get-btn" data-name="adress"><?= $contact->adress; ?></div>
            </td>
        </tr>
        <tr>
            <td>Адрес склада</td>
            <td>
                <div class="editor-get-btn" data-name="adress_storage"><?= $contact->adress_storage; ?></div>
            </td>
        </tr>
        <tr>
            <td>Время работы</td>
            <td>
                <div class="editor-get-btn" data-name="work_time"><?= $contact->work_time; ?></div>
            </td>
        </tr>
        <tr>
            <td>Телефон</td>
            <td>
                <a href="#" data-type="text" data-name="phone" class="editable-param"><?= $contact->phone; ?></a>
            </td>
        </tr>
        <tr>
            <td>Факс</td>
            <td>
                <a href="#" data-type="text" data-name="fax" class="editable-param"><?= $contact->fax; ?></a>
            </td>
        </tr>
        <tr>
            <td>Почта</td>
            <td>
                <a href="#" data-type="text" data-name="mail" class="editable-param"><?= $contact->mail; ?></a>
            </td>
        </tr>
        </tbody>
    </table>
</div>


<div class="section">
    <h3>Список отделений</h3>
    <div class="addPanel">
        <button type="button" class="btn btn-default" id="add-entity">Добавить представительство</button>

        <div class="form-inline" id="adding-form" style="display: none">
            <div class="form-group">
                <label class="sr-only" for="inputName">Название представительства</label>
                <input type="text" class="form-control" id="inputName" placeholder="Введите название..."/>
            </div>

            <button type="button" class="btn btn-default" id="adding-complete">Добавить</button>
            <button type="button" class="btn btn-default" id="adding-cancel">Отмена</button>
        </div>
    </div>
    <div class="addPanel">
        <button type="button" class="btn btn-default" id="tagit-add">Добавить существующий подраздел</button>

        <div id="tagit-form" style="display: none">
            <ul id="tagit-subsections" ></ul>
            <input type="hidden" id="tagit-subsections-res" name="subsectionsIds"/>

            <button type="button" class="btn btn-default" id="tagit-save">Добавить</button>
            <button type="button" class="btn btn-default" id="tagit-cancel">Отмена</button>
        </div>
    </div>
    <table class="table admin-table  table-striped">
        <tr>
            <th>Id</th>
            <th>Название</th>
            <th>Управление</th>
        </tr>
        <tbody id="sortable">
        <? foreach($subsections as $subsec){ ?>
            <tr class="entity" <?= $subsec->deleted ? 'style="color: #BBB"' : '' ?>>
                <td><?= $subsec->id; ?></td>
                <td><?= $subsec->title; ?></td>
                <td>
                    <a href="#" class="editBtn">Редактировать</a>
                    <a href="#" class="removeBtn">Открепить</a>
                    <a href="#" class="deleteBtn">Удалить</a>
                    <a href="#" class="showBtn" <?= $subsec->deleted ? '' : 'style="display: none"' ?>>Показать</a>
                    <a href="#" class="hideBtn" <?= $subsec->deleted ? 'style="display: none"' : '' ?>>Скрыть</a>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>


<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= $contact->id ?>';
        catalog.baseUrl = '<?= $this->url('zfcadmin/contacts') ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INDEX ?>';
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.editablesSave
        });
    });
</script>