<h1>Контакты</h1>
<div class="section">
    <h3>Список офисов</h3>
    <div class="addPanel">
        <button type="button" class="btn btn-default" id="add-entity">Добавить офис</button>

        <div class="form-inline" id="adding-form" style="display: none">
            <div class="form-group">
                <label class="sr-only" for="inputName">Новый офис</label>
                <input type="text" class="form-control" id="inputName" placeholder="Введите наименование..."/>
            </div>

            <button type="button" class="btn btn-default" id="adding-complete">Добавить</button>
            <button type="button" class="btn btn-default" id="adding-cancel">Отмена</button>
        </div>
    </div>
    <div class="addPanel">
        <!--button type="button" class="btn btn-default" id="tagit-add">Добавить существующий подраздел</button-->

        <div id="tagit-form" style="display: none">
            <ul id="tagit-subsections" ></ul>
            <input type="hidden" id="tagit-subsections-res" name="subsectionsIds"/>

            <button type="button" class="btn btn-default" id="tagit-save">Добавить</button>
            <button type="button" class="btn btn-default" id="tagit-cancel">Отмена</button>
        </div>
    </div>
    <table class="table admin-table  table-striped">
        <tr>
            <th>Id</th>
			<th>Наименование</th>
            <th>Адрес</th>
			<th>Часы работы</th>
			<th>Телефон</th>
			<th>Факс</th>
			<th>Почта</th>
            <th>Управление</th>
        </tr>
        <tbody id="sortable">
        <? foreach($subsections as $subsec){ ?>
            <tr class="entity">
                <td><?= $subsec->id; ?></td>
				<td><?= $subsec->title; ?></td>
                <td><?= $subsec->adress; ?></td>
				<td><?= $subsec->work_time; ?></td>
				<td><?= $subsec->phone; ?></td>
				<td><?= $subsec->fax; ?></td>
				<td><?= $subsec->mail; ?></td>
                <td>
                    <a href="#" class="editBtn">Редактировать</a>
                    <a href="#" class="deleteBtn">Удалить</a>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
	
	<? if ($our_contacts) { ?>
	<h3>Внутренняя рассылка уведомлений</h3>
	<table class="table admin-table table-striped">
			<tr id="file">
            <td>CSV-файл Google c контактами сотрудников</td>
            <td>
                <div
                    ng-single-file-upload
                    parent-type="contacts"
					parent-id="1"
                    folder="contacts"
                    field="file"
                ></div>

                <script type="application/javascript">
                    AppFactory("file", "contacts", ["fileMapper", "ur.file"]);
                </script>
            </td>
        </tr><tr><td></td><td></td></tr>
        <tr>
            <th>Id</th>
            <th>E-mail</th>
        </tr>
        <tbody id="sortable">
        <? foreach($our_contacts as $our_contact){ ?>
            <tr class="entity">
                <td><?= $our_contact->id; ?></td>
				<td><?= $our_contact->email; ?></td>
            </tr>
        <? } ?>
        </tbody>
    </table>
	<? } ?>
</div>


<!--script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= $contact->id ?>';
        catalog.baseUrl = '<?= $this->url('zfcadmin/contacts') ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INDEX ?>';
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.editablesSave
        });
    });
</script-->
<script type="text/javascript">
    $(document).ready(function(){
        catalog.baseUrl = '<?= $this->url('zfcadmin/contacts') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/contacts', array('action'=> 'view')) ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INDEX ?>';

        catalog.init();
    });
</script>