<h1>
    <a href="<?= $this->url('zfcadmin/contacts') ?>">Контакты</a>
    >
    <span id="title"><?= $contact->id; ?></span>
</h1>

<div class="section">
    <table class="table admin-table  table-striped">
        <tbody>
		<tr>
            <td>Наименование</td>
            <td>
                <a href="#" data-type="text" data-name="title" class="editable-param"><?= $contact->title; ?></a>
            </td>
        </tr>
        <tr>
            <td>Адрес</td>
            <td>
                <div class="editor-get-btn" data-name="adress"><?= $contact->adress; ?></div>
            </td>
        </tr>
        <tr>
            <td>Адрес склада</td>
            <td>
                <div class="editor-get-btn" data-name="adress_storage"><?= $contact->adress_storage; ?></div>
            </td>
        </tr>
        <tr>
            <td>Время работы</td>
            <td>
                <div class="editor-get-btn" data-name="work_time"><?= $contact->work_time; ?></div>
            </td>
        </tr>
        <tr>
            <td>Телефон</td>
            <td>
                <a href="#" data-type="text" data-name="phone" class="editable-param"><?= $contact->phone; ?></a>
            </td>
        </tr>
        <tr>
            <td>Факс</td>
            <td>
                <a href="#" data-type="text" data-name="fax" class="editable-param"><?= $contact->fax; ?></a>
            </td>
        </tr>
		<tr>
            <td>Дополнительный телефон 1</td>
            <td>
                <a href="#" data-type="text" data-name="add_phone_1" class="editable-param"><?= $contact->add_phone_1; ?></a>
            </td>
        </tr>
		<tr>
            <td>Дополнительный телефон 2</td>
            <td>
                <a href="#" data-type="text" data-name="add_phone_2" class="editable-param"><?= $contact->add_phone_2; ?></a>
            </td>
        </tr>
        <tr>
            <td>Почта</td>
            <td>
                <a href="#" data-type="text" data-name="mail" class="editable-param"><?= $contact->mail; ?></a>
            </td>
        </tr>
		<tr>
            <td>GPS-координаты офиса</td>
            <td>
                <a href="#" data-type="text" data-name="gps_point" class="editable-param"><?= $contact->gps_point; ?></a>
            </td>
        </tr>
		<tr>
            <td>GPS-координаты центра карты</td>
            <td>
                <a href="#" data-type="text" data-name="gps_center" class="editable-param"><?= $contact->gps_center; ?></a>
            </td>
        </tr>
		<tr>
            <td>GPS-увеличение</td>
            <td>
                <a href="#" data-type="text" data-name="gps_zoom" class="editable-param"><?= $contact->gps_zoom; ?></a>
            </td>
        </tr>
		</tbody>
    </table>
</div>

<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= $contact->id ?>';
        catalog.baseUrl = '<?= $this->url('zfcadmin/contacts') ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INDEX ?>';
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.editablesSave
        });
    });
</script>