<h1>
    <a href="<?= $this->url('zfcadmin/team') ?>">Наша команда</a>
    >
    <span id="title"><?= $entity->title; ?></span>
</h1>

<div class="section">
    <h3>Основная информация</h3>
    <table class="table admin-table table-striped">
        <tbody>
        <tr>
            <td>Имя</td>
            <td>
                <a href="#" data-type="text" data-name="title" class="editable-param"><?= $entity->title; ?></a>
            </td>
        </tr>

        <tr ng-app="imageMapper">
            <td>Изображение</td>
            <td ng-controller="ImageCtrl">
                <div
                    ng-single-image-upload
                    parent-type="team"
                    parent-id="<?= $entity->id ?>"
                    folder="team"
                    field="img"
                    img="<?= $entity->img_name ? $entity->img_name : "" ?>"
                    img-id ="<?= $entity->img ? $entity->img : "" ?>"
                    ></div>
                <script type="application/javascript">
                    AppFactory("imageMapper", "images", ["imageMapper", "ur.file"]);
                </script>
            </td>
        </tr>

        <tr>
            <td>Специальность</td>
            <td>
                <a href="#" data-type="text" data-name="role" class="editable-param"><?= $entity->role; ?></a>
            </td>
        </tr>
        <tr>
            <td>Телефон</td>
            <td>
                <a href="#" data-type="text" data-name="phone" class="editable-param"><?= $entity->phone; ?></a>
            </td>
        </tr>
        <tr>
            <td>Почта</td>
            <td>
                <a href="#" data-type="text" data-name="mail" class="editable-param"><?= $entity->mail; ?></a>
            </td>
        </tr>
        <tr>
            <td>Описание</td>
            <td>
                <div class="editor-get-btn" data-name="text"><?= $entity->text; ?></div>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    $(function(){
        catalog.parentId = '<?= $entity->id ?>';
        catalog.baseUrl = '<?= $this->url('zfcadmin/team') ?>';
        catalog.initEditables();

        wysiwyg.init({
            getUrl:'<?= $this->url('zfcadmin/info', array('action' => 'getWysiwygBar')) ?>',
            saveFunction: wysiwyg.editablesSave
        });

        imgUploader.init({
            type: 'single',
            imgUrl: '<?= $this->basePath() . '/images/team/' ?>'
        });
    });
</script>