<?php
$series = $this->series;
$showPic = $this->showPic;
?>


<a href="<?= $this->url('catalog', array('action'=>'series', 'id'=>$series->id)) ?>">
<div class="col-md-12 ">
    <div class="row">
        <div class="subsection-link col-md-12 dotted-top" style="padding-left: 0; padding-right: 0">
            <?= $series->title; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" style="padding: 0">
            <? if ($showPic) { ?>
                <? if (isset($series->previewName)) { ?>
                    <? $src = $series->previewName ? $this->basePath() . '/images/series/' . $series->previewName : $this->basePath() . '/images/empty-series.png' ?>
                <? } else { ?>
                    <? $src = $series->img ? $this->basePath() . '/images/series/' . $series->img : $this->basePath() . '/images/empty-series.png' ?>
                <? } ?>
<!--                --><?// $src = $series->img ? $this->basePath() . '/images/series/' . $series->img : $this->basePath() . '/images/empty-series.png' ?>
                <img src="<?= $src ?>" alt="<?= $series->title ?>"/>
            <? } ?>
        </div>
    </div>
</div>
<div class="subsection-link-icon"></div>
</a>