<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span data-dismiss="modal">×</span></button>
    <h4 class="modal-title text-center"><strong>Восстановление пароля</strong></h4>
</div>
<div class="modal-body">
    <div class="popup-modal">
        <div class="b-partner-registration">
            <form novalidate
                  name="forgot"
                  ng-controller="ForgotPasswordController">
                <div>
                    <div class="b-registration__cell b-registration__cell_left">
                        <label for="identity">Введите ваш e-mail и мы отправим вам новый пароль*</label>
                    </div>
                    <div class="b-registration__cell b-registration__cell_right">
                        <input type="text"
                               class="b-form-control b-form-control_small"
                               data-required="yes"
                               name="identity"
                               id="identity"
                               ng-model="formData.identity"
                               autocomplete="off"
                               required />
                    </div>
                </div>

                <div class="text-center">
                    <div class="b-button b-button_gray" ng-click="submit()" id="registration_button" ng-disabled="forgot.$invalid">
                        <span class="b-button__text">
                            Получить новый пароль
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!--<script type="text/javascript">-->
<!--    $(function(){-->
<!--        window.setTimeout( function(){ formajax.init({changeUrl: false, successPopup: 'passwordsend'})}, 50);-->
<!---->
<!--    });-->
<!--</script>-->
