<div class="row">
    <div class="col-md-12 text-center"><h1>Восстановление пароля</h1></div>
</div>

<form action="<?= $this->url('cabinet', array('action' => 'forgot'))?>" method="post"
      class="aledo-form form-horizontal row-second-small form-left" role="form">

    <div class="form-group">
        <div class="col-md-12">
            <label for="identity" class="col-md-12 control-label">введите ваш e-mail и мы отправим вам новый пароль</label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <input type="text" name="identity" class="form-control" data-required="yes">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <button type="submit" class="btn btn-aledo-black">Восстановить</button>
        </div>
    </div>
</form>

<script type="text/javascript">
    $(function(){
        window.setTimeout( function(){ formajax.init({changeUrl: false, successPopup: 'passwordsend'})}, 50);

    });
</script>
