<div class="row">
    <div class="col-md-12 text-center first-line"><h2>Спасибо, ваш заказ оформлен</h2></div>
</div>

<div class="row row-second-small"><div class="col-md-12"><div class="dotted-bottom"></div></div></div>
<div class="row row-second-small">
    <div class="col-md-12 text-center"><h1>Номер заказа: <?= $params['orderId'] ?></h1></div>
</div>
<div class="row"><div class="col-md-12"><div class="dotted-bottom"></div></div></div>

<div class="row row-second">
    <div class="col-md-12">
        На указанный вами e-mail будет направлено уведомление с описанием и номером заказа. В ближайшее время наш менеджер свяжется с вами для уточнения способа доставки и оплаты товара.
    </div>
</div>
<div style="display:inline;">
    <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/966821971/?label=lugyCJLD5lgQ05CCzQM&amp;guid=ON&amp;script=0"/>
</div>
