<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" onclick="javascript:location.reload();"><span data-dismiss="modal">×</span></button>
    <h4 class="modal-title text-center"><strong>Здравствуйте, <?= $params['name'] ?>!</strong></h4>
</div>
<div class="modal-body">
    <div class="popup-modal">
        <div class="row row-second">
            <div class="col-md-12">
                Ваша заявка принята в обработку.<br />
                В ближайшее время наш менеджер свяжется с вами для уточнения деталей.<br />
                Спасибо, что выбрали нас!
            </div>
        </div>
    </div>
</div>

<script>
    $(function(){
        console.log($.url());
        window.setTimeout( function(){
            location.reload(true)
        }, 30000);
    });
</script>

<!-- Google Code for &#1056;&#1077;&#1075;&#1080;&#1089;&#1090;&#1088;&#1072;&#1094;&#1080;&#1103; Conversion Page -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 995594752;
    var google_conversion_language = "ru";
    var google_conversion_format = "1";
    var google_conversion_color = "ffffff";
    var google_conversion_label = "-kNPCOD02gcQgKTe2gM";
    var google_remarketing_only = false;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/995594752/?label=-kNPCOD02gcQgKTe2gM&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>

<? if ($this->isSpamed) { ?>
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 995594752;
        var google_conversion_language = "en";

        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "fOQICOiC2wcQgKTe2gM";

        var google_remarketing_only = false;
        /* ]]> */
    </script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/995594752/?label=fOQICOiC2wcQgKTe2gM&amp;guid=ON&amp;script=0"/>
        </div>
    </noscript>
<? } ?>