<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span data-dismiss="modal">×</span></button>
    <h4 class="modal-title text-center"><strong>Сообщение отправлено!</strong></h4>
</div>
<div class="modal-body">
    <div class="popup-modal">
        <div class="row row-second">
            <div class="col-md-12">
                В ближайшее время с вами свяжется наш менеджер.
            </div>
        </div>
    </div>
</div>