<!-- NEW -->
<form novalidate
      action="<?= $this->url('cabinet', array('action' => 'register'))?>"
      name="registration"
      ng-controller="RegistrationController">
    <div>
        <div class="b-registration__cell b-registration__cell_left">
            <label for="user_name">Имя*</label>
        </div>
        <div class="b-registration__cell b-registration__cell_right">
            <input type="text"
                   class="b-form-control b-form-control_small"
                   data-required="yes"
                   name="username"
                   id="user_name"
                   ng-model="user_name"
                   autocomplete="off"
                   required />
        </div>
    </div>
    <div>
        <div class="b-registration__cell b-registration__cell_left">
            <label for="user_tel">Контактный телефон*</label>
        </div>
        <div class="b-registration__cell b-registration__cell_right">
            <input type="text"
                   class="b-form-control b-form-control_small"
                   id="user_tel"
                   name="phone"
                   data-required="yes"
                   ng-model="user_tel"
                   autocomplete="off"
                   required />
        </div>
    </div>
    <div>
        <div class="b-registration__cell b-registration__cell_left">
            <label for="user_tel">Город</label>
        </div>
        <div class="b-registration__cell b-registration__cell_right">
            <input type="text"
                   class="b-form-control b-form-control_small"
                   id="user_tel"
                   name="city"
                   data-required="no"
                   ng-model="user_tel"
                   autocomplete="off"
                />
        </div>
    </div>
    <div>
        <div class="b-registration__cell b-registration__cell_left">
            <label for="user_email">E-mail*</label>
        </div>
        <div class="b-registration__cell b-registration__cell_right">
            <input type="text"
                   class="b-form-control b-form-control_small"
                   id="user_email"
                   data-required="yes"
                   name="email"
                   ng-model="user_email"
                   autocomplete="off"
                   required />
        </div>
    </div>

    <div class="b-registration__table">
        <div class="b-registration__row">
            <div class="b-registration__cell b-registration__cell_left">
                <label for="user_password">Пароль*</label>
            </div>
            <div class="b-registration__cell b-registration__cell_right">
                <input type="password"
                       class="b-form-control b-form-control_small"
                       id="user_cur_password"
                       ng-model="user_cur_password"
                       data-required="yes"
                       name="password"
                       autocomplete="off"
                       required />
            </div>
        </div>
        <div class="b-registration__row">
            <div class="b-registration__cell b-registration__cell_left">
                <label for="user_password_repeat">Повторите пароль*</label>
            </div>
            <div class="b-registration__cell b-registration__cell_right">
                <input type="password"
                       class="b-form-control b-form-control_small"
                       id="user_password_repeat"
                       ng-model="user_password_repeat"
                       autocomplete="off"
                       name="passwordVerify"
                       data-required="yes"
                       required />
            </div>
        </div>
    </div>
    <div class="text-center">
        <button class="b-button b-button_gray" id="registration_button" ng-disabled="registration.$invalid" type="submit">
            <span class="b-button__text">
                СОХРАНИТЬ ПЕРСОНАЛЬНЫЕ ДАННЫЕ
            </span>
        </button>
    </div>
</form>

<script type="text/javascript">
    $(function(){
        window.setTimeout( function(){
            formajax.init({
                changeUrl: false,
                successPopup: 'regsuccessFromCart'
            })
        }, 100);
    });
</script>