<?//
//    /** @var \ZfcUser\Form\Register $form */
//    $form = $this->form;
//
//    $form->setAttribute('action', $this->url('cabinet',array('action'=>'register')));
//    $form->setAttribute('class', "form-horizontal form-left row-second-small");
//    $form->setAttribute('role', "form");
//    $form->prepare();
//?>
<!--<div class="row">-->
<!--    <div class="col-md-12 text-center"><h1>Регистрация</h1></div>-->
<!--</div>-->
<!---->
<!--<form action="--><?//= $this->url('cabinet', array('action' => 'register'))?><!--" method="post"-->
<!--      class="aledo-form form-left form-horizontal row-second-small" role="form">-->
<!--    <div class="form-group">-->
<!--        <label class="col-md-4 control-label">имя*</label>-->
<!--        <div class="col-md-8">-->
<!--            --><?//
//            $username = $form->get('username');
//            $username->setAttribute('class', "form-control");
//            $username->setAttribute('data-required', "yes");
//            ?>
<!--            --><?//= $this->formText($username) ?>
<!--        </div>-->
<!--    </div>-->
<!---->
<!--    <div class="form-group">-->
<!--        <label class="col-md-6 control-label">контактный телефон*</label>-->
<!--        <div class="col-md-6">-->
<!--            --><?//
//            $phone = $form->get('phone');
//            $phone->setAttribute('class', "form-control");
//            $phone->setAttribute('data-required', "yes");
//            ?>
<!--            --><?//= $this->formText($phone) ?>
<!--<!--            <input name="phone" type="text" class="form-control">-->
<!--        </div>-->
<!--    </div>-->
<!---->
<!--    <div class="form-group">-->
<!--        <label class="col-md-6 control-label">Город</label>-->
<!--        <div class="col-md-6">-->
<!--            --><?//
//            $city = $form->get('city');
//            $city->setAttribute('class', "form-control");
//            $city->setAttribute('data-required', "no");
//            ?>
<!--            --><?//= $this->formText($city) ?>
<!--        </div>-->
<!--    </div>-->
<!---->
<!--    <div class="form-group">-->
<!--        <label class="col-md-4 control-label">e-mail*</label>-->
<!--        <div class="col-md-8">-->
<!--            --><?//
//            $email = $form->get('email');
//            $email->setAttribute('class', "form-control");
//            $email->setAttribute('data-required', "yes");
//            ?>
<!--            --><?//= $this->formText($email) ?>
<!--<!--            <input name="email" type="text" class="form-control">-->
<!--        </div>-->
<!--    </div>-->
<!---->
<!--    <div class="checkbox col-md-offset-1">-->
<!--        --><?//
//        $is_spamed = $form->get('is_spamed');
//        $is_spamed->setAttribute('id', "reg-spam");
//        $is_spamed->setValue(1);
//        ?>
<!--        --><?//= $this->formCheckbox($is_spamed) ?>
<!--        <label for="reg-spam">подписаться на рассылку-->
<!--            <br>(не волнуйтесь, мы не рассылаем СПАМ)</label>-->
<!--    </div>-->
<!---->
<!--    <div class="form-group row-second-small">-->
<!--        <label class="col-md-6 control-label">пароль*</label>-->
<!--        <div class="col-md-6">-->
<!--            <input name="password" type="password" class="form-control" data-required="yes">-->
<!--        </div>-->
<!--    </div>-->
<!---->
<!--    <div class="form-group">-->
<!--        <label class="col-md-6 control-label">подтвердите пароль*</label>-->
<!--        <div class="col-md-6">-->
<!--            --><?//
//            $passwordVerify = $form->get('passwordVerify');
//            $passwordVerify->setAttribute('class', "form-control");
//            $passwordVerify->setAttribute('data-required', "yes");
//            ?>
<!--            --><?//= $this->formPassword($passwordVerify) ?>
<!--        </div>-->
<!--    </div>-->
<!---->
<!--    <div class="form-group">-->
<!--        <div class="col-md-12">-->
<!--            <input type="hidden" name="redirect" value="--><?//= $url ?><!--"/>-->
<!--            <button id="popup-reg-complete" type="submit" class="btn btn-aledo-black">Зарегистрироваться</button>-->
<!--        </div>-->
<!--    </div>-->
<!--</form>-->

<!-- NEW -->

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span data-dismiss="modal">×</span></button>
    <h4 class="modal-title text-center"><strong>РЕГИСТРАЦИЯ</strong></h4>
</div>
<div class="modal-body">
    <div class="popup-modal">
        <hr class="dotted-separator" />
        <div class="text-center b-mt1 b-mb1">ВАШИ ПЕРСОНАЛЬНЫЕ ДАННЫЕ:</div>
        <hr class="dotted-separator b-mb1" />
        <div class="b-partner-registration">
                    <form novalidate
                          name="registration"
                          ng-controller="RegistrationController">
                        <div>
                            <div class="b-registration__cell b-registration__cell_left">
                                <label for="user_name">Имя*</label>
                            </div>
                            <div class="b-registration__cell b-registration__cell_right">
                                <input type="text"
                                       class="b-form-control b-form-control_small"
                                       data-required="yes"
                                       name="user_name"
                                       id="user_name"
                                       ng-model="formData.user_name"
                                       ng-init="formData.user_name=''"
                                       autocomplete="off"
                                       ng-change="validityOnChange('user_name')"
                                       required />
                                <div class=""
                                     ng-show="registration.user_name.$dirty && registration.user_name.$invalid">
                                    <small class="b-form-error"
                                           ng-show="registration.user_name.$error.stringLengthTooShort">
                                        Длина поля должна быть по меньшей мере 3 символа
                                    </small>
                                </div>
                            </div>

                        </div>
                        <div>
                            <div class="b-registration__cell b-registration__cell_left">
                                <label for="user_tel">Контактный телефон*</label>
                            </div>
                            <div class="b-registration__cell b-registration__cell_right">
                                <input type="text"
                                       class="b-form-control b-form-control_small"
                                       id="user_tel"
                                       name="user_tel"
                                       data-required="yes"
                                       ng-model="formData.user_tel"
                                       ng-init="formData.user_tel=''"
                                       autocomplete="off"
                                       ng-change="validityOnChange('user_tel')"
                                       required />
                            </div>
                        </div>
                        <div>
                            <div class="b-registration__cell b-registration__cell_left">
                                <label for="user_city">Город*</label>
                            </div>
                            <div class="b-registration__cell b-registration__cell_right">
                                <input type="text"
                                       class="b-form-control b-form-control_small"
                                       id="user_city"
                                       name="user_city"
                                       data-required="yes"
                                       ng-model="formData.user_city"
                                       ng-init="formData.user_city=''"
                                       ng-change="validityOnChange('user_city')"
                                       autocomplete="off"
                                       required
                                    />
                            </div>
                        </div>
                        <div>
                            <div class="b-registration__cell b-registration__cell_left">
                                <label for="user_email">E-mail*</label>
                            </div>
                            <div class="b-registration__cell b-registration__cell_right">
                                <input type="text"
                                       class="b-form-control b-form-control_small"
                                       id="user_email"
                                       data-required="yes"
                                       name="user_email"
                                       ng-model="formData.user_email"
                                       ng-init="formData.user_email=''"
                                       ng-change="validityOnChange('user_email')"
                                       autocomplete="off"
                                       required />
                                <div class=""
                                     ng-show="registration.user_email.$dirty && registration.user_email.$invalid">
                                    <small class="b-form-error"
                                           ng-show="registration.user_email.$error.recordFound">
                                        Пользователь с таким Email уже зарегистрирован
                                    </small>
                                    <small class="b-form-error"
                                           ng-show="registration.user_email.$error.stringLengthTooShort">
                                        Длина поля должна быть по меньшей мере 3 символа
                                    </small>
                                    <small class="b-form-error"
                                           ng-show="registration.user_email.$error.wrong_format">
                                        Неправильный формат почты
                                    </small>
                                </div>
                            </div>
                        </div>

                        <div class="b-registration__table">
                            <div class="b-registration__row">
                                <div class="b-registration__cell b-registration__cell_left">
                                    <label for="user_cur_password">Пароль*</label>
                                </div>
                                <div class="b-registration__cell b-registration__cell_right">
                                    <input type="password"
                                           class="b-form-control b-form-control_small"
                                           id="user_cur_password"
                                           ng-model="formData.user_cur_password"
                                           ng-init="formData.user_cur_password=''"
                                           data-required="yes"
                                           name="user_cur_password"
                                           ng-change="validityOnChange('user_cur_password')"
                                           autocomplete="off"
                                           required />
                                    <div class=""
                                         ng-show="registration.user_cur_password.$dirty && registration.user_cur_password.$invalid">
                                        <small class="b-form-error"
                                               ng-show="registration.user_cur_password.$error.is_empty">
                                            Поле не может быть пустым
                                        </small>
                                        <small class="b-form-error"
                                               ng-show="registration.user_cur_password.$error.stringLengthTooShort">
                                            Длина поля должна быть по меньшей мере 6 символов
                                        </small>
                                    </div>
                                </div>
                            </div>
                            <div class="b-registration__row">
                                <div class="b-registration__cell b-registration__cell_left">
                                    <label for="user_password_repeat">Повторите пароль*</label>
                                </div>
                                <div class="b-registration__cell b-registration__cell_right">
                                    <input type="password"
                                           class="b-form-control b-form-control_small"
                                           id="user_password_repeat"
                                           ng-model="formData.user_password_repeat"
                                           ng-init="formData.user_password_repeat=''"
                                           autocomplete="off"
                                           name="user_password_repeat"
                                           ng-change="validityOnChange('user_password_repeat')"
                                           data-required="yes"
                                           required />
                                    <div class=""
                                         ng-show="registration.user_password_repeat.$dirty && registration.user_password_repeat.$invalid">
                                        <small class="b-form-error"
                                               ng-show="registration.user_password_repeat.$error.is_empty">
                                            Поле не может быть пустым
                                        </small>
                                        <small class="b-form-error"
                                               ng-show="registration.user_password_repeat.$error.notSame">
                                            Пароли не совпадают
                                        </small>
                                        <small class="b-form-error"
                                               ng-show="registration.user_password_repeat.$error.stringLengthTooShort">
                                            Длина поля должна быть по меньшей мере 6 символов
                                        </small>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="b-registration__row">
                            <input class="b-form-control b-checkbox"
                                   type="checkbox"
                                   id="user_is_spamed"
                                   ng-model="formData.user_is_spamed"
                                   ng-init="formData.user_is_spamed=true"
                                />
                            <label for="user_is_spamed">подписаться на рассылку (информация о скидках, акциях)</label>

                        </div>
                        <div class="text-center">
                            <div class="b-button b-button_gray" ng-click="submit()" id="registration_button" ng-disabled="registration.$invalid">
                                <span class="b-button__text">
                                    СОХРАНИТЬ ПЕРСОНАЛЬНЫЕ ДАННЫЕ
                                </span>
                            </div>
                        </div>
                    </form>
        </div>
    </div>
</div>
<!---->
<!--<script type="text/javascript">-->
<!--    $(function(){-->
<!--        window.setTimeout( function(){-->
<!--            formajax.init({-->
<!--                changeUrl: false,-->
<!--                successPopup: 'regsuccess'-->
<!--            })-->
<!--        }, 100);-->
<!--    });-->
<!--</script>-->