<div class="row" style="padding-top: 20px">
    <div class="col-md-10 col-md-offset-1 text-center"><h2>Вы успешно зарегистрированы!</h2></div>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="dotted-top"></div>
    </div>
</div>
<div class="row row-second" style="padding-bottom: 20px">
    <div class="col-md-10 col-md-offset-1" style="font-size: 11px">
        На указанный вами e-mail отправлено сообщение с регистрационными данными. Спасибо, что выбрали нас!
    </div>
</div>

<script>
    $(function(){
        window.setTimeout( function(){
            location.reload(true)
        }, 30000);
    });
</script>

<!-- Google Code for &#1056;&#1077;&#1075;&#1080;&#1089;&#1090;&#1088;&#1072;&#1094;&#1080;&#1103; Conversion Page -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 995594752;
    var google_conversion_language = "ru";
    var google_conversion_format = "1";
    var google_conversion_color = "ffffff";
    var google_conversion_label = "-kNPCOD02gcQgKTe2gM";
    var google_remarketing_only = false;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/995594752/?label=-kNPCOD02gcQgKTe2gM&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>

<? if ($this->isSpamed) { ?>
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 995594752;
        var google_conversion_language = "en";

        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "fOQICOiC2wcQgKTe2gM";

        var google_remarketing_only = false;
        /* ]]> */
    </script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/995594752/?label=fOQICOiC2wcQgKTe2gM&amp;guid=ON&amp;script=0"/>
        </div>
    </noscript>
<? } ?>