<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span data-dismiss="modal">×</span></button>
    <h4 class="modal-title text-center"><strong>ЗАЯВКА НА ПРОЕКТ</strong></h4>
</div>
<div class="modal-body">
    <div class="popup-modal" ng-controller="CalculationServiceController">
            <? $sl = $this->getHelperPluginManager()->getServiceLocator(); ?>

        <form novalidate ng-submit="submit()" name="calculationService">
                <div>
                    <div>
                        <div class="b-registration__cell b-registration__cell_left">
                            <label for="username">ФИО*</label>
                        </div>
                        <div class="b-registration__cell b-registration__cell_right">
                            <input type="text"
                                   class="b-form-control b-form-control_small"
                                   id="username"
                                   ng-model="formData.name"
                                   autocomplete="on" <?= ($this->isRegistered && $this->user->getUsername()) ?
                                'value="' . $this->user->getUsername() . '"' : ''?> required />
                        </div>
                    </div>
                    <div>
                        <div class="b-registration__cell b-registration__cell_left">
                            <label for="phone">Контактный телефон*</label>
                        </div>
                        <div class="b-registration__cell b-registration__cell_right">
                            <input type="text" input-mask="+7 (999) 999-99-99"
                                   class="b-form-control b-form-control_small" id="phone" ng-model="formData.phone" autocomplete="on"
                                <?= ($this->isRegistered && $this->user->getPhone()) ? 'value="' . $this->user->getPhone() . '"' : ''?> required />
                        </div>
                    </div>
                    <div>
                        <div class="b-registration__cell b-registration__cell_left">
                            <label for="email">E-mail*</label>
                        </div>
                        <div class="b-registration__cell b-registration__cell_right">
                            <input type="text" class="b-form-control b-form-control_small" id="email" ng-model="formData.mail" autocomplete="on"
                                <?= ($this->isRegistered && $this->user->getEmail()) ? 'value="' . $this->user->getEmail() . '"' : ''?> required />
                        </div>
                    </div>
                    <div class="b-form-group">
                        <div class="b-registration__cell b-registration__cell_left">
                            <label for="city">Город*</label>
                        </div>
                        <div class="b-registration__cell b-registration__cell_right">
                            <input type="text" class="b-form-control b-form-control_small" id="city" ng-model="formData.city" autocomplete="on"
                                <?= ($this->isRegistered && $this->user->getCity()) ? 'value="' . $this->user->getCity() . '"' : ''?> required />
                        </div>
                    </div>

                    <div class="b-order-place__file-zone" style="width: 100%;height: auto;padding: 1rem;" ng-class="{'b-order-place__file-zone_file-uploaded' : fileName.length }">
                        <div><input type="file" name="file" file-model="formData.file" id="orderDetails" onchange="angular.element(this).scope().showFileName(this)" /></div>
                        <input class="hidden-last-file" type="hidden" value="<?= $this->lastFile ? '1' : '0' ?>" name="formData.service_lastFile" style="display: none"/>

                        <div class="b-order-place__file-zone-label" ng-hide="fileName.length">
                            <script type="text/javascript">
                                if (browser.msie9) {
                                    $('.b-order-place__file-zone-label').html("<u>Загрузите</u> чертёж<br/>(DWG, PDF, JPG, DOC)");
                                } else {
                                    $('.b-order-place__file-zone-label').html("Перетащите чертёж<br/>(DWG, PDF, JPG, DOC) " +
                                    "сюда или <u>загрузите файл</u>");
                                }

                            </script>
                        </div>
                        <div ng-show="fileName.length">
                            <span ng-bind="fileName"></span>

                            <div>
                                <button type="button" class="b-order-place__file-reset close" ng-click="resetFile(angular.element(this))">
                                    &times;
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <input type="text" name="form-type" ng-init="formData['form-type']=<?= \Services\Controller\ServicesController::PROJECT_ORDER_FORM ?>" style="display: none"
                   ng-value="<?= \Services\Controller\ServicesController::PROJECT_ORDER_FORM ?>"/>
                <div class="text-darker-gray text-center">
                    <button class="b-button b-button_gray" id="partner_reistration_button" ng-disabled="calculationService.$invalid">
                        <span class="b-button__text">
                            отправить заявку
                        </span>
                    </button>
                </div>

        </form>
    </div>
</div>