<!-- NEW -->

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span data-dismiss="modal">×</span></button>
    <h4 class="modal-title text-center"><strong>ОТПРАВИТЬ РЕЗЮМЕ</strong></h4>
</div>
<div class="modal-body">
    <div class="popup-modal">
        <hr class="dotted-separator" />
        <div class="text-center b-mt1 b-mb1">КОНТАКТНАЯ ИНФОРМАЦИЯ</div>
        <div class="b-partner-registration">
                    <form novalidate
                          name="work"
                          ng-controller="JobController">
                        <div>
                            <div class="b-registration__cell b-registration__cell_left">
                                <label for="work_name">ФИО*</label>
                            </div>
                            <div class="b-registration__cell b-registration__cell_right">
                                <input type="text"
                                       class="b-form-control b-form-control_small"
                                       data-required="yes"
                                       name="work_name"
                                       id="work_name"
                                       ng-model="formData.name"
                                       ng-init="formData.name=''"
                                       autocomplete="off"
                                       ng-change="validityOnChange('name')"
                                       required />
							    <div class="ng-hide" ng-show="nameError"><small class="b-form-error">Введите имя (минимум 3 символа)</small></div>
                                <div class=""
                                     ng-show="registration.name.$dirty && registration.name.$invalid">
                                    <small class="b-form-error"
                                           ng-show="registration.name.$error.stringLengthTooShort">
                                        Длина поля должна быть по меньшей мере 3 символа
                                    </small>
                                </div>
                            </div>

                        </div>
                        <div>
                            <div class="b-registration__cell b-registration__cell_left">
                                <label for="work_tel">Номер телефона*</label>
                            </div>
                            <div class="b-registration__cell b-registration__cell_right">
                                <input type="text"
                                       class="b-form-control b-form-control_small"
                                       id="work_tel"
                                       name="work_tel"
                                       data-required="yes"
                                       ng-model="formData.tel"
                                       ng-init="formData.tel=''"
                                       autocomplete="off"
                                       ng-change="validityOnChange('tel')"
                                       required />
                            </div>
                        </div>
                        <div>
                            <div class="b-registration__cell b-registration__cell_left">
                                <label for="work_mail">E-mail*</label>
                            </div>
                            <div class="b-registration__cell b-registration__cell_right">
                                <input type="text"
                                       class="b-form-control b-form-control_small"
                                       id="work_mail"
                                       data-required="yes"
                                       name="work_mail"
                                       ng-model="formData.mail"
                                       ng-init="formData.mail=''"
                                       ng-change="validityOnChange('mail')"
                                       autocomplete="off"
                                       required />
                                <div class=""
                                     ng-show="registration.mail.$dirty && registration.mail.$invalid">
                                    <small class="b-form-error"
                                           ng-show="registration.mail.$error.recordFound">
                                        Пользователь с таким Email уже зарегистрирован
                                    </small>
                                    <small class="b-form-error"
                                           ng-show="registration.mail.$error.stringLengthTooShort">
                                        Длина поля должна быть по меньшей мере 3 символа
                                    </small>
                                    <small class="b-form-error"
                                           ng-show="registration.mail.$error.wrong_format">
                                        Неправильный формат почты
                                    </small>
                                </div>
                            </div>
                        </div>

                        <hr class="dotted-separator b-mt1 b-mb1" />
                        <div class="text-center">
                            <div class="b-button b-button_gray" ng-click="submit()" id="registration_button" ng-disabled="registration.$invalid">
                                <span class="b-button__text">
                                    ОТПРАВИТЬ ЗАПРОС
                                </span>
                            </div>
                        </div>
                    </form>
        </div>
    </div>
</div>