    <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"><span data-dismiss="modal">×</span></button>
                                <h4 class="modal-title text-center"><strong>ОТПРАВИТЬ РЕЗЮМЕ</strong></h4>
                            </div>
                            <div class="modal-body">
                                <div class="popup-modal">
                                    <hr class="dotted-separator b-mb2" />
                                    <p class="text-center">КОНТАКТНАЯ ИНФОРМАЦИЯ</p>
                                    <form name="vacancy_form" enctype="multipart/form-data" ng-controller="JobController">
									<input type="hidden" id="vacancy_id" ng-model="formData.vacancy" ng-init="formData.vacancy='<?= $params ?>'" name="vacancy_id" value="<?= $params ?>" />
                                        <div class="b-work-form b-work-form_vacancy b-clearfix">
                                            <div class="b-work-form__table">
                                                <div>
                                                    <div class="b-work-form__cell b-work-form__cell_left text-nowrap">
                                                        <label for="vacancy_name">ФИО*</label>
                                                    </div>
                                                    <div class="b-work-form__cell ">
                                                        <input  ng-model="formData.name" ng-init="formData.name=''" name="vacancy_name" id="vacancy_name"
                                                                class="b-form-control b-form-control_small" required=""/>
                                                        <div class="ng-hide" ng-show="nameError">
                                                            <small class="b-form-error">Введите имя (минимум 3 символа)</small></div>
                                                    </div>
                                                </div>
                                                <div>
                                                    <div class="b-work-form__cell b-work-form__cell_left text-nowrap">
                                                        <label for="vacancy_phone">Номер телефона *</label>
                                                    </div>
                                                    <div class="b-work-form__cell">
                                                        <input  ng-model="formData.phone" id="vacancy_phone" ng-init="formData.phone=''"
                                                                class="b-form-control b-form-control_small" id="vacancy_phone" required="" />
                                                        <div class="ng-hide" ng-show="phoneError"><small class="b-form-error">Введите корректный номер телефона</small></div>
                                                    </div>
                                                </div>
                                                <div>
                                                    <div class="b-work-form__cell b-work-form__cell_left text-nowrap">
                                                        <label for="vacancy_mail">E-mail*</label>
                                                    </div>
                                                    <div class="b-work-form__cell">
                                                        <input  id="vacancy_mail"
                                                                required=""
                                                                ng-model="formData.mail" ng-init="formData.mail=''" name="vacancy_mail" class="b-form-control b-form-control_small" />
                                                        <div class="ng-hide" ng-show="mailError"><small class="b-form-error">Введите корректный e-mail</small></div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="b-work-form__file  b-work-form_vacancy__file text-center">
                                                <div class="b-work-form__file-zone b-work-form_vacancy__file-zone" style="width: 100%;height: auto;" ng-class="{'b-work-form_vacancy__file-zone_file-uploaded' : fileName.length }">

                                                    <div><input type="file" name="file" file-model="formData.file" ng-init="formData.file=''" id="jobDetails" onchange="angular.element(this).scope().showFileName(this)" /></div>

                                                    <div class="b-work-form__file-zone-label b-work-form_vacancy__file-zone-label" ng-hide="fileName.length">
                                                        
														Перетащите файл резюме (TXT, DOC, PDF) сюда или <u>загрузить файл</u>
                                                    </div>
                                                    <div ng-show="fileName.length">
                                                        <span ng-bind="fileName"></span>
                                                        <button type="button" class="b-work-form__file-reset close" ng-click="resetFile(angular.element(this))">&times;</button>
                                                    </div>
                                                </div>
 <div class="ng-hide" ng-show="fileError"><small class="b-form-error">Загрузите файл с резюме</small></div>
                                            </div>
                                           
                                            <div class="b-work-form__table">
                                                <label for="vacancy_letter">Сопроводительное письмо</label>
                                                <textarea id="vacancy_letter" name="vacancy_letter" ng-model="formData.letter" ng-init="formData.letter=''" rows="5" class="b-form-control b-form-control_small"></textarea>
                                            </div>
                                            <hr class="dotted-separator b-mt2"/>
                                            <div class="text-center">
                                            <button class="b-button b-button_gray" id="vacancy_submit" ng-disabled="vacancy_form.$invalid" ng-click="submit()">
                                                <span class="b-button__text">отправить запрос</span>
                                            </button>
                                            </div>
                                        </div>

                                    </form>
                                </div>
                            </div>