<?
if (!$footerBlocks) {
	$footerBlocks = $this->getHelperPluginManager()->getServiceLocator()->get('FooterBlocksTable')->fetchAll("order ASC");
	
	$footerArr = array();
	foreach ($footerBlocks as $fb) {
		$footerArr[$fb->column][] = $fb;
	}
}
?>
<footer class="b-layout-footer b-section">
    <div class="b-section__content">
        <div class="row b-footer-mobile-table">
            <div class="col-xs-12 col-sm-6  col-md-3 b-footer-mobile-col b-footer-mobile-col_left">
                <div class="b-footer-mobile-col__inner">
					<? foreach($contacts_ as $contact) {?>
                    <p>
                        <?= $contact->adress ?>
                    </p>
					<? } ?>
					<p>
                        <?= $contacts_[0]->work_time ?>
                    </p>
                    <p>
                        Бесплатно по РФ<br />
                        8 (800) 555 56 72
                    </p>
                    <p>
                        8 (812) 448 58 49 СПБ<br />
                        8 (499) 703 24 42 МСК
                    </p>
<!--                    <p>-->
<!--                        <a href="mailto:--><?//= $contacts_[0]->mail ?><!--">--><?//= $contacts_[0]->mail ?><!--</a>-->
<!--                    </p>-->
                </div>
            </div>
            <div class="b-footer-mobile-col b-footer-mobile-col_decoration visible-sm-table-cell visible-xs"></div>
            <div class=" col-xs-12 col-sm-6 col-md-9 b-footer-mobile-col b-footer-mobile-col_right">
                <div class="row">
                    <div class="b-footer-mobile-col__inner b-footer-mobile-col_right__inner" id="footer_collapse">
                        <div class="col-md-4 panel">
                            <h5 class="text-darker b-layout-footer__col-heading hidden-xs hidden-sm"><strong>Клиентам</strong></h5>

                            <h5 class="text-darker b-layout-footer__col-heading visible-sm-block visible-xs-block">
                                <a href="#collapse_clients" data-parent="#footer_collapse"
                                   data-toggle="collapse" class="collapsed"><strong>Клиентам</strong></a>
                            </h5>
                            <ul class="list-unstyled  collapse" id="collapse_clients">

                                <? foreach ($footerArr[1] as $fa1) { ?>
                                <li><a class="b-highlighted-link" href="<?= $fa1->link ?>"><?= $fa1->title ?></a></li>
                                <? } ?>
                            </ul>
                        </div>
                        <div class=" col-md-3 panel">
                            <h5 class="text-darker b-layout-footer__col-heading hidden-xs hidden-sm"><strong>О нас</strong></h5>
                            <h5 class="text-darker b-layout-footer__col-heading visible-sm-block visible-xs-block">
                                <a href="#collapse_about" class="collapsed"  data-parent="#footer_collapse" data-toggle="collapse"><strong>О нас</strong></a>
                            </h5>

                            <ul class="list-unstyled collapse" id="collapse_about">
                                <? foreach ($footerArr[2] as $fa2) { ?>
                                    <li><a class="b-highlighted-link" href="<?= $fa2->link ?>"><?= $fa2->title ?></a></li>
                                <? } ?>
                            </ul>
                        </div>
                        <div class=" col-md-3 panel ">
                            <h5 class="text-darker b-layout-footer__col-heading hidden-xs hidden-sm"><strong>Скачать</strong></h5>
                            <h5 class="text-darker b-layout-footer__col-heading visible-sm-block visible-xs-block">
                                <a href="#collapse_download" data-parent="#footer_collapse" data-toggle="collapse" class="collapsed"><strong>Скачать</strong></a>
                            </h5>
                            <ul class="list-unstyled  collapse" id="collapse_download">
                                <? foreach ($footerArr[3] as $fa3) { ?>
                                    <li><a class="b-highlighted-link" href="<?= $fa3->link ?>"><?= $fa3->title ?></a></li>
                                <? } ?>
                            </ul>
                        </div>
                        <div class="col-md-2 ">
                            <ul class="list-unstyled">
								<li><a class="b-highlighted-link" href="/sitemap/">Карта сайта</a></li>
                                <? if ($user = $this->zfcUserIdentity()){ ?>
                                    <li><a class="b-highlighted-link" href="/cabinet">Личный кабинет</a></li>
                                    <li><a class="b-highlighted-link" href="/cabinet/logout?redirect=<?= '//' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>">Выйти</a></li>
                                <? } ?>
                            </ul>
                        </div>
                    </div>

                </div>

            </div>
        </div>

        <br class="hidden-xs"/>

        <hr class="dotted-separator" />
        <div class="b-footer-link-nav">
            <a class="b-footer-link-nav__link b-footer-link-nav__link_left" href="/index">
                <img src="/Content/images/footer-logo-left.svg"/>
                <img src="/Content/images/footer-logo-left-hover.svg" />
            </a>
            <div class="b-footer-link-nav__link-separator"></div>
            <a class="b-footer-link-nav__link b-footer-link-nav__link_right" href="http://kaledoscop.ru">
                <img src="/Content/images/footer-logo-right.svg" />
                <img src="/Content/images/footer-logo-right-hover.svg" />
            </a>
        </div>
        <!-- <hr class="dotted-separator" />
         <div class="b-footer-social-link-nav">
             <a class="b-footer-social-link-nav__link b-footer-social-link-nav__link_vk"></a>
             <a class="b-footer-social-link-nav__link b-footer-social-link-nav__link_fb"></a>
         </div> -->
    </div>
</footer>

<script>
    $('#popup-register').on('click', function(e){
        e.preventDefault();
        showFooBarPopup('register');
    });
</script>