<header class="b-layout__header b-section b-layout-header ">
    <div class="b-authorize b-section " id="auth_block" style="display: none">

        <a href="javascript:void(0)" class="b-authorize__close" onclick="aledo.hideAuthBlock()">
            <img src="/Content/images/icon-close.svg" width="20" height="20" />
        </a>
        <div class="b-section__content  b-clearfix">
            <div class="b-authorize__row">
                <form novalidate
                      name="login-form"
                      method="post"
                      ng-enter="submit()"
                      id="login-form"
                      action="<?= $this->url('cabinet', array('action' => 'login'))?>"
                      ng-controller="LoginController">
                    <p class="b-authorize__heading">Вход в личный кабинет</p>
                    <div class="b-authorize__col">
                        <input name="identity"
                               type="text"
                               id="auth_email"
                               placeholder="Ваш e-mail"
                               class="b-form-control b-form-control_small b-form-control_auth"
                               ng-model="formData.identity" />
                        <div class=""  style="margin-top: -0.7rem;"
                             ng-show="loginError">
                            <small class="b-form-error">
                                Неправильный логин или пароль
                            </small>
                        </div>
                    </div>
                    <div class="b-authorize__col">
                        <input name="credential"
                               type="password"
                               id="auth_password"
                               placeholder="Ваш пароль"
                               class="b-form-control b-form-control_small b-form-control_auth"
                               ng-model="formData.credential" />
                        <a href="javascript:void(0)" class="text-darker-gray b-password-recovery-trigger" ng-controller="PopupController" ng-click="getPopup(ALEDO_POPUP_FORGOT)"><small>Забыли пароль?</small></a>
                    </div>
                    <div class="b-authorize__col">
                        <a ng-click="submit()" class="b-button b-button_gray b-button_auth b-button_small">
                            <span class="b-button__text">Войти</span>
                        </a>
                        <a class="b-button b-button_gray b-button_auth b-button_small" ng-controller="PopupController" href="javascript:void(0)" ng-click="getPopup(ALEDO_POPUP_REGISTER)">
                            <span class="b-button__text">Зарегистрироваться</span>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="b-section__content b-section__content_mobile-header" id="mobile_header_anchor">
        <div class="b-header-top-section">
            <div class="b-header-top-section__left">
                <a href="/" class="b-header-top-section__logo-link">

                    <svg version="1.1" id="Слой_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                         viewBox="0 136 960 289" enable-background="new 0 136 960 289" xml:space="preserve" class="b-logo-icon">
<g>
    <g class="hidden-xs hidden-sm b-logo-icon__scrolled-hidden">
        <path fill="#6E7071" d="M96.8,411.8c-1.9,0-3.8-0.4-5.4-1.1s-2.7-1.5-3.8-2.7c-1.1-1.1-1.9-2.7-2.3-4.2c-0.4-1.5-0.8-3.4-0.8-5.4
			s0.4-3.8,0.8-5.4c0.4-1.5,1.1-3.1,2.3-4.6c1.1-1.1,2.3-2.3,3.8-3.1c1.5-0.8,3.4-1.1,5.4-1.1c1.5,0,3.1,0,4.2,0.4
			c1.1,0.4,2.3,0.8,3.4,1.5s1.9,1.5,2.3,2.7c0.8,1.1,1.1,2.7,1.1,4.2h-4.6c-0.4-1.5-1.1-3.1-2.3-3.8c-1.1-0.8-2.7-1.5-4.2-1.5
			c-1.5,0-3.1,0.4-3.8,0.8c-1.1,0.8-1.9,1.5-2.7,2.3c-0.8,0.8-1.1,1.9-1.5,3.4c-0.4,1.1-0.4,2.7-0.4,3.8c0,1.1,0,2.3,0.4,3.4
			c0.4,1.1,0.8,2.3,1.5,3.1c0.8,0.8,1.5,1.5,2.3,2.3c1.1,0.4,2.3,0.8,3.4,0.8c2.3,0,3.8-0.4,5-1.5c1.1-1.1,1.9-2.7,2.3-4.6h4.6
			c-0.4,3.4-1.5,5.7-3.4,7.6C102.9,411,100.2,411.8,96.8,411.8z" />
        <path fill="#6E7071" d="M113.2,385h12.2c1.1,0,2.3,0,3.4,0.4c1.1,0,1.9,0.4,3.1,1.1c0.8,0.4,1.5,1.1,1.9,1.9
			c0.4,0.8,0.8,1.9,0.8,3.1c0,1.5-0.4,2.7-1.1,3.4c-0.8,0.8-1.5,1.5-2.7,2.3l0,0c1.5,0.4,2.7,1.1,3.8,2.3c0.8,1.1,1.5,2.7,1.5,4.2
			c0,1.1-0.4,2.3-0.8,3.1c-0.4,0.8-0.8,1.9-1.5,2.3c-0.8,0.8-1.5,1.1-2.7,1.5c-1.1,0.4-1.9,0.8-3.1,0.8H114V385H113.2z M125.1,395.7
			c1.9,0,3.1-0.4,3.8-1.1c0.8-0.8,1.1-1.5,1.1-2.7c0-1.1-0.4-1.9-1.1-2.7c-0.8-0.8-1.9-0.8-3.8-0.8h-7.3v7.3L125.1,395.7
			L125.1,395.7z M126.6,407.6c1.5,0,2.7-0.4,3.4-1.1c0.8-0.8,1.1-1.9,1.1-3.1c0-1.1-0.4-2.3-1.1-2.7c-0.8-0.8-1.9-1.1-3.8-1.1h-8.4
			v8.4h8.8V407.6z" />
        <path fill="#6E7071" d="M151.8,411.8c-1.9,0-3.8-0.4-5.4-1.1c-1.5-0.8-3.1-1.5-3.8-3.1c-1.1-1.1-1.9-2.7-2.3-4.2
			c-0.4-1.5-0.8-3.4-0.8-5.7c0-1.9,0.4-3.8,0.8-5.4c0.8-1.5,1.5-3.1,2.7-4.2c1.1-1.1,2.3-2.3,3.8-2.7c1.5-0.8,3.1-1.1,5-1.1
			c2.3,0,4.2,0.4,5.7,1.5c1.5,1.1,2.7,2.3,3.8,3.8c0.8,1.5,1.5,3.1,1.9,5s0.4,3.4,0.4,5h-19.9c0,1.1,0,2.3,0.4,3.4s0.8,1.9,1.5,2.7
			c0.8,0.8,1.5,1.5,2.7,1.9c1.1,0.4,2.3,0.8,3.8,0.8c1.9,0,3.4-0.4,4.6-1.1c1.1-0.8,1.9-2.3,2.3-3.8h4.2c-0.4,3.1-1.9,5.4-3.8,6.9
			C157.6,411,154.9,411.8,151.8,411.8z M159.1,395.7c0-1.1-0.4-1.9-0.8-3.1c-0.4-0.8-0.8-1.5-1.5-2.3c-0.8-0.8-1.5-1.1-2.3-1.5
			c-0.8-0.4-1.9-0.8-3.1-0.8c-1.1,0-2.3,0.4-3.1,0.8c-0.8,0.4-1.5,0.8-2.3,1.5c-0.8,0.8-1.1,1.5-1.5,2.3c-0.4,0.8-0.8,1.9-0.8,3.1
			H159.1z" />
        <path fill="#6E7071" d="M174.4,388.8h-9.6V385h23.3v3.8h-9.6v22.6h-4.2V388.8z" />
        <path fill="#6E7071" d="M203.1,411.8c-1.9,0-3.8-0.4-5.4-1.1c-1.5-0.8-3.1-1.5-3.8-3.1c-1.1-1.1-1.9-2.7-2.3-4.2
			c-0.4-1.5-0.8-3.4-0.8-5.4c0-1.9,0.4-3.8,0.8-5.4c0.4-1.5,1.5-3.1,2.3-4.2c1.1-1.1,2.3-2.3,3.8-3.1c1.5-0.8,3.4-1.1,5.4-1.1
			s3.8,0.4,5.4,1.1c1.5,0.8,3.1,1.5,4.2,3.1c1.1,1.1,1.9,2.7,2.3,4.2c0.4,1.5,0.8,3.4,0.8,5.4c0,1.9-0.4,3.8-0.8,5.4
			c-0.4,1.5-1.5,3.1-2.3,4.2c-1.1,1.1-2.3,2.3-4.2,3.1C206.9,411.4,205,411.8,203.1,411.8z M203.1,407.9c1.1,0,2.3-0.4,3.1-0.8
			c1.1-0.4,1.9-1.1,2.7-1.9c0.8-0.8,1.1-1.9,1.9-3.1c0.4-1.1,0.8-2.7,0.8-4.2c0-1.5-0.4-3.1-0.8-4.2c-0.4-1.1-1.1-2.3-1.9-3.1
			c-0.8-0.8-1.5-1.5-2.7-1.9c-1.1-0.4-1.9-0.8-3.1-0.8c-1.1,0-2.3,0.4-3.1,0.8c-1.1,0.4-1.9,1.1-2.7,1.9c-0.8,0.8-1.5,1.9-1.9,3.1
			c-0.4,1.1-0.8,2.7-0.8,4.2c0,1.5,0.4,3.1,0.8,4.2c0.4,1.1,1.1,2.3,1.9,3.1c0.8,0.8,1.5,1.5,2.7,1.9
			C200.8,407.9,201.9,407.9,203.1,407.9z" />
        <path fill="#6E7071" d="M218,407.6h3.1c0.4-0.8,0.8-1.5,1.1-3.1c0.4-1.1,0.8-2.7,1.1-4.2c0.4-1.5,0.8-3.1,0.8-5
			c0.4-1.5,0.4-3.4,0.4-5v-5.7h19.1v22.6h3.4V419h-4.2v-8h-21v8H218V407.6z M239,407.6v-18.7h-10.3v2.3c0,1.5,0,3.4-0.4,5
			c-0.4,1.5-0.4,3.1-0.8,4.6c-0.4,1.5-0.8,2.7-1.1,3.8c-0.4,1.1-0.8,2.3-1.1,2.7H239V407.6z" />
        <path fill="#6E7071" d="M250.9,385h4.2v21.4l12.6-21.4h5.7v26.4h-4.2V390l-12.6,21.4h-5.7V385z" />
        <path fill="#6E7071" d="M291.1,411.8c-2.3,0-3.8-0.4-5.4-1.1c-1.5-0.8-3.1-1.5-3.8-3.1c-1.1-1.1-1.9-2.7-2.3-4.2
			c-0.4-1.5-0.8-3.4-0.8-5.4c0-1.9,0.4-3.8,0.8-5.4c0.4-1.5,1.5-3.1,2.3-4.2c1.1-1.1,2.3-2.3,3.8-3.1c1.5-0.8,3.4-1.1,5.4-1.1
			s3.8,0.4,5.4,1.1c1.5,0.8,3.1,1.5,4.2,3.1c1.1,1.1,1.9,2.7,2.3,4.2c0.4,1.5,0.8,3.4,0.8,5.4c0,1.9-0.4,3.8-0.8,5.4
			c-0.4,1.5-1.5,3.1-2.3,4.2c-1.1,1.1-2.3,2.3-4.2,3.1C294.9,411.4,293.4,411.8,291.1,411.8z M291.1,407.9c1.1,0,2.3-0.4,3.1-0.8
			c1.1-0.4,1.9-1.1,2.7-1.9c0.8-0.8,1.1-1.9,1.9-3.1c0.4-1.1,0.8-2.7,0.8-4.2c0-1.5-0.4-3.1-0.8-4.2c-0.4-1.1-1.1-2.3-1.9-3.1
			c-0.8-0.8-1.5-1.5-2.7-1.9c-1.1-0.4-1.9-0.8-3.1-0.8c-1.1,0-2.3,0.4-3.1,0.8c-1.1,0.4-1.9,1.1-2.7,1.9c-0.8,0.8-1.5,1.9-1.9,3.1
			s-0.4,2.7-0.4,4.2c0,1.5,0.4,3.1,0.8,4.2c0.4,1.1,1.1,2.3,1.9,3.1c0.8,0.8,1.5,1.5,2.7,1.9C288.8,407.9,289.9,407.9,291.1,407.9z" />
        <path fill="#6E7071" d="M306,407.6h3.1c0.4-0.8,0.8-1.5,1.1-3.1c0.4-1.1,0.8-2.7,1.1-4.2s0.8-3.1,0.8-5c0.4-1.5,0.4-3.4,0.4-5
			v-5.7h19.1v22.6h3.4V419h-4.2v-8h-20.7v8H306V407.6z M327,407.6v-18.7h-10.3v2.3c0,1.5,0,3.4-0.4,5c0,1.5-0.4,3.1-0.8,4.6
			c-0.4,1.5-0.8,2.7-1.1,3.8c-0.4,1.1-0.8,2.3-1.1,2.7H327V407.6z" />
        <path fill="#6E7071" d="M338.9,385h4.2v10.3h13.4V385h4.2v26.4h-4.2v-12.2h-13.4v12.2h-4.2V385z" />
        <path fill="#6E7071" d="M367.6,385h4.2v9.9h8c2.7,0,4.6,0.8,6.1,2.3c1.5,1.5,2.3,3.4,2.3,6.1c0,2.3-0.8,4.6-2.3,6.1
			s-3.4,2.3-6.1,2.3h-12.6V385H367.6z M378.6,407.6c3.4,0,5.4-1.5,5.4-4.2c0-3.1-1.9-4.2-5.4-4.2h-6.9v8.8h6.9V407.6z M392.8,385
			h4.2v26.4h-4.2V385z" />
        <path fill="#6E7071" d="M415,411.8c-2.3,0-3.8-0.4-5.7-1.1c-1.5-0.8-3.1-1.5-3.8-3.1c-1.1-1.1-1.9-2.7-2.3-4.2
			c-0.4-1.5-0.8-3.4-0.8-5.7c0-1.9,0.4-3.8,0.8-5.4c0.8-1.5,1.5-3.1,2.7-4.2c1.1-1.1,2.3-2.3,3.8-2.7c1.5-0.8,3.1-1.1,5-1.1
			c2.3,0,4.2,0.4,5.7,1.5s2.7,2.3,3.8,3.8c0.8,1.5,1.5,3.1,1.9,5c0.4,1.9,0.4,3.4,0.4,5h-19.5c0,1.1,0,2.3,0.4,3.4
			c0.4,1.1,0.8,1.9,1.5,2.7c0.8,0.8,1.5,1.5,2.7,1.9s2.3,0.8,3.8,0.8c1.9,0,3.4-0.4,4.6-1.1c1.1-0.8,1.9-2.3,2.3-3.8h4.2
			c-0.8,3.1-1.9,5.4-3.8,6.9C420.3,411,418,411.8,415,411.8z M421.9,395.7c0-1.1-0.4-1.9-0.8-3.1c-0.4-0.8-0.8-1.5-1.5-2.3
			c-0.8-0.8-1.5-1.1-2.3-1.5c-0.8-0.4-1.9-0.8-3.1-0.8s-2.3,0.4-3.1,0.8c-0.8,0.4-1.5,0.8-2.3,1.5c-0.8,0.8-1.1,1.5-1.5,2.3
			c-0.4,0.8-0.8,1.9-0.8,3.1H421.9z" />
        <path fill="#6E7071" d="M455.9,411.8c-1.9,0-3.8-0.4-5.4-1.1s-2.7-1.5-3.8-2.7c-1.1-1.1-1.9-2.7-2.3-4.2c-0.4-1.5-0.8-3.4-0.8-5.4
			s0.4-3.8,0.8-5.4c0.4-1.5,1.1-3.1,2.3-4.6c1.1-1.1,2.3-2.3,3.8-3.1c1.5-0.8,3.4-1.1,5.4-1.1c1.5,0,3.1,0,4.2,0.4
			c1.1,0.4,2.3,0.8,3.4,1.5s1.9,1.5,2.3,2.7c0.8,1.1,1.1,2.7,1.1,4.2h-4.6c-0.4-1.5-1.1-3.1-2.3-3.8c-1.1-0.8-2.7-1.5-4.2-1.5
			s-2.7,0.4-3.8,0.8c-1.1,0.8-1.9,1.5-2.7,2.3c-0.8,0.8-1.1,1.9-1.5,3.4c-0.4,1.1-0.4,2.7-0.4,3.8c0,1.1,0,2.3,0.4,3.4
			c0.4,1.1,0.8,2.3,1.1,3.1c0.8,0.8,1.5,1.5,2.3,2.3c1.1,0.4,2.3,0.8,3.4,0.8c2.3,0,3.8-0.4,5-1.5c1.1-1.1,1.9-2.7,2.3-4.6h4.6
			c-0.4,3.4-1.5,5.7-3.4,7.6C462,411,459.3,411.8,455.9,411.8z" />
        <path fill="#6E7071" d="M472.4,385h4.2v21.4l12.6-21.4h5.4v26.4h-4.2V390l-12.6,21.4H472V385H472.4z" />
        <path fill="#6E7071" d="M512.1,411.8c-1.9,0-3.8-0.4-5.4-1.1c-1.5-0.8-2.7-1.5-3.8-2.7c-1.1-1.1-1.9-2.7-2.3-4.2
			c-0.4-1.5-0.8-3.4-0.8-5.4s0.4-3.8,0.8-5.4c0.4-1.5,1.1-3.1,2.3-4.6c1.1-1.1,2.3-2.3,3.8-3.1c1.5-0.8,3.4-1.1,5.4-1.1
			c1.5,0,3.1,0,4.2,0.4c1.1,0.4,2.3,0.8,3.4,1.5s1.9,1.5,2.3,2.7c0.8,1.1,1.1,2.7,1.1,4.2h-4.6c-0.4-1.5-1.1-3.1-2.3-3.8
			c-1.1-0.8-2.7-1.5-4.2-1.5c-1.5,0-3.1,0.4-3.8,0.8c-1.1,0.8-1.9,1.5-2.7,2.3c-0.8,0.8-1.1,1.9-1.5,3.4c-0.4,1.1-0.4,2.7-0.4,3.8
			c0,1.1,0,2.3,0.4,3.4c0.4,1.1,0.8,2.3,1.5,3.1s1.5,1.5,2.3,2.3c1.1,0.4,2.3,0.8,3.4,0.8c2.3,0,3.8-0.4,5-1.5
			c1.1-1.1,1.9-2.7,2.3-4.6h4.6c-0.4,3.4-1.5,5.7-3.4,7.6C518.2,411,515.6,411.8,512.1,411.8z" />
        <path fill="#6E7071" d="M535.1,388.8h-9.6V385h23.3v3.8h-9.6v22.6h-4.2V388.8z" />
        <path fill="#6E7071" d="M563.4,411.8c-1.9,0-3.8-0.4-5.4-1.1c-1.5-0.8-3.1-1.5-3.8-3.1c-1.1-1.1-1.9-2.7-2.3-4.2
			c-0.4-1.5-0.8-3.4-0.8-5.7c0-1.9,0.4-3.8,0.8-5.4c0.8-1.5,1.5-3.1,2.7-4.2c1.1-1.1,2.3-2.3,3.8-2.7c1.5-0.8,3.1-1.1,5-1.1
			c2.3,0,4.2,0.4,5.7,1.5c1.5,1.1,2.7,2.3,3.8,3.8c0.8,1.5,1.5,3.1,1.9,5c0.4,1.9,0.4,3.4,0.4,5h-19.9c0,1.1,0,2.3,0.4,3.4
			s0.8,1.9,1.5,2.7s1.5,1.5,2.7,1.9c1.1,0.4,2.3,0.8,3.8,0.8c1.9,0,3.4-0.4,4.6-1.1c1.1-0.8,1.9-2.3,2.3-3.8h4.2
			c-0.8,3.1-1.9,5.4-3.8,6.9C569.1,411,566.4,411.8,563.4,411.8z M570.6,395.7c0-1.1-0.4-1.9-0.8-3.1c-0.4-0.8-0.8-1.5-1.5-2.3
			s-1.5-1.1-2.3-1.5c-0.8-0.4-1.9-0.8-3.1-0.8s-2.3,0.4-3.1,0.8c-0.8,0.4-1.5,0.8-2.3,1.5c-0.8,0.8-1.1,1.5-1.5,2.3
			c-0.4,0.8-0.8,1.9-0.8,3.1H570.6z" />
        <path fill="#6E7071" d="M579.8,385h6.1l8,21.4l0,0l8-21.4h6.1v26.4h-4.2v-21l-8,21h-3.8l-8-21v21h-4.2V385z" />
        <path fill="#6E7071" d="M614.6,385h4.2v9.9h8c2.7,0,4.6,0.8,6.1,2.3c1.5,1.5,2.3,3.4,2.3,6.1c0,2.3-0.8,4.6-2.3,6.1
			s-3.4,2.3-6.1,2.3h-12.6V385H614.6z M625.7,407.6c3.8,0,5.4-1.5,5.4-4.2c0-3.1-1.9-4.2-5.4-4.2h-6.9v8.8h6.9V407.6z M639.9,385
			h4.2v26.4h-4.2V385z" />
    </g>
    <path fill="#D0D434" d="M196.6,320.4c-5.4,0-9.9-1.5-13-4.6c-3.1-3.1-5-8-5-14.9c-5.7,6.9-12.6,11.9-20.3,14.9
		c-7.6,3.1-16.1,4.6-24.9,4.6c-5.7,0-11.1-0.8-16.4-1.9c-5-1.1-9.6-3.4-13.4-6.1c-3.8-2.7-6.9-6.5-9.2-11.1
		c-2.3-4.6-3.4-9.9-3.4-16.4c0-7.3,1.1-13.4,3.8-18c2.7-4.6,5.7-8.4,9.9-11.5c4.2-3.1,8.8-5,13.8-6.5c5.4-1.5,10.7-2.7,16.1-3.8
		c5.7-1.1,11.1-1.9,16.4-2.7c5.4-0.8,9.9-1.5,13.8-2.3c3.8-1.1,6.9-2.7,9.6-4.6c2.3-1.9,3.4-5,3.4-9.2c0-4.6-0.8-8.4-2.7-11.1
		c-1.9-2.7-3.8-5-6.9-6.5c-2.7-1.5-5.7-2.3-9.2-3.1c-3.4-0.4-6.9-0.8-9.9-0.8c-8.8,0-16.4,1.5-22.2,5c-6.1,3.4-9.2,9.9-9.6,19.1h-21
		c0.4-8,1.9-14.5,5-19.9c3.1-5.4,6.9-9.9,11.9-13.4s10.7-5.7,17.2-7.3s13.4-2.3,20.3-2.3c5.7,0,11.5,0.4,17.2,1.1
		c5.7,0.8,10.7,2.7,15.3,5c4.6,2.7,8.4,6.1,11.1,10.7c2.7,4.6,4.2,10.7,4.2,18v65.8c0,5,0.4,8.4,0.8,11.1c0.8,2.3,2.7,3.4,5.7,3.4
		c1.9,0,3.8-0.4,6.5-1.1v17.2C208.1,319.6,203.1,320.4,196.6,320.4z M167.1,256.1c-4.2,0.8-8.8,1.5-13.4,2.3
		c-4.6,0.8-9.6,1.1-14.2,1.9c-5,0.8-9.2,1.9-13,3.4c-3.8,1.5-6.9,3.8-9.2,6.9s-3.4,7.3-3.4,12.6c0,3.4,0.8,6.5,1.9,8.8
		c1.5,2.3,3.1,4.2,5.4,5.7c2.3,1.5,5,2.7,8,3.1c3.1,0.8,6.1,1.1,9.2,1.1c6.9,0,13-0.8,18-2.7c5-1.9,8.8-4.2,12.2-7.3
		c3.1-3.1,5.4-6.1,6.9-9.6c1.5-3.4,2.3-6.5,2.3-9.6v-21.4C175.2,253.8,171.7,254.9,167.1,256.1z" />
    <path class="b-logo-icon__scrolled-hidden" fill="#6E7071" d="M246.3,141v176.7h-21V141H246.3z" />
    <path class="b-logo-icon__scrolled-hidden" fill="#6E7071" d="M361.4,309.6c-9.6,7.3-21.8,11.1-36.3,11.1c-10.3,0-19.1-1.5-26.8-5c-7.6-3.4-13.8-8-19.1-13.8
		c-5-6.1-8.8-13-11.5-21.4s-3.8-17.2-4.2-27.2c0-9.6,1.5-18.7,4.6-26.8c3.1-8,7.3-14.9,12.6-21c5.4-6.1,11.9-10.7,19.1-13.8
		c7.3-3.4,15.3-5,24.1-5c11.5,0,21,2.3,28.3,6.9c7.6,4.6,13.4,10.7,18,18c4.6,7.3,7.6,15.3,9.6,23.7c1.5,8.4,2.3,16.8,1.9,24.5
		h-95.6c0,5.7,0.4,11.1,1.9,16.1s3.8,9.6,7.3,13.4s7.6,6.9,12.6,9.2c5,2.3,11.1,3.4,18,3.4c8.8,0,16.1-1.9,21.8-6.1
		c5.7-4.2,9.6-10.3,11.1-18.7h20.7C377.1,291.7,371,302.4,361.4,309.6z M356.5,227.4c-1.9-4.6-4.6-8.4-7.6-11.5
		c-3.1-3.1-6.9-5.7-11.5-7.6c-4.2-1.9-9.2-2.7-14.5-2.7s-10.3,1.1-14.9,2.7c-4.2,1.9-8,4.6-11.1,7.6c-3.1,3.4-5.7,7.3-7.3,11.5
		c-1.9,4.2-3.1,9.2-3.1,14.2h73.1C359.5,236.6,358.4,232,356.5,227.4z" />
    <path class="b-logo-icon__scrolled-hidden" fill="#6E7071" d="M495.3,317.7v-17.2h-0.4c-3.4,7.3-8.8,12.2-16.4,15.3c-7.3,3.1-15.7,4.6-24.5,4.6c-9.9,0-18.4-1.9-26-5.4
		c-7.3-3.8-13.4-8.4-18.4-14.5c-5-6.1-8.4-13-11.1-21.4c-2.7-8-3.8-16.8-3.8-25.6c0-9.2,1.1-17.6,3.4-25.6c2.3-8,6.1-15.3,10.7-21
		c5-6.1,11.1-10.7,18.4-14.5c7.3-3.4,16.1-5.4,25.6-5.4c3.4,0,6.9,0.4,10.7,1.1s7.6,1.9,11.5,3.4s7.3,3.4,10.7,6.1
		c3.4,2.7,6.1,5.7,8.4,9.6h0.4V141h21v176.7L495.3,317.7L495.3,317.7z M419.6,272.2c1.5,5.7,3.8,10.7,7.3,15.3
		c3.1,4.6,7.3,8,12.2,10.7c5,2.7,11.1,3.8,17.6,3.8c7.3,0,13-1.5,18-4.2s9.2-6.5,12.2-11.1c3.1-4.6,5.4-9.6,6.9-15.3
		c1.5-5.7,1.9-11.5,1.9-17.6c0-6.1-0.8-12.2-2.3-18.4c-1.5-5.7-3.8-11.1-6.9-15.3c-3.1-4.6-7.3-8-12.6-10.7
		c-5-2.7-11.5-4.2-18.7-4.2s-13,1.5-18,4.2c-5,2.7-8.8,6.5-11.9,11.1c-3.1,4.6-5,9.9-6.5,15.7c-1.1,6.1-1.9,12.2-1.9,18.4
		C417.3,260.7,418,266.8,419.6,272.2z" />
    <path class="b-logo-icon__scrolled-hidden" fill="#6E7071" d="M533.5,227.4c2.7-8,6.5-15.3,11.9-21.4c5.4-6.1,11.9-10.7,19.5-14.2s16.8-5.4,26.8-5.4
		c10.3,0,19.1,1.9,26.8,5.4c7.6,3.4,14.2,8,19.5,14.2c5.4,6.1,9.2,13,11.9,21.4c2.7,8,3.8,16.8,3.8,26.4c0,9.6-1.1,18-3.8,26.4
		c-2.7,8-6.5,15.3-11.9,21c-5.4,6.1-11.9,10.7-19.5,14.2c-7.6,3.4-16.4,5-26.8,5c-9.9,0-19.1-1.5-26.8-5s-14.2-8-19.5-14.2
		c-5.4-6.1-9.2-13-11.9-21c-2.7-8-3.8-16.8-3.8-26.4C529.7,244.6,530.9,235.8,533.5,227.4z M555,274.5c1.9,6.1,5,11.1,8.4,15.3
		c3.4,4.2,8,7.3,12.6,9.2c5,2.3,9.9,3.1,15.3,3.1c5.4,0,10.7-1.1,15.3-3.1c5-2.3,9.2-5.4,12.6-9.2c3.4-4.2,6.5-9.2,8.4-15.3
		s3.1-13,3.1-20.7c0-7.6-1.1-14.5-3.1-20.7s-5-11.1-8.4-15.3c-3.4-4.2-8-7.3-12.6-9.6c-5-2.3-9.9-3.1-15.3-3.1
		c-5.4,0-10.7,1.1-15.3,3.1c-5,2.3-9.2,5.4-12.6,9.6c-3.8,4.2-6.5,9.2-8.4,15.3s-3.1,13-3.1,20.7C551.9,261.8,553.1,268.7,555,274.5
		z" />
    <path class="b-logo-icon__scrolled-visible" fill="#CBCC2C" d="M239.4,230.6c-9.6,0-17.5-7.8-17.5-17.5c0-9.6,7.8-17.5,17.5-17.5c9.6,0,17.5,7.8,17.5,17.5
		C256.9,222.7,249.1,230.6,239.4,230.6 M239.4,199.4c-7.5,0-13.7,6.1-13.7,13.6c0,7.5,6.1,13.7,13.7,13.7c7.5,0,13.6-6.1,13.6-13.7
		C253.1,205.6,247,199.4,239.4,199.4" />
    <path class="b-logo-icon__scrolled-visible" fill="#CBCC2C" d="M304.8,230.6c-9.6,0-17.5-7.8-17.5-17.5c0-9.6,7.8-17.5,17.5-17.5s17.5,7.8,17.5,17.5
		C322.3,222.7,314.4,230.6,304.8,230.6 M304.8,199.4c-7.5,0-13.7,6.1-13.7,13.6c0,7.5,6.1,13.7,13.7,13.7c7.5,0,13.7-6.1,13.7-13.7
		C318.4,205.6,312.3,199.4,304.8,199.4" />
    <path class="b-logo-icon__scrolled-visible" fill="#CBCC2C" d="M370.1,230.6c-9.6,0-17.5-7.8-17.5-17.5c0-9.6,7.8-17.5,17.5-17.5c9.6,0,17.5,7.8,17.5,17.5
		C387.6,222.7,379.8,230.6,370.1,230.6 M370.1,199.4c-7.5,0-13.6,6.1-13.6,13.6c0,7.5,6.1,13.7,13.6,13.7c7.5,0,13.7-6.1,13.7-13.7
		C383.8,205.6,377.7,199.4,370.1,199.4" />
    <path class="b-logo-icon__scrolled-visible" fill="#CBCC2C" d="M435.5,229.6c-9.6,0-17.5-7.8-17.5-17.5c0-9.6,7.9-17.5,17.5-17.5c9.6,0,17.5,7.8,17.5,17.5
		C453,221.7,445.1,229.6,435.5,229.6 M435.5,198.4c-7.5,0-13.7,6.1-13.7,13.6c0,7.5,6.1,13.7,13.7,13.7c7.5,0,13.6-6.1,13.6-13.7
		C449.2,204.6,443,198.4,435.5,198.4" />
    <path fill="#D0D434" d="M25.2,230.6c-11.5,0-20.7-9.2-20.7-20.7s9.2-20.7,20.7-20.7s20.7,9.2,20.7,20.7S36.7,230.6,25.2,230.6z
		 M25.2,197.3c-6.9,0-12.6,5.7-12.6,12.6s5.7,12.6,12.6,12.6s12.6-5.7,12.6-12.6S32.1,197.3,25.2,197.3z" />
    <path class="b-logo-icon__scrolled-hidden" fill="#6E7071" d="M727.5,229.7c-10.3,0-18.7-8.4-18.7-18.7s8.4-18.7,18.7-18.7s18.7,8.4,18.7,18.7
		C745.8,221.3,737.8,229.7,727.5,229.7z M727.5,196.4c-8,0-14.5,6.5-14.5,14.5s6.5,14.5,14.5,14.5S742,219,742,211
		C742,202.9,735.5,196.4,727.5,196.4z" />
    <path class="b-logo-icon__scrolled-hidden" fill="#6E7071" d="M797.1,229.7c-10.3,0-18.7-8.4-18.7-18.7s8.4-18.7,18.7-18.7c10.3,0,18.7,8.4,18.7,18.7
		C815.8,221.3,807.4,229.7,797.1,229.7z M797.1,196.4c-8,0-14.5,6.5-14.5,14.5s6.5,14.5,14.5,14.5c8,0,14.5-6.5,14.5-14.5
		C811.6,202.9,805.1,196.4,797.1,196.4z" />
    <path class="b-logo-icon__scrolled-hidden" fill="#6E7071" d="M866.7,229.7c-10.3,0-18.7-8.4-18.7-18.7s8.4-18.7,18.7-18.7c10.3,0,18.7,8.4,18.7,18.7
		S877,229.7,866.7,229.7z M866.7,196.4c-8,0-14.5,6.5-14.5,14.5s6.5,14.5,14.5,14.5c8,0,14.5-6.5,14.5-14.5
		C881.2,202.9,874.7,196.4,866.7,196.4z" />
    <path class="b-logo-icon__scrolled-hidden" fill="#6E7071" d="M936.7,228.7c-10.3,0-18.7-8.4-18.7-18.7s8.4-18.7,18.7-18.7c10.3,0,18.7,8.4,18.7,18.7
		C955,220.3,946.6,228.7,936.7,228.7z M936.7,195.4c-8,0-14.5,6.5-14.5,14.5s6.5,14.5,14.5,14.5c8,0,14.5-6.5,14.5-14.5
		C951.2,201.9,944.7,195.4,936.7,195.4z" />
</g>
</svg>

                </a>
            </div>
            <div class="b-header-top-section__right">
                <div class="b-header-top-section__we-work hidden-xs hidden-sm">
                    <ul class="b-header-top-section__list list-unstyled b-right">
                        <li class="b-header-top-section__list-item b-header-top-section__we-work__list-item" style="text-align: right">

                        </li>

                        <li class="b-header-top-section__list-item b-header-top-section__we-work__list-item">
                            <? /** @var $user \ZfcUser\Entity\User */ ?>
                            <? if ($user = $this->zfcUserIdentity()) { ?>
                                Привет, <?= $user->getUsername() ?>!
                            <? } ?>
                        </li>
                    </ul>
                </div>
                <ul class="b-header-top-section__list list-unstyled b-right">
                    <li class="b-header-top-section__list-item hidden-xs" style="text-align: right">
                        <a href="/info/" class="b-highlighted-link b-header-top-section__link b-header-top-section__link_about-company <?= ($active=='info' && $action=='index') ? 'b-header-top-section__link-active' : ''?>">О компании</a><br class=" visible-sm-block visible-xs-block" />
                        <a href="/partners/" class="b-highlighted-link b-header-top-section__link <?= $active=='partners' ? 'b-header-top-section__link-active' : ''?>">Партнерам</a>
                        <? if ($isManager && $godModeId && $godModeName) { ?>
                            <div style="font-size: 1.1rem;">
                            <span style="color: #666; padding-left: 10px; padding-top: 5px; line-height: 20px; display: inline-block;">
                                Пользователь номер <?= $godModeId ?><br />(<?= $godModeName ?>) <br />
                            </span>

                            <a class="pull-right" style="color: #666; padding-top: 5px; line-height: 20px; display: inline-block" href="/cabinet/godModeOff">[Отмена]</a>
                            </div>
                        <? } ?>
                    </li>

                        <li class="b-header-top-section__list-item  hidden-xs" style="border-right: none">
                            <? if ($user = $this->zfcUserIdentity()){ ?>
                                <a href="/cabinet/" class="b-highlighted-link b-header-top-section__link">Личный кабинет</a><br />
                            <? } else { ?>
                                <a href="javascript:void(0)" id="auth_block_trigger" class="b-highlighted-link b-header-top-section__link">Войти</a><br />
                            <? } ?>
                            <a href="/cart/"  class="main-cart b-highlighted-link b-header-top-section__link cart-empty">Корзина&nbsp;<span class="main-cart-badge">(<span class="main-cart-val"></span>)</span></a>
                        </li>

                    <li class="b-header-top-section__list-item b-header-top-section__list-item_mobile">
                        <span href="javascript:void(0)" class="b-header-top-section__link b-header-top-section__we-work__list-item">Работаем по всей РФ</span><br />
                        <a href="javascript:void(0)" class="b-header-top-section__link link_tel">8 (800) 555 56 72</a>
                    </li>

                    <li class="b-header-top-section__list-item  b-header-top-section__list-item_mobile">
                        <!-- javascript:void(0) -->
                        <a href="callto:+78124485849" class="b-header-top-section__link link_tel">8 (812) 448 58 49 <span style="color: a5a5a5">СПБ</span></a><br />
                        <a href="tel:+74997032442" class="b-header-top-section__link link_tel">8 (499) 703 24 42 <span style="color: a5a5a5">МСК</span></a>
                    </li>
                </ul>


            </div>
        </div>
    </div>

    <? if (\User\Service\UserService::$commercialMode) { ?>
        <aledo-commercial-prods-data style="display: none"><?= $_COOKIE['prodscommercial'] ?></aledo-commercial-prods-data>
    <? } ?>
	
	
  <div class="visible-xs b-mobile-nav" ng-mobile-nav>
    <a href="javascript:void(0)" class="b-mobile-nav__trigger" >МЕНЮ
    <span class="b-menu-icon  b-mobile-nav__menu-icon">
        <i class="b-menu-icon__line b-menu-icon__line_t"></i>
    <i class="b-menu-icon__line b-menu-icon__line_c"></i>
    <i class="b-menu-icon__line b-menu-icon__line_b"></i>
    </span>
      </a>
    <ul class="b-mobile-nav-list list-unstyled">
      <li class="b-mobile-nav-list__list-item b-mobile-search" ng-mobile-search>
        <div class="b-mobile-search__inner">
         
                <form name="search" method="get" role="search" action="<?= $this->url('search'); ?>">
                <!--<div class="b-mobile-search__input-wrapper">
                 
                  </div>-->
                   <div class="b-mobile-search__cell">
             <input  name="search" type="text" class="b-mobile-search__input"  placeholder="НАЧНИТЕ ПОИСК ПРОДУКЦИИ"/>
          </div>
          <div class="b-mobile-search__cell b-mobile-search__cell_r">
            <a class="b-mobile-search__trigger" href="javascript:void(0)"><!-- --></a>
          </div>
                 
                  </form>
         
        </div>
       
      </li>
      <li class="b-mobile-nav-list__list-item">
        <a  class="b-mobile-nav-list__link b-highlighted-link b-highlighted-link_mobile-nav-link<?= $active=='catalog' ? 'b-mobile-nav-list__link_active' : ''?>" href="/catalog/">Каталог</a>
      </li>
      <li class="b-mobile-nav-list__list-item">
        <a  class="b-mobile-nav-list__link b-highlighted-link b-highlighted-link_mobile-nav-link  <?= $active=='projects' ? 'b-mobile-nav-list__link_active' : ''?>" href="/projects/">Проекты</a>
      </li>
      <li class="b-mobile-nav-list__list-item">
        <a class="b-mobile-nav-list__link b-highlighted-link b-highlighted-link_mobile-nav-link  <?= $active=='solutions' ? 'b-mobile-nav-list__link_active' : ''?>" href="/solutions/">Решения</a>
      </li>
      <li class="b-mobile-nav-list__list-item">
        <a class="b-mobile-nav-list__link b-highlighted-link  b-highlighted-link_mobile-nav-link <?= ($active=='info' && $action=='delivery') ? 'b-mobile-nav-list__link_active' : ''?>" href="/info/delivery">Доставка и оплата</a>
      </li>
      <li class="b-mobile-nav-list__list-item">
        <a  class="b-mobile-nav-list__link b-highlighted-link b-highlighted-link_mobile-nav-link <?= ($active=='blog' || $active=='article') ? 'b-mobile-nav-list__link_active' : ''?>" href="/blog/">Блог</a>
      </li>
      <li class="b-mobile-nav-list__list-item">
        <a  class="b-mobile-nav-list__link b-highlighted-link b-highlighted-link_mobile-nav-link <?= $active=='contacts' ? 'b-mobile-nav-list__link_active' : ''?>" href="/contacts/">Контакты</a>
      </li>
	   <li class="b-mobile-nav-list__list-item">
        <a  class="b-mobile-nav-list__link b-highlighted-link b-highlighted-link_mobile-nav-link <?= ($active=='info' && $action=='index') ? 'b-mobile-nav-list__link_active' : ''?>" href="/info/">О компании</a>
      </li>
	     <li class="b-mobile-nav-list__list-item">
        <a  class="b-mobile-nav-list__link b-highlighted-link b-highlighted-link_mobile-nav-link <?= ($active=='partners') ? 'b-mobile-nav-list__link_active' : ''?>" href="/partners/">Партнерам</a>
      </li>
	  
	  
      <li class="b-mobile-nav-list__list-item">
        <? if ($user = $this->zfcUserIdentity()){ ?>
                  
           
      <a href="/cabinet/" class="b-mobile-nav-list__link b-highlighted-link  b-highlighted-link_mobile-nav-link">Личный кабинет</a>
     
      <? } else { ?>
                                
      <a href="#mobile_header_anchor" id="auth_block_trigger" class="b-mobile-nav-list__link b-highlighted-link b-highlighted-link_mobile-nav-link">Войти</a>
      
      <? } ?>
           
      </li>
      <li class="b-mobile-nav-list__list-item">
        <a href="/cart/"  class="main-cart b-mobile-nav-list__link cart-empty  b-highlighted-link  b-highlighted-link_mobile-nav-link">
          Корзина&nbsp;<span class="main-cart-badge">
            (<span class="main-cart-val"></span>)
          </span>
        </a>
      </li>
    </ul>

  </div>
	
    <div class="b-header-bottom-section hidden-xs">
        <div class="b-section__content">
            <ul class="b-main-navigation list-unstyled">
                <li class="b-main-navigation__list-item">
                    <a class="b-main-navigation__link b-left <?= $active=='catalog' ? 'b-main-navigation__link-active' : ''?>" href="/catalog/">Каталог</a>
                </li>
                <li class="b-main-navigation__list-item">
                    <a class="b-main-navigation__link b-left <?= $active=='projects' ? 'b-main-navigation__link-active' : ''?>" href="/projects/">Проекты</a>
                </li>
                <li class="b-main-navigation__list-item">
                    <a class="b-main-navigation__link b-left <?= $active=='solutions' ? 'b-main-navigation__link-active' : ''?>" href="/solutions/">Решения</a>
                </li>


                <li class="b-main-navigation__list-item">
                    <a class="b-main-navigation__link b-main-navigation__link_payment b-left <?= ($active=='info' && $action=='delivery') ? 'b-main-navigation__link-active' : ''?>" href="/info/delivery">Доставка и оплата</a>
                </li>

                <li class="b-main-navigation__list-item">
                    <a class="b-main-navigation__link b-main-blog <?= ($active=='blog' || $active=='articles') ? 'b-main-navigation__link-active' : ''?>" href="/blog/">Блог</a>
                </li>
                <li class="b-main-navigation__list-item b-main-navigation__list-item_contacts">
                    <a class="b-main-navigation__link b-right <?= $active=='contacts' ? 'b-main-navigation__link-active' : ''?>" href="/contacts/">Контакты</a>
                </li>
                <li class="b-main-navigation__list-item b-clearfix">
                    <a class="b-main-navigation__link b-search-button b-right"></a>
                </li>
            </ul>
            <div class="b-search">
                <form name="search" method="get" role="search" action="<?= $this->url('search'); ?>">
                    <div class="b-placeholdered-input b-placeholdered-input_search b-search__input-outer">
                        <label for="search" class="b-placeholdered-input__label">Начните поиск продукции</label>
                        <input id="search" name="search" type="text" class="b-search__input b-placeholdered-input__input" />
                    </div>
                    <input type="submit" style="display:none"/>
                </form>
            </div>

        </div>

    </div>
    <?php  if($isCart){ ?>
        <div class="b-cart-header">

            <div class="b-section__content">
                <div class="b-breadcrumbs">
                    <? foreach ($breadCrumbs as $bc) { ?>
                        <a class="b-breadcrumbs__item" href="<?= $bc['link'] ?>"><?= $bc['text'] ?></a>&nbsp;/
                    <? } ?>
                    <strong class="b-breadcrumbs__item b-breadcrumbs__item_active"><?= $pageTitle ?></strong>
                </div>
            </div>
            <div class="b-section__content">
                <table cellpadding="0" cellspacing="0" border="0" class="b-cart-table">
                    <colgroup>
                        <col style="width:16rem;"/>
                        <col style="width:10rem;" />
                        <col style="width:100%" />
                        <col style="width:7.5rem;" />
                        <col style="width:10.8rem;" />
                        <col style="width:10.8rem;" />
                        <col style="width:1.3rem;" />
                    </colgroup>
                    <tr>
                        <th class="b-cart-header-cell b-cart-product-cell  b-cart-product-cell_image">
                            <div class="b-cart-product-cell_image__inner">Продукт</div>
                        </th>
                        <th class="b-cart-header-cell b-cart-product-cell  b-cart-product-cell_article">
                            <div class="b-cart-product-cell_article__inner">Артикул</div>
                        </th>
                        <th class="b-cart-header-cell b-cart-product-cell  b-cart-product-cell_title">Наименование</th>
                        <th class="b-cart-header-cell b-cart-product-cell  b-cart-product-cell_price">
                            <div class="b-cart-product-cell_price__inner">Цена</div>
                        </th>
                        <th class="b-cart-header-cell b-cart-product-cell  b-cart-product-cell_count">
                            <div class="b-cart-product-cell_count__inner">Кол-во</div>
                        </th>
                        <th class="b-cart-header-cell b-cart-product-cell  b-cart-product-cell_result-price">
                            <div class="b-cart-product-cell_result-price__inner">
                                Стоимость
                            </div>
                        </th>
                        <td class="b-cart-header-cell b-cart-product-cell  b-cart-product-cell_delete">
                            <div class="b-cart-product-cell_delete__inner">
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    <?php } ?>



</header>