<script src="/Scripts/apps/Registration.js"></script>
<div class="modal fade " id="registration_modal" tabindex="-1">
    <div class="modal-dialog b-registration-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="javascript:void" class="close" data-dismiss="modal"><span>×</span></a>
                <h4 class="modal-title text-center"><strong>РЕГИСТРАЦИЯ</strong></h4>
            </div>
            <div class="modal-body">
                <div class="b-registration">
                    <form novalidate name="registration" ng-controller="RegistrationController">
                        <div>
                            <div class="b-registration__cell b-registration__cell_left">
                                <label for="user_name">Имя*</label>
                            </div>
                            <div class="b-registration__cell b-registration__cell_right">
                                <input type="text" class="b-form-control b-form-control_small" id="user_name" ng-model="user_name" autocomplete="off" required />
                            </div>
                        </div>
                        <div>
                            <div class="b-registration__cell b-registration__cell_left">
                                <label for="user_tel">Контактный телефон*</label>
                            </div>
                            <div class="b-registration__cell b-registration__cell_right">
                                <input type="text" class="b-form-control b-form-control_small" id="user_tel" ng-model="user_tel" autocomplete="off" required />
                            </div>
                        </div>
                        <div>
                            <div class="b-registration__cell b-registration__cell_left">
                                <label for="user_email">E-mail*</label>
                            </div>
                            <div class="b-registration__cell b-registration__cell_right">
                                <input type="text" class="b-form-control b-form-control_small" id="user_email" ng-model="user_email" autocomplete="off" required />
                            </div>
                        </div>

                        <div class="b-registration__table">
                            <div class="b-registration__row">
                                <div class="b-registration__cell b-registration__cell_left">
                                    <label for="user_password">Пароль*</label>
                                </div>
                                <div class="b-registration__cell b-registration__cell_right">
                                    <input type="password" class="b-form-control b-form-control_small" id="user_cur_password" ng-model="user_cur_password" autocomplete="off" required />
                                </div>
                            </div>
                            <div class="b-registration__row">
                                <div class="b-registration__cell b-registration__cell_left">
                                    <label for="user_password_repeat">Повторите пароль*</label>
                                </div>
                                <div class="b-registration__cell b-registration__cell_right">
                                    <input type="password" class="b-form-control b-form-control_small" id="user_password_repeat" ng-model="user_password_repeat" autocomplete="off" required />
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <button class="b-button b-button_gray" id="registration_button" ng-disabled="registration.$invalid">
                                <span class="b-button__text">
                                    СОХРАНИТЬ ПЕРСОНАЛЬНЫЕ ДАННЫЕ
                                </span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
