
<div class="col-xs-12" >
    <div class="equal-block-name equal-block" style="padding-top: 0; float: left; padding-left: 0">
        <h3 style="font-size: 2.4rem; margin: 0; margin-top: 13px;"><?= $series->visible_title ?></h3>
    </div>

    <? foreach($equalParameters as $field=>$val){
        if(!in_array($field, $shownEqualParams)){ continue; }
        ?>
        <div class="equal-block dotted-left" >
            <p class="text-grey" style="font-size: 13px"><?= isset($params[$field]) ? $params[$field]->title : $field ?></p>
            <h3 <?= preg_match('[(\d)+]', $val) ? 'style="text-transform: none"' : '' ?>><?= isset($params[$field]) ? $params[$field]->pre_value . ' ' . $val.' '.$params[$field]->post_value : $val; ?></h3>

        </div>
    <? } ?>

</div>