<div class="modal fade " id="catalog_mobile_redirect" tabindex="-1">
    <div class="modal-dialog b-mobile-redirect-dialog">

        <div class="b-mobile-redirect-dialog__content">

            <a class="b-mobile-redirect-dialog__link">Смотреть товар</a>
            на полной версии сайта

        </div>
    </div>
</div>
<script type="text/javascript">
    (function () {
        jQuery("#catalog_mobile_redirect").on("show.bs.modal", function (e) {
            var $target = jQuery(e.relatedTarget),
                href = $target.data("href"),
                $link = jQuery(".b-mobile-redirect-dialog__link");
            $link.attr("href", href);
        });
    })()
</script>