<?
$hierarchies = $this->hierarchies;
$discounts = $this->discounts;

$fields = array('id', 'title', 'file_custom', 'controller_type', 'power', 'i_out', 'u_out', 'warranty', 'free_balance', 'price_without_nds', 'price_with_nds', 'length', 'is_offer');
$filteredFields = array('power', 'i_out', 'u_out', 'warranty');
if ($user && $user->getIsPartner()) {
    $fields[] = 'partner_price';
}

$posVals = \Catalog\Service\CatalogService::getValsJSON($products, $filteredFields, 0, $params);
$isDriver = (reset($products)->type == 'Драйвер тока');
$products = \Catalog\Service\CatalogService::getProductsJSON($products, $fields, $user, $series, $hierarchies, $discounts, $filteredFields, $isDriver);

?>



<solo-table make-sortable="3" ng-init="setDriver(<?= $isDriver ? 'true' : 'false' ?>)">

<div solo-table-data>
    [<?= $products ?>]
</div>
<div solo-table-header-data>
    [
    {
    "name": "id",
    "label": "Артикул"
    },
    {
    "name": "title",
    "label": "Наименование"
    },
    {
    "name": "file_custom",
    "label": ""
    },
    {
    "name": "controller_type",
    "label": "Габариты",
    "measures": ""
    },
    {
    "name": "power",
    "label": "Мощность",
    "measures": "Вт"
    },
    <? if ($isDriver) {  ?>
    {
    "name": "i_out",
    "label": "Выходной ток",
    "measures": "А"
    },
    <? } else { ?>
    {
    "name": "u_out",
    "label": "Выходное напряжение",
    "measures": "В"
    },
    <? } ?>
    {
    "name": "warranty",
    "label": "Гарантия"
    },
    {
    "name": "free_balance",
    "label": "Наличие"
    },
    {
    "name": "price_with_nds",
    "label": "Цена"
    }
    <? if ($user && $user->getIsPartner()) { ?>
        ,
        {
        "name": "partner_price",
        "label": "Ваша цена"
        }
    <? } ?>
    ]
</div>
<div solo-table-pos-vals>
    <?= $posVals ?>
</div>
    <div class="row" style="margin-bottom: 10px">
        <div class="col-md-12">
            <span style="font-weight: bold">Цены на предлагаемую продукцию зависят от курса у.е.</span>
        </div>
    </div>

<? include 'series-filter-angular.phtml'; ?>

<table class="table table-hover table-aledo table-products" id="table-products_<?= $serNum ?>" style="width: 100%;">
    <thead>
    <tr>
        <th class="{{th.name}}-header" ng-repeat="th in ths = tds" sort-by='{{th.name}}'>{{th.label}}</th>
        <th class="buy-item-header"></th>
        <th class="copy-link-header"></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <tr
        itemscope
        itemtype="http://schema.org/Product"
        ng-repeat="item in filtered = (original | possibleVals:possibleVals:this | instock:instock:this | offers:offers:this)"
        ng-class="{selectedProd: item.id == selectedProdId, productIncart: elCarto[item.id]==1 }"
        class="item product-line"
        data-id="{{item.id}}"
        <? if (!$nonFilter) { ?>
        ng-show="item.id != 162461"
        <? } ?>
        >
        <!--        <tr itemscope itemtype="http://schema.org/Product"-->
        <!--            class="item product-line --><?//= $this->selectedProdId == $prod->id ? 'selectedProd' : ''?><!--"-->
        <!--            data-id="--><?//= $prod->id; ?><!--">-->
        <td itemprop="productID" class="td-grey item-id">{{item.id}}</td>
        <td itemprop="name" class="item-title">{{item.title}}</td>
        <td class="file_custom">
            <div ng-show="item.file_custom">
                <a href="/images/product_docs/{{item.file_custom}}"
                   target="_blank"
                   ng-click="ga('send', 'event', 'button', 'click', 'download', '{{item.file_custom}}');">
                    <span ng-init="type=item.file_custom.substr(-3, 3).toLowerCase()" class="icon-download icon-{{type}}"></span>
                </a>
            </div>
        </td>

        <td class="controller_type">{{item.controller_type}}</td>
        <td class="power">{{item.power}}
            <span ng-if="!substr(item.i_out, 'Вт')"> Вт</span>
        </td>
        <td class="td-grey <?= $isDriver ? 'i_out' : 'u_out'?>">
            {{item.<?= $isDriver ? 'i_out' : 'u_out' ?>}}
            <? if ($isDriver) { ?>
            <span ng-if="!substr(item.i_out, 'А')"> А</span>
            <? } else { ?>
            <span ng-if="!substr(item.u_out, 'В')"> В</span>
            <? } ?>
        </td>
        <td class="warranty">{{item.warranty}} {{getYearForm(item.warranty)}}</td>
            <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                <td class="td-grey free_balance">
                    <div ng-if="item.free_balance">
                        <span ng-if="item.free_balance == -1">
                            <div class="icon-daw"></div><link itemprop="availability" href="http://schema.org/InStock"/>
                        </span>
                        <span ng-if="item.free_balance > 0">
                            {{item.free_balance}}
                        </span>

                    </div>
                    <div ng-if="item.free_balance == 0">
                        <div title="Уточняйте наличие" class="icon-question"></div><link itemprop="availability" href="http://schema.org/OutOfStock"/>
                    </div>
                </td>

                <td class="price-with-nds">
                    <span itemprop="price">
                        {{item.price_with_nds}}
                    </span>
                    <span>
                        <span class="b-rub">Р</span>
                    </span>
                </td>

                <? if ($user && $user->getIsPartner()) { ?>
                    <td class="td-grey partner-price">
                    <span itemprop="price">
                        {{item.partner_price}}
                    </span>
                    <span ng-if="item.length > 0">
                        <span class="b-rub">Р</span>/м
                    </span>
                    <span ng-if="item.length == 0">
                        <span class="b-rub">Р</span>
                    </span>
                    </td>
                <? } ?>
            </span>
        <!--                <td class="td-grey"></td>-->
        <td class="but-item">
            <a class="buy-btn" title="купить модель" ng-click="addItemToCart(item.id)">
                <span class="buy-arrow"></span>
                    <span class="buy-body">
                        <span class="buy-on">купить</span>
                    </span>
            </a>
            <a href="<?= $this->url('cart') ?>" class="buy-to-cart" title="модель помещена в корзину">в корзине</a>
        </td>
        <td class="copy-link">
            <!--                --><?// if(in_array($prod->id, $offeredIds)){ ?>
            <span ng-if="false">
                    <div class="icon-discount"></div>
                </span>
            <!--                --><?// } ?>

            <a class="getlink-btn">
                <div class="icon-getlink zeroclipboard"
                     data-clipboard-text="http://<?=\Application\Service\MailService::CURRENT_DOMEN?>/catalog/product/{{item.id}}/"></div>
            </a>
            <a class="buy-back-btn" ng-click="removeItemFromCart(item.id)" title="убрать из корзины"><div class="icon-whitecross"></div></a>

        </td>
        <td style="padding: 0">
                <span ng-show="item.is_offer">
                    <div class="icon-offer"></div>
                </span>
        </td>
    </tr>
    </tbody>
</table>
</solo-table>

<script>

</script>