<? 
$hierarchies = $this->hierarchies;
$discounts = $this->discounts;

foreach($products as $product) { 
	$price = \Catalog\Service\CatalogService::getRegularPriceWithNds($product, true, $hierarchies, $this->requests); 
?>
	<div itemscope itemtype="http://schema.org/Product" style="display:none;">
		<meta itemprop="productID" content="<?= $product->id ?>" />
        <meta itemprop="name" content="<?= $product->title ?>" />
		<div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
			<meta itemprop="availability" content="<?= $product->free_balance > 0 ? 'http://schema.org/InStock' : 'http://schema.org/OutOfStock' ?>" />
			<meta itemprop="price" content="<?= $price ?>" />
			<meta itemprop="priceCurrency" content="RUB" />
		</div>
	</div>
<? } ?>

<?
$fields = array('id', 'title', 'file_custom', 'electro_power', 'color_of_light', 'luminous_flux', 'power', 'free_balance', 'price_without_nds', 'price_with_nds', 'length', 'is_offer', 'is_price_requestable');
$filteredFields = array('electro_power', 'color_of_light', 'luminous_flux', 'power');
if ($user && $user->getIsPartner()) {
    $fields[] = 'partner_price';
}

$posVals = \Catalog\Service\CatalogService::getValsJSON($products, $filteredFields, $prevProdCount, $params, true);
$products = \Catalog\Service\CatalogService::getProductsJSON($products, $fields, $user, $series, $hierarchies, $discounts, $filteredFields, true, true, $this->requests);

?>


<solo-table ng-cloak>
    <div solo-table-data style="display: none;">
        [<?= $products ?>]
    </div>
    <div solo-table-header-data style="display: none;">
        [
        {
        "name": "id",
        "label": "Артикул"
        },
        {
        "name": "title",
        "label": "Наименование"
        },
        {
        "name": "file_custom",
        "label": ""
        },
        {
        "name": "electro_power",
        "label": "Питание",
        "measures": ""
        },
        {
        "name": "color_of_light",
        "label": "Цвет свечения",
        "measures": ""
        },
        {
        "name": "luminous_flux",
        "label": "Световой поток",
        "measures": "лм/м"
        },
        {
        "name": "power",
        "label": "Мощность",
        "measures": "Вт/м"
        },
        {
        "name": "free_balance",
        "label": "Наличие",
        "measures": ""
        },
        {
        "name": "price_with_nds",
        "label": "Цена",
        "measures": ""
        }
    <? if ($user && $user->getIsPartner()) { ?>
        ,
        {
        "name": "partner_price",
        "label": "Ваша цена"
        }
    <? } ?>
        ]
    </div>
    <div solo-table-pos-vals style="display: none;">
        <?= $posVals ?>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <span style="font-weight: bold">Цены на предлагаемую продукцию зависят от курса у.е.</span>
        </div>
    </div>
    <? include 'series-filter-angular.phtml'; ?>
<table class="table table-hover table-aledo table-products" id="table-products_<?= $serNum ?>" style="width: 100%;">
    <thead>
    <tr>
        <th class="{{th.name}}-header" ng-repeat="th in ths = tds" sort-by='{{th.name}}'><span ng-bind="th.label"></span></th>
        <th class="buy-item-header"></th>
        <th class="copy-link-header"></th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
        <tr ng-repeat="item in filtered = (original | possibleVals:possibleVals:this | instock:instock:this | offers:offers:this)"
            ng-class="{selectedProd: item.id == selectedProdId<?= !$this->commercialMode ? ', productIncart: elCarto[item.id]==1' : '' ?>}"
            class="item product-line product-line"
            data-id="{{item.id}}"
            >
<!--        <tr-->
<!--            class="item product-line --><?//= $this->selectedProdId == $prod->id ? 'selectedProd' : ''?><!--"-->
<!--            data-id="--><?//= $prod->id; ?><!--">-->
            <td class="td-grey item-id">{{item.id}}</td>
            <td class="item-title">{{item.title}}</td>
            <td class="file_custom">
                <div ng-show="item.file_custom">
                <a href="/images/product_docs/{{item.file_custom}}"
                   target="_blank"
                   ng-click="ga('send', 'event', 'button', 'click', 'download', '{{item.file_custom}}');">
                    <span ng-init="type=item.file_custom.substr(-3, 3).toLowerCase()" class="icon-download icon-{{type}}"></span>
                </a>
                </div>
            </td>

            <td class="electro-power">{{item.electro_power}}</td>
            <td class="color-of-light">{{item.color_of_light}}</td>
            <td class="td-grey luminous-flux">
                <span ng-if="item.luminous_flux">
                {{item.luminous_flux}}<span ng-if="!(item.luminous_flux.indexOf('лм') + 1)"> лм</span>
                </span>
                <span ng-if="!item.luminous_flux">-</span>
            </td>
            <td class="power">{{item.power}} Вт/м</td>
                <td class="td-grey free_balance">
                    <div ng-if="item.free_balance">
                        <span ng-if="item.free_balance == -1">
                            <div class="icon-daw"></div>
                        </span>
                        <span ng-if="item.free_balance > 0">
                            {{item.free_balance}}
                        </span>

                    </div>
                    <div ng-if="item.free_balance == 0">
                        <div title="Уточняйте наличие" class="icon-question"></div>
                    </div>
                </td>

                <td class="price-with-nds">
					<span ng-if="item.is_price_requestable == 0">
						<span>
							{{item.price_with_nds}}
						</span>
						<span ng-if="item.length > 0">
							<span class="b-rub">Р</span>/м
						</span>
						<span ng-if="item.length == 0">
							<span class="b-rub">Р</span>
						</span>
					</span>
					<div class="b-price-requestable" ng-if="item.is_price_requestable == 1">по<br>запросу</div>
                </td>

                <? if ($user && $user->getIsPartner()) { ?>
                <td class="td-grey partner-price">
					<span ng-if="item.is_price_requestable == 0">
						<span>
							{{item.partner_price}}
						</span>
						<span ng-if="item.length > 0">
							<span class="b-rub">Р</span>/м
						</span>
						<span ng-if="item.length == 0">
							<span class="b-rub">Р</span>
						</span>
					</span>
					<div class="b-price-requestable" ng-if="item.is_price_requestable == 1">по<br>запросу</div>
                </td>
                <? } ?>
            <!--                <td class="td-grey"></td>-->
            <? if ($this->commercialMode) { ?>
                <td class="comm-item" style="cursor: pointer" ng-controller="CommercialsController">

                    <a class="comm-btn"  title="добавить в КП" ng-show="!checkProdInRoom(item.id)" ng-click="prodAPI.add(item.id)">
                        <span class="buy-arrow"></span>
                    <span class="buy-body">
                        <span class="buy-on">в КП</span>
                    </span>
                    </a>
                    <a href="/cabinet/?c=<?=  \User\Service\UserService::$commercialId  ?>&r=<?=  \User\Service\UserService::$roomId ?>#offers_1" style="font-size: 10px;font-weight: bold;text-decoration: underline;text-transform: uppercase;" ng-show="checkProdInRoom(item.id)" title="модель помещена в КП">в КП</a>
                </td>
            <? } else { ?>
                <td class="but-item">
                    <a class="buy-btn" title="купить модель" ng-click="addItemToCart(item.id)">
                        <span class="buy-arrow"></span>
                        <span class="buy-body">
                            <span class="buy-on">купить</span>
                        </span>
                    </a>
                    <a href="<?= $this->url('cart') ?>" class="buy-to-cart" title="модель помещена в корзину">в корзине</a>
                </td>
            <? } ?>
            <td class="copy-link" style="padding-left: 5px;">

                <a class="getlink-btn">
                    <div class="icon-getlink zeroclipboard"
                         title="Скопировать ссылку в буфер обмена"
                         data-clipboard-text="http://<?=\Application\Service\MailService::CURRENT_DOMEN?>/catalog/product/{{item.id}}/<?= $nonFilter ? '?ser=' . $parentSerNum . ($partialTab ? $partialTab : '') : '' ?>"></div>
                </a>
<!--                <a class="buy-back-btn" ng-click="removeItemFromCart(item.id)" title="убрать из корзины"><div class="icon-whitecross"></div></a>-->


            </td>

            <td style="padding: 0; padding-left: 5px;">
                <span ng-show="item.is_offer">
                    <div class="icon-offer" title="Распродажа"></div>
                </span>
            </td>

            <td style="padding: 0; padding-left: 5px;">
                <a class="buy-back-btn" ng-click="removeItemFromCart(item.id)" title="убрать из корзины"><div class="icon-whitecross"></div></a>
            </td>
        </tr>
    </tbody>
</table>

</solo-table>