<?
$hierarchies = $this->hierarchies;
$discounts = $this->discounts;
$fields = array('id', 'title', 'file_custom', 'free_balance', 'price_without_nds', 'price_with_nds', 'is_offer');
$filteredFields = array();
if ($user && $user->getIsPartner()) {
    $fields[] = 'partner_price';
}

$posVals = \Catalog\Service\CatalogService::getValsJSON($products, $filteredFields, $prevProdCount, $params);

$products = \Catalog\Service\CatalogService::getProductsJSON($products, $fields, $user, \Catalog\Service\CatalogService::DISPLAY_STYLE_LENTS, $hierarchies, $discounts, $filteredFields, true, false);
$partialTab = $this->partialTab ? $this->partialTab : false;
?>



<solo-table ng-cloak>
    <div solo-table-data style="display: none;">
        [<?= $products ?>]
    </div>
    <div solo-table-header-data style="display: none;">
        [
        {
        "name": "id",
        "label": "Артикул"
        },
        {
        "name": "title",
        "label": "Наименование"
        },
        {
        "name": "file_custom",
        "label": "Изображение"
        },
        {
        "name": "free_balance",
        "label": "Наличие"
        },
        {
        "name": "price_with_nds",
        "label": "Цена"
        }
        <? if ($user && $user->getIsPartner()) { ?>
            ,
            {
            "name": "partner_price",
            "label": "Ваша цена"
            }
        <? } ?>
        ]
    </div>
    <div solo-table-pos-vals style="display: none;">
        <?= $posVals ?>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <span style="font-weight: bold">Цены на предлагаемую продукцию зависят от курса у.е.</span>
        </div>
    </div>
<!--    --><?// include 'series-filter-angular.phtml'; ?>

    <table class="table table-hover table-aledo table-products" id="table-products_<?= $serNum ?>" style="margin-top: 10px; width: 100%;">
        <thead>
        <tr>
            <th class="{{th.name}}-header" ng-repeat="th in ths = tds" sort-by='{{th.name}}'>{{th.label}}</th>
            <th class="buy-item-header"></th>
            <th class="copy-link-header"></th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr
            itemscope
            itemtype="http://schema.org/Product"
            ng-repeat="item in filtered = (original | possibleVals:possibleVals:this | instock:instock:this | offers:offers:this)"
            ng-class="{selectedProd: item.id == selectedProdId<?= !$this->commercialMode ? ', productIncart: elCarto[item.id]==1' : '' ?>}"

            class="item product-line"
            data-id="{{item.id}}"
            class="product-line"
            >
            <!--        <tr itemscope itemtype="http://schema.org/Product"-->
            <!--            class="item product-line --><?//= $this->selectedProdId == $prod->id ? 'selectedProd' : ''?><!--"-->
            <!--            data-id="--><?//= $prod->id; ?><!--">-->
            <td itemprop="productID" class="td-grey item-id">{{item.id}}</td>
            <td itemprop="name" class="item-title">{{item.title}}</td>
            <td class="file_custom">

                <div ng-show="item.file_custom">
                    <a href="/images/product_docs/{{item.file_custom}}"
                       class="profile-image-fancybox"
                       ng-click="ga('send', 'event', 'button', 'click', 'download', '{{item.file_custom}}');">
                        <span class="icon-download icon-photo"></span><span class="icon-title">ФОТО</span>
                    </a>
                </div>
            </td>
            <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                <td class="td-grey free_balance">
                    <div ng-if="item.free_balance">
                        <span ng-if="item.free_balance == -1">
                            <div class="icon-daw"></div><link itemprop="availability" href="http://schema.org/InStock"/>
                        </span>
                        <span ng-if="item.free_balance > 0">
                            {{item.free_balance}}
                        </span>

                    </div>
                    <div ng-if="item.free_balance == 0">
                        <div title="Уточняйте наличие" class="icon-question"></div><link itemprop="availability" href="http://schema.org/OutOfStock"/>
                    </div>
                </td>

                <td class="price-with-nds">
                    <span itemprop="price">
                        {{item.price_with_nds}}
                    </span>
                    <span>
                        <span class="b-rub">Р</span>
                    </span>
                </td>

                <? if ($user && $user->getIsPartner()) { ?>
                    <td class="td-grey partner-price">
                    <span itemprop="price">
                        {{item.partner_price}}
                    </span>
                    <span>
                        <span class="b-rub">Р</span>
                    </span>
                    </td>
                <? } ?>
            </span>
            <? if ($this->commercialMode) { ?>
                <td class="comm-item" style="cursor: pointer" ng-controller="CommercialsController">

                    <a class="comm-btn"  title="добавить в КП" ng-show="!checkProdInRoom(item.id)" ng-click="prodAPI.add(item.id)">
                        <span class="buy-arrow"></span>
                    <span class="buy-body">
                        <span class="buy-on">в КП</span>
                    </span>
                    </a>
                    <a href="/cabinet/?c=<?=  \User\Service\UserService::$commercialId  ?>&r=<?=  \User\Service\UserService::$roomId ?>#offers_1" style="font-size: 10px;font-weight: bold;text-decoration: underline;text-transform: uppercase;" ng-show="checkProdInRoom(item.id)" title="модель помещена в КП">в КП</a>
                </td>
            <? } else { ?>
            <td class="but-item">
                <a class="buy-btn" title="купить модель" ng-click="addItemToCart(item.id)">
                    <span class="buy-arrow"></span>
                    <span class="buy-body">
                        <span class="buy-on">купить</span>
                    </span>
                </a>
                <a href="<?= $this->url('cart') ?>" class="buy-to-cart" title="модель помещена в корзину">в корзине</a>
            </td>
            <? } ?>
            <td class="copy-link" style="padding-left: 5px;">
                <span ng-if="false">
                    <div class="icon-discount"></div>
                </span>

                <a class="getlink-btn">
                    <div class="icon-getlink zeroclipboard"
                         title="Скопировать ссылку в буфер обмена"
                         data-clipboard-text="http://<?= \Application\Service\MailService::CURRENT_DOMEN ?>/catalog/product/{{item.id}}/<?= $nonFilter ? '?ser=' . $parentSerNum . ($partialTab ? $partialTab : '') : '' ?>"></div>
                </a>
<!--                <a class="buy-back-btn" ng-click="removeItemFromCart(item.id)" title="убрать из корзины"><div class="icon-whitecross"></div></a>-->
<!--                <span ng-show="item.is_offer > 0">-->
<!--                    <div class="icon-offer"></div>-->
<!--                </span>-->
            </td>
            <td style="padding: 0; padding-left: 5px;">
                <span ng-show="item.is_offer">
                    <div class="icon-offer" title="Распродажа"></div>
                </span>
            </td>

            <td style="padding: 0; padding-left: 5px;">
                <a class="buy-back-btn" ng-click="removeItemFromCart(item.id)" title="убрать из корзины"><div class="icon-whitecross"></div></a>
            </td>
        </tr>
        </tbody>
    </table>
</solo-table>

<script>
$(function() {
    $(".profile-image-fancybox").fancybox({
        overlayShow	:	false,
        minWidth     : 400,
        maxWidth     : 800,
        padding: 0,
        helpers: {
            overlay: {
                locked: false
            }
        }
    });
});

</script>