<?
    $hierarchies = $this->hierarchies;
    $discounts = $this->discounts;
    $fields = array('id', 'title', 'file_custom', 'case_color', 'color_of_light', 'luminous_flux', 'viewing_angle', 'free_balance', 'price_without_nds', 'price_with_nds', 'length', 'is_offer');
    $filteredFields = array('case_color', 'color_of_light', 'luminous_flux', 'viewing_angle');
    if ($user && $user->getIsPartner()) {
        $fields[] = 'partner_price';
    }

    $posVals = \Catalog\Service\CatalogService::getValsJSON($products, $filteredFields, $prevProdCount, $params);

    $products = \Catalog\Service\CatalogService::getProductsJSON($products, $fields, $user, $series, $hierarchies, $discounts, $filteredFields, true);

?>


<solo-table make-sortable="3"  ng-cloak>
    <div solo-table-data style="display: none;">
        [<?= $products ?>]
    </div>
    <div solo-table-header-data style="display: none;">
        [
        {
        "id":0,
        "name": "id",
        "label": "Артикул"
        },
        {
        "id":1,
        "name": "title",
        "label": "Наименование"
        },
        {
        "id":2,
        "name": "file_custom",
        "label": ""
        },
        {
        "id":3,
        "name": "case_color",
        "label": "Цвет корпуса",
        "measures": ""
        },
        {
        "id":4,
        "name": "color_of_light",
        "label": "Цвет свечения",
        "measures": ""
        },
        {
        "id":5,
        "name": "luminous_flux",
        "label": "Световой поток",
        "measures": "лм/м"
        },
        {
        "id":6,
        "name": "viewing_angle",
        "label": "Угол пучка",
        "measures": "°"
        },
        {
        "id":7,
        "name": "free_balance",
        "label": "Наличие",
        "measures": "шт."
        },
        {
        "id":8,
        "name": "price_with_nds",
        "label": "Цена",
        "measures": ""
        }
        <? if ($user && $user->getIsPartner()) { ?>
            ,
            {
            "name": "partner_price",
            "label": "Ваша цена"
            }
        <? } ?>
        ]
    </div>
    <div solo-table-pos-vals style="display: none;">
        <?= $posVals ?>
    </div>
    <? include 'series-filter-angular.phtml'; ?>
    <div class="row">
        <div class="col-xs-12">
            <span style="font-weight: bold">Цены на предлагаемую продукцию зависят от курса у.е.</span>
        </div>
    </div>
    <table class="table table-hover table-aledo table-products" id="table-products_<?= $serNum ?>" style="width: 100%;">
        <thead>
        <tr ng-init="printScopeId(tds)">
            <th class="{{th.name}}-header" ng-repeat="(key, th) in tds" sort-by='{{th.name}}'>{{th.label}}</th>
            <th class="buy-item-header"></th>
            <th class="copy-link-header"></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr
            itemscope
            itemtype="http://schema.org/Product"
            ng-repeat="item in filtered = (original | possibleVals:possibleVals:this | instock:instock:this | offers:offers:this)"

            ng-class="{selectedProd: item.id == selectedProdId, productIncart: elCarto[item.id]==1 }"

            class="item product-line"
            data-id="{{item.id}}">
            <!--        <tr itemscope itemtype="http://schema.org/Product"-->
            <!--            class="item product-line --><?//= $this->selectedProdId == $prod->id ? 'selectedProd' : ''?><!--"-->
            <!--            data-id="--><?//= $prod->id; ?><!--">-->
            <td itemprop="productID" class="item-id">{{item.id}}</td>
            <td itemprop="name" class="item-title">{{item.title}}</td>
            <td class="file_custom">
                <div ng-show="item.file_custom">
                    <a href="/images/product_docs/{{item.file_custom}}"
                       target="_blank"
                       ng-click="ga('send', 'event', 'button', 'click', 'download', '{{item.file_custom}}');">
                        <span ng-init="type=item.file_custom.substr(-3, 3).toLowerCase()" class="icon-download icon-{{type}}"></span>
                    </a>
                </div>
            </td>

            <td class="case_color">{{item.case_color}}</td>
            <td class="color_of_light">{{item.color_of_light}}</td>
            <td class="td-grey luminous_flux">{{item.luminous_flux}} лм<span ng-if="!(item.luminous_flux.indexOf('лм') + 1)">лм</span></td>
            <td class="viewing_angle">{{item.viewing_angle}}°</td>
            <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                <td class="td-grey free_balance" style="padding: 0">
                    <div ng-if="item.free_balance">
                        <span ng-if="item.free_balance == -1">
                            <div class="icon-daw"></div><link itemprop="availability" href="http://schema.org/InStock"/>
                        </span>
                        <span ng-if="item.free_balance > 0">
                            {{item.free_balance}}
                        </span>

                    </div>
                    <div ng-if="item.free_balance == 0">
                        <div title="Уточняйте наличие" class="icon-question"></div><link itemprop="availability" href="http://schema.org/OutOfStock"/>
                    </div>
                </td>

                <td class="price-with-nds">
                    <span itemprop="price">
                        {{item.price_with_nds}}
                    </span><span class="b-rub">Р</span>

                </td>

                <? if ($user && $user->getIsPartner()) { ?>
                    <td class="td-grey partner-price">
                    <span itemprop="price">
                        {{item.partner_price}}
                    </span>
                    <span>
                        <span class="b-rub">Р</span>
                    </span>
                    </td>
                <? } ?>
            </span>

            <td class="but-item">
                <a class="buy-btn" title="купить модель" ng-click="addItemToCart(item.id)">
                    <span class="buy-arrow"></span>
                    <span class="buy-body">
                        <span class="buy-on">купить</span>
                    </span>
                </a>
                <a href="<?= $this->url('cart') ?>" class="buy-to-cart" title="модель помещена в корзину">в корзине</a>
            </td>
            <td class="copy-link">

                <a class="getlink-btn">
                    <div class="icon-getlink zeroclipboard"
                         data-clipboard-text="http://<?=\Application\Service\MailService::CURRENT_DOMEN?>/catalog/product/{{item.id}}/"></div>
                </a>
                <a class="buy-back-btn" ng-click="removeItemFromCart(item.id)" title="убрать из корзины"><div class="icon-whitecross"></div></a>


            </td>
            <td style="padding: 0">
                <span ng-show="item.is_offer">
                    <div class="icon-offer"></div>
                </span>
            </td>
        </tr>
        </tbody>
    </table>
</solo-table>
