
<tr>
    <th>Изображение</th>
    <th>Цена</th>
    <!--                <th>Партнерская цена</th>-->
    <th style="width: 60px;"></th>
    <th style="width: 30px;"></th>
</tr>
<tr class="product-line" data-id="<?= $this->product->id; ?>" >
    <td>
        <? if($this->product->file_custom){ ?>
            <a href="<?=$this->basePath() . '/images/product_docs/' . $this->product->file_custom ?>"
               target="_blank"
               onclick="ga('send', 'event', 'button', 'click', 'download', '<?= $this->product->file_custom ?>');"
            >
                <span class="icon-download icon-photo"></span>
                <span class="icon-title">ФОТО</span>
            </a>
        <? } ?>
    </td>
    <td itemprop="offers" itemscope itemtype="http://schema.org/Offer">
        <meta itemprop="currency" content="RUB" />
        <span itemprop="seller" itemscope itemtype="http://schema.org/Organization">
                <meta itemprop="name" content="Aledo" />
                <meta itemprop="address" content="<?= strip_tags($contacts->adress) ?>" />
                <meta itemprop="telephone" content="<?= $contacts->phone?>" />
                <meta itemprop="faxNumber" content="<?= $contacts->fax ?>" />
                <meta itemprop="email" content="<?= $contacts->mail ?>" />
            </span>
        <span itemprop="price"><?= \Catalog\Service\CatalogService::getTruePrice($this->product->price_without_nds); ?></span>&nbsp;<span class="b-rub">Р</span>
    </td>
    <td>
        <a class="buy-btn">
            <span class="buy-arrow"></span>
        <span class="buy-body">
            <span class="buy-on">купить</span>
        </span>
        </a>
        <a href="<?= $this->url('cart') ?>" class="buy-to-cart">в корзине</a>
    </td>
    <td>
        <a class="buy-back-btn" title="убрать из корзины"><div class="icon-whitecross"></div></a>
    </td>
</tr>
