<?
$hierarchies = $this->hierarchies;

$discounts = $this->discounts;


$fields = array('id', 'title', 'file_custom', 'electro_power', 'color_of_light', 'luminous_flux', 'power', 'free_balance', 'price_without_nds', 'price_with_nds', 'length', 'is_offer');
$filteredFields = array('electro_power', 'color_of_light', 'luminous_flux', 'power');
if ($user && $user->getIsPartner()) {
    $fields[] = 'partner_price';
}

$posVals = \Catalog\Service\CatalogService::getValsJSON($products, $filteredFields, $prevProdCount, $params, true);

$products = \Catalog\Service\CatalogService::getProductsJSON($products, $fields, $user, $series, $hierarchies, $discounts, $filteredFields, true, true);

?>


<solo-table make-sortable="3"  ng-cloak>
    <div solo-table-data style="display: none;">
        [<?= $products ?>]
    </div>
    <div solo-table-header-data style="display: none;">
        [
        {
        "name": "id",
        "label": "Артикул"
        },
        {
        "name": "title",
        "label": "Наименование"
        },
        {
        "name": "file_custom",
        "label": ""
        },
        {
        "name": "electro_power",
        "label": "Питание",
        "measures": ""
        },
        {
        "name": "color_of_light",
        "label": "Цвет свечения",
        "measures": ""
        },
        {
        "name": "luminous_flux",
        "label": "Световой поток",
        "measures": "лм/м"
        },
        {
        "name": "power",
        "label": "Мощность",
        "measures": "Вт/м"
        },
        {
        "name": "free_balance",
        "label": "Наличие",
        "measures": ""
        },
        {
        "name": "price_with_nds",
        "label": "Цена",
        "measures": ""
        }
    <? if ($user && $user->getIsPartner()) { ?>
        ,
        {
        "name": "partner_price",
        "label": "Ваша цена"
        }
    <? } ?>
        ]
    </div>
    <div solo-table-pos-vals style="display: none;">
        <?= $posVals ?>
    </div>
    <div class="row">
        <div class="col-md-12">
            <span style="font-weight: bold">Цены на предлагаемую продукцию зависят от курса у.е.</span>
        </div>
    </div>
    <? include 'series-filter-angular.phtml'; ?>
<table class="table table-hover table-aledo table-products" id="table-products_<?= $serNum ?>" style="width: 100%;">
    <thead>
    <tr>
        <th class="{{th.name}}-header" ng-repeat="th in ths = tds" sort-by='{{th.name}}'><span ng-bind="th.label"></span></th>
        <th class="buy-item-header"></th>
        <th class="copy-link-header"></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
        <tr
            itemscope
            itemtype="http://schema.org/Product"
            ng-repeat="item in filtered = (original | possibleVals:possibleVals:this | instock:instock:this | offers:offers:this)"
            ng-class="{selectedProd: item.id == selectedProdId, productIncart: elCarto[item.id]==1 }"
            class="item product-line product-line"
            data-id="{{item.id}}"
            >
<!--        <tr itemscope itemtype="http://schema.org/Product"-->
<!--            class="item product-line --><?//= $this->selectedProdId == $prod->id ? 'selectedProd' : ''?><!--"-->
<!--            data-id="--><?//= $prod->id; ?><!--">-->
            <td itemprop="productID" class="td-grey item-id">{{item.id}}</td>
            <td itemprop="name" class="item-title">{{item.title}}</td>
            <td class="file_custom">
                <div ng-show="item.file_custom">
                <a href="/images/product_docs/{{item.file_custom}}"
                   target="_blank"
                   ng-click="ga('send', 'event', 'button', 'click', 'download', '{{item.file_custom}}');">
                    <span ng-init="type=item.file_custom.substr(-3, 3).toLowerCase()" class="icon-download icon-{{type}}"></span>
                </a>
                </div>
            </td>

            <td class="electro-power">{{item.electro_power}}</td>
            <td class="color-of-light">{{item.color_of_light}}</td>
            <td class="td-grey luminous-flux">
                <span ng-if="item.luminous_flux">
                {{item.luminous_flux}}<span ng-if="!(item.luminous_flux.indexOf('лм') + 1)"> лм</span>
                </span>
                <span ng-if="!item.luminous_flux">-</span>
            </td>
            <td class="power">{{item.power}} Вт/м</td>
            <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                <td class="td-grey free_balance">
                    <div ng-if="item.free_balance">
                        <span ng-if="item.free_balance == -1">
                            <div class="icon-daw"></div><link itemprop="availability" href="http://schema.org/InStock"/>
                        </span>
                        <span ng-if="item.free_balance > 0">
                            {{item.free_balance}}
                        </span>

                    </div>
                    <div ng-if="item.free_balance == 0">
                        <div title="Уточняйте наличие" class="icon-question"></div><link itemprop="availability" href="http://schema.org/OutOfStock"/>
                    </div>
                </td>

                <td class="price-with-nds">
                    <span itemprop="price">
                        {{item.price_with_nds}}
                    </span>
                    <span ng-if="item.length > 0">
                        <span class="b-rub">Р</span>/м
                    </span>
                    <span ng-if="item.length == 0">
                        <span class="b-rub">Р</span>
                    </span>
                </td>

                <? if ($user && $user->getIsPartner()) { ?>
                <td class="td-grey partner-price">
                    <span itemprop="price">
                        {{item.partner_price}}
                    </span>
                    <span ng-if="item.length > 0">
                        <span class="b-rub">Р</span>/м
                    </span>
                    <span ng-if="item.length == 0">
                        <span class="b-rub">Р</span>
                    </span>
                </td>
                <? } ?>
            </span>
            <!--                <td class="td-grey"></td>-->
            <td class="but-item">
                <a class="buy-btn" title="купить модель" ng-click="addItemToCart(item.id)">
                    <span class="buy-arrow"></span>
                    <span class="buy-body">
                        <span class="buy-on">купить</span>
                    </span>
                </a>
                <a href="<?= $this->url('cart') ?>" class="buy-to-cart" title="модель помещена в корзину">в корзине</a>
            </td>
            <td class="copy-link">
<!--                --><?// if(in_array($prod->id, $offeredIds)){ ?>
                <span ng-if="false">
                    <div class="icon-discount"></div>
                </span>
                <!--                --><?// } ?>

                <a class="getlink-btn">
                    <div class="icon-getlink zeroclipboard"
                         data-clipboard-text="http://<?=\Application\Service\MailService::CURRENT_DOMEN?>/catalog/product/{{item.id}}/"></div>
                </a>
                <a class="buy-back-btn" ng-click="removeItemFromCart(item.id)" title="убрать из корзины"><div class="icon-whitecross"></div></a>

            </td>

            <td style="padding: 0">
                <span ng-show="item.is_offer">
                    <div class="icon-offer"></div>
                </span>
            </td>
        </tr>
    </tbody>
</table>

</solo-table>