<? $isDomainZoneBy = \Application\Service\ApplicationService::isDomainZone('by'); ?>
<h1>Документы</h1>

<? if (!$isDomainZoneBy) { ?>
<h2>Каталоги</h2>
<div id="entityMapper_catalog">
    <div ng-controller="EntitiesCtrl">
        <div nd-entities-list-data>
            <?= $catalogsJson ?>
        </div>
        <div nd-entities-list-pattern>
        {
            "title" : {
                "type" : "text",
                "default" : "",
                "label" : "Название"
            },
            "type" : {
                "type" : "hidden",
                "default" : "<?= \Documents\Model\DocumentTable::TYPE_CATALOG ?>",
                "label" : "Тип"
            }
        }
        </div>
        <div
            ng-entities-list
            parent-type="0"
            parent-id="0"
            controller="documents"
            type="<?= \Catalog\Controller\AdminController::DOCUMENT_TABLE?>"
            rights="00111"
            ></div>

        <script type="application/javascript">
            AppFactory("entityMapper_catalog", "entityMapper2", ["entitiesMapper"]);
        </script>
    </div>
</div>

<h2>Сертификаты</h2>
<div id="entityMapper_certificate">
    <div ng-controller="EntitiesCtrl">
        <div nd-entities-list-data>
            <?= $certificatesJson ?>
        </div>
        <div nd-entities-list-pattern>
            {
            "title" : {
            "type" : "text",
            "default" : "",
            "label" : "Название"
            },
            "type" : {
            "type" : "hidden",
            "default" : "<?= \Documents\Model\DocumentTable::TYPE_CERTIFICATE ?>",
            "label" : "Тип"
            }
            }
        </div>
        <div
            ng-entities-list
            parent-type="0"
            parent-id="0"
            controller="documents"
            type="<?= \Catalog\Controller\AdminController::DOCUMENT_TABLE?>"
            rights="00111"
            ></div>

        <script type="application/javascript">
            AppFactory("entityMapper_certificate", "entityMapper2", ["entitiesMapper"]);
        </script>
    </div>
</div>

<h2>Инструкции</h2>
<div id="entityMapper_instruction">
    <div ng-controller="EntitiesCtrl">
        <div nd-entities-list-data>
            <?= $instructionsJson ?>
        </div>
        <div nd-entities-list-pattern>
            {
            "title" : {
            "type" : "text",
            "default" : "",
            "label" : "Название"
            },
            "type" : {
            "type" : "hidden",
            "default" : "<?= \Documents\Model\DocumentTable::TYPE_INSTRUCTION ?>",
            "label" : "Тип"
            }
            }
        </div>
        <div
            ng-entities-list
            parent-type="0"
            parent-id="0"
            controller="documents"
            type="<?= \Catalog\Controller\AdminController::DOCUMENT_TABLE?>"
            rights="00111"
            ></div>

        <script type="application/javascript">
            AppFactory("entityMapper_instruction", "entityMapper2", ["entitiesMapper"]);
        </script>
    </div>
</div>
<? } ?>

<h2>Отзывы</h2>
<div id="entityMapper_comment">
    <div ng-controller="EntitiesCtrl">
        <div nd-entities-list-data>
            <?= $commentsJson ?>
        </div>
        <div nd-entities-list-pattern>
            {
            "title" : {
            "type" : "text",
            "default" : "",
            "label" : "Название"
            },
            "type" : {
            "type" : "hidden",
            "default" : "<?= \Documents\Model\DocumentTable::TYPE_COMMENT ?>",
            "label" : "Тип"
            }
            }
        </div>
        <div
            ng-entities-list
            parent-type="0"
            parent-id="0"
            controller="documents"
            type="<?= \Catalog\Controller\AdminController::DOCUMENT_TABLE?>"
            rights="00111"
            ></div>

        <script type="application/javascript">
            AppFactory("entityMapper_comment", "entityMapper2", ["entitiesMapper"]);
        </script>
    </div>
</div>
<!--<div class="section">-->
<!--    <h3>Список участников</h3>-->
<!--    <div class="addPanel">-->
<!--        <button type="button" class="btn btn-default" id="add-entity">Добавить участника</button>-->
<!---->
<!--        <div class="form-inline" id="adding-form" style="display: none">-->
<!--            <div class="form-group">-->
<!--                <label class="sr-only" for="inputName">Название</label>-->
<!--                <input type="text" class="form-control" id="inputName" placeholder="Введите имя..."/>-->
<!--            </div>-->
<!---->
<!--            <button type="button" class="btn btn-default" id="adding-complete">Добавить</button>-->
<!--            <button type="button" class="btn btn-default" id="adding-cancel">Отмена</button>-->
<!--        </div>-->
<!--    </div>-->
<!---->
<!--    <table class="table admin-table  table-striped">-->
<!--        <tr>-->
<!--            <th>Id</th>-->
<!--            <th>Имя</th>-->
<!--            <th>Управление</th>-->
<!--        </tr>-->
<!--        <tbody id="sortable">-->
<!--        --><?// foreach($entities as $entity){ ?>
<!--            <tr class="entity">-->
<!--                <td>--><?//= $entity->id; ?><!--</td>-->
<!--                <td>--><?//= $entity->title; ?><!--</td>-->
<!--                <td>-->
<!--                    <a href="#" class="editBtn">Редактировать</a>-->
<!--                    <a href="#" class="deleteBtn">Удалить</a>-->
<!--                </td>-->
<!--            </tr>-->
<!--        --><?// } ?>
<!--        </tbody>-->
<!--    </table>-->
<!--</div>-->

<script type="text/javascript">
    $(document).ready(function(){
        catalog.baseUrl = '<?= $this->url('zfcadmin/documents') ?>';
        catalog.editUrl = '<?= $this->url('zfcadmin/documents', array('action'=> 'view')) ?>';
        catalog.page_info_type = '<?= \Info\Service\SeoService::INDEX ?>';
        catalog.init();
    });
</script>