<table cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff" style="border-collapse:collapse; margin:0 auto">
    <tbody>
        <tr>
        <td align="center">

            <table width="600" height="200" cellpadding="0" cellspacing="0" style="margin:0 auto;font-family:'Lato',Arial,Helvetica,sans-serif;border-collapse:collapse; color:#666666">
                <tbody>
                <tr height="10">
                    <td height="10" colspan="4">
                        <p style="border-bottom: 1px dotted black"></p>
                    </td>
                </tr>
                <tr height="20">
                    <td width="20" height="20">&nbsp;</td>
                    <td width="220" height="20">
                        <p>
                            Здравствуйте, <?= $this->username ?>!
                            <br />
                            Вам были назначены следующие скидки:
                        </p>
                    </td>
                    <td height="20" align="right">
                        <table>
                            <tbody>
                            <tr>
                                <td colspan="2">
                                    <img src="http://<?= $_SERVER['HTTP_HOST'] ?>/images/aledo-logo-without-title.png" width="212" height="40" alt="Aledo <<?= $this->contacts[0]->phone ?>>" />
                                </td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td width="18">&nbsp;</td>
                                <td>
                                    <?= $this->contacts[0]->phone ?>
                                </td>
                                <td>&nbsp;</td>
                            </tr>
                            </tbody>

                        </table>
                    </td>

                    <td width="1" height="20">&nbsp;</td>
                </tr>

                <tr height="10">
                    <td height="10" colspan="4">
                        <p style="border-bottom: 1px dotted black; margin-bottom: 0"></p>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="2" bgcolor="white" align="left">
                        <? foreach ($discounts as $discount) { ?>
                            <div style="max-width: 600px; padding-top: 20px; ">
                                <? if ($discount->section_type == \Catalog\Controller\AdminController::SECTION_TABLE) {
                                    if (array_key_exists($discount->section_id, $sections)) {
                                        $path = 'http://' . $_SERVER['HTTP_HOST'] . '/catalog/section/' . $discount->section_id;


                                        if ($discount->discount) {
                                            echo '<div><a style="color: #666666; padding-left: ' .  (40 * ($discount->section_type-1)) . 'px;" href="' . $path . '"><span style="font-size: 16px; text-decoration: underline; font-weight: bold; text-transform: uppercase">' . $sections[$discount->section_id]->title . '</span></a>: <span style="float: right; font-size: 16px; color: #C8CF76; font-weight: bold">' . $discount->discount . '%</span></div>';
                                        } else {
                                            echo '<div><a style="color: #666666; padding-left: ' .  (40 * ($discount->section_type-1)) . 'px;" href="' . $path . '"><span style="font-size: 16px;  text-decoration: underline; font-weight: bold; text-transform: uppercase">' . $sections[$discount->section_id]->title . '</span></a></div>';
                                        }
                                    }
                                } elseif ($discount->section_type == \Catalog\Controller\AdminController::SUBSECTION_TABLE) {
                                    if (array_key_exists($discount->section_id, $subsections)) {
                                        $path = 'http://' . $_SERVER['HTTP_HOST'] . '/catalog/subsection/' . $discount->section_id;
                                        if ($discount->discount) {
                                            echo '<div><a style="color: #666666; padding-left: ' .  (40 * ($discount->section_type-1)) . 'px;" href="' . $path . '"><span style="font-size: 14px;  text-decoration: underline;">' . $subsections[$discount->section_id]->title . '</span></a>:  <span style="float: right; font-size: 16px; color: #C8CF76; font-weight: bold">' . $discount->discount . '%</span></div>';
                                        } else {
                                            echo '<div><a style="color: #666666; padding-left: ' .  (40 * ($discount->section_type-1)) . 'px;" href="' . $path . '"><span style="font-size: 14px;  text-decoration: underline;">' . $subsections[$discount->section_id]->title . '</span></a></div>';
                                        }
                                    }
                                } elseif ($discount->section_type == \Catalog\Controller\AdminController::SERIES_TABLE) {
                                    if (array_key_exists($discount->section_id, $series)) {
                                        $path = 'http://' . $_SERVER['HTTP_HOST'] . '/catalog/series/' . $discount->section_id;
                                        if ($discount->discount) {
                                            echo '<div><a style="color: #666666; padding-left: ' .  (40 * ($discount->section_type-1)) . 'px;" href="' . $path . '"><span style="font-size: 14px;  text-decoration: underline;">' . $series[$discount->section_id]->title . '</span></a>:  <span style="float: right; font-size: 16px; color: #C8CF76; font-weight: bold">' . $discount->discount . '%</span></div>';
                                        } else {
                                            echo '<div><a style="color: #666666; padding-left: ' .  (40 * ($discount->section_type-1)) . 'px;" href="' . $path . '"><span style="font-size: 14px;  text-decoration: underline;">' . $series[$discount->section_id]->title . '</span></a></div>';
                                        }
                                    }
                                } elseif ($discount->section_type == \Catalog\Controller\AdminController::PRODUCT_TABLE) {
                                    $path = 'http://' . $_SERVER['HTTP_HOST'] . '/catalog/product/' . $discount->section_id;
                                    if (array_key_exists($discount->section_id, $products)) {
                                       echo '<div><a style="color: #666666; padding-left: ' .  (40 * ($discount->section_type-1)) . 'px;" href="' . $path . '"><span style="font-size: 14px;  text-decoration: underline;">' . $products[$discount->section_id]->title . '</span></a>:  <span style="float: right; font-size: 16px; color: #C8CF76; font-weight: bold">' . $discount->discount . '%</span></div>';
                                    }
                                } ?>
                                <div style="border-bottom: 1px dotted black; height: 20px; margin-left: <?= 40 * ($discount->section_type-1) ?>px;"></div>
                            </div>
                        <? } ?>

                    </td>
                    <td>&nbsp;</td>
                </tr>
                </tbody></table>
        </td>
    </tr>
    </tbody></table>