<table cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff" style="border-collapse:collapse; margin:0 auto">
    <tbody>
        <tr>
        <td align="center">
            <table width="600" height="200" cellpadding="0" cellspacing="0" style="margin:0 auto;font-family:'Lato',Arial,Helvetica,sans-serif;border-collapse:collapse">
                <tbody>
                <tr height="10">
                    <td height="10" colspan="4">
                        <p style="border-bottom: 1px dotted black"></p>
                    </td>
                </tr>
                <tr height="20">
                    <td width="20" height="20">&nbsp;</td>
                    <td width="220" height="20">
                        <p>
                            Здравствуйте, <?= $this->username ?>!
                        </p>
                    </td>
                    <td height="20" align="right">
                        <table>
                            <tbody>
                            <tr>
                                <td colspan="2">
                                    <img src="http://<?= $_SERVER['HTTP_HOST'] ?>/images/aledo-logo-without-title.png" width="212" height="40" alt="Aledo <<?= $this->contacts[0]->phone ?>>" />
                                </td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td width="18">&nbsp;</td>
                                <td>
                                    <?= $this->contacts[0]->phone ?>
                                </td>
                                <td>&nbsp;</td>
                            </tr>
                            </tbody>

                        </table>
                    </td>

                    <td width="1" height="20">&nbsp;</td>
                </tr>

                <tr height="10">
                    <td height="10" colspan="4">
                        <p style="border-bottom: 1px dotted black"></p>
                    </td>
                </tr>
                <tr height="20">
                    <td height="20">&nbsp;</td>
                    <td height="20" colspan="2">
                        <p>
                            Вы запросили восстановление пароля на сайте <a href="http://<?= $_SERVER['HTTP_HOST'] ?>"><?= $_SERVER['SERVER_NAME'] ?></a>
                        </p>
                        <p>
                            Чтобы задать новый пароль для пользователя <?= $this->username ?> перейдите по ссылке:
                            <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/cabinet/rememberpassword?token=<?=$this->token?>">
                                http://<?= $_SERVER['HTTP_HOST'] ?>/cabinet/rememberpassword?token=<?=$this->token?>
                            </a>
                        </p>
                        <p>
                            Если вы не оставляли заявку на смену пароля, просто проигнорируйте данное письмо.
                        </p>
                    </td>
                    <td height="20">&nbsp;</td>
                </tr>
                <tr height="10">
                    <td height="10" colspan="4">
                        <p style="border-bottom: 1px dotted black"></p>
                    </td>
                </tr>
                <tr height="20">
                    <td height="20">&nbsp;</td>
                    <td height="20" colspan="2">
                        Спасибо, что выбрали нас!
                    </td>
                    <td height="20">&nbsp;</td>
                </tr>

                </tbody></table>
        </td>
    </tr>
    </tbody>
</table>