<table cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff" style="border-collapse:collapse; margin:0 auto">
    <tbody>
    <tr>
        <td align="center">
            <table width="600" height="200" cellpadding="0" cellspacing="0" style="margin:0 auto;font-family:'Lato',Arial,Helvetica,sans-serif;border-collapse:collapse">
                <tbody>
                <tr height="10">
                    <td height="10" colspan="4">
                        <p style="border-bottom: 1px dotted black"></p>
                    </td>
                </tr>
                <tr height="20">
                    <td width="20" height="20">&nbsp;</td>
                    <td width="220" height="20">
                        <p>
                            Здравствуйте, <?= $this->username ?>!
                            <br />
                            Номер Вашей заявки <?= $this->orderId ?>
                        </p>
                    </td>
                    <td height="20" align="right">
                        <table>
                            <tbody>
                            <tr>
                                <td colspan="2">
                                    <img src="http://<?= $_SERVER['HTTP_HOST'] ?>/images/aledo-logo-without-title.png" width="212" height="40" alt="Aledo <<?= $this->contacts[0]->phone ?>>" />
                                </td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td width="18">&nbsp;</td>
                                <td>
                                    <?= $this->contacts[0]->phone ?>
                                </td>
                                <td>&nbsp;</td>
                            </tr>
                            </tbody>

                        </table>
                    </td>

                    <td width="1" height="20">&nbsp;</td>
                </tr>

                <tr height="10">
                    <td height="10" colspan="4">
                        <p style="border-bottom: 1px dotted black"></p>
                    </td>
                </tr>
                <tr height="20">
                    <td height="20">&nbsp;</td>
                    <td height="20" colspan="2" bgcolor="white" align="left">
                        <table width="600" border="0" cellpadding="0" cellspacing="0" align="left">
                            <tbody>


                            <? foreach ($this->params as $paramKey => $oneParam) : ?>
                            <tr height="30">
                                <td width="180" style="color: #666666">
                                    <?= $paramKey ?>:
                                </td>
                                <td>
                                    <?= $oneParam ?>
                                </td>
                            </tr>
                            <? endforeach; ?>


                            <tr height="10">
                                <td height="10" colspan="4">
                                    <p style="border-bottom: 1px dotted black"></p>
                                </td>
                            </tr>
                            <? if (!empty($this->attachedFileName)) : ?>
                                <tr>
                                    <td width="180" style="color: #666666">
                                        Прикреплённый файл:
                                    </td>
                                    <td>
                                        <?= $this->attachedFileName ?>
                                    </td>
                                </tr>
                                <tr height="10">
                                    <td height="10" colspan="4">
                                        <p style="border-bottom: 1px dotted black"></p>
                                    </td>
                                </tr>
                            <? endif; ?>
                            <? if (!empty($this->comment)) : ?>
                                <tr>
                                    <td width="180" style="color: #666666">
                                        Комментарий:
                                    </td>
                                    <td>
                                        <?= $this->comment ?>
                                    </td>
                                </tr>
                            <? endif; ?>
                            </tbody>
                        </table>
                    <td>&nbsp;</td>
                </tr>
                <tr height="10">
                    <td height="10" colspan="4">
                        <p style="border-bottom: 1px dotted black"></p>
                    </td>
                </tr>
                <tr height="20">
                    <td height="20">&nbsp;</td>
                    <td height="20" colspan="2">
                        В ближайшее время наш менеджер свяжется с вами для уточнения деталей.<br />
                        Спасибо, что выбрали нас!
                    </td>
                    <td height="20">&nbsp;</td>
                </tr>

                </tbody></table>
        </td>
    </tr>
    </tbody>
</table>
