<div class="b-cabinet b-section">

    <div class="b-section__content">
        <div class="b-tabs-wrapper b-tabs-wrapper_cabinet">
            <ul class="b-tabs list-unstyled">
                <li class="b-tabs__tab ">
                    <a class="b-tabs__link  text-left" href="#orders_history" data-toggle="tab">История заказов</a>
                </li>
                <li class="b-tabs__tab">
                    <a class="b-tabs__link  text-left" href="#personal_data" data-toggle="tab">Персональные данные</a>
                </li>
                <li class="b-tabs__tab active">
                    <a class="b-tabs__link  text-left" href="#offers_1" data-toggle="tab">Коммерческие предложения</a>
                </li>
            </ul>
            <div class="b-tabs-content">
                <div class="b-tabs-content__item  b-tabs-content__item_offer fade active in" id="offers_1">


                    <table cellpadding="0" cellspacing="0" border="0" class="b-offers-table">
                        <colgroup>
                            <col style="width:50px"/>
                            <col style="width:60%"/>

                        </colgroup>
                        <tr class="b-offers-table__row">
                            <td class="b-offers-table__cell b-offers-table__cell_header-cell">
                                ID
                            </td>
                            <td class="b-offers-table__cell b-offers-table__cell_header-cell">
                                Название
                            </td>
                            <td class="b-offers-table__cell b-offers-table__cell_header-cell">
                                Дата
                            </td>
                            <td class="b-offers-table__cell b-offers-table__cell_header-cell">
                                Сумма
                            </td>
                            <td class="b-offers-table__cell b-offers-table__cell_header-cell">
                                Управление
                            </td>
                        </tr>
                        <tr class="b-offers-table__row">
                            <td colspan="6" class="b-offers-table__cell b-offers-table__cell_add-offer">
                                <a href="javascript:void(0)">Добавить коммерческое предложение</a>
                            </td>
                        </tr>
                        <tr class="b-offers-table__row">
                            <td class="b-offers-table__cell">
                                23
                            </td>
                            <td class="b-offers-table__cell ">
                                <a href="javascript:void(0)"> Коммерческое предложение для Михаила ,Коммерческое
                                    предложение для МихаилаКоммерческое предложение для Михаила Коммерческое предложение
                                    для Михаила ,Коммерческое предложение для МихаилаКоммерческое предложение для
                                    Михаила</a>
                            </td>
                            <td class="b-offers-table__cell b-offers-table__cell_date">
                                25.06.2015
                            </td>
                            <td class="b-offers-table__cell b-offers-table__cell_summ">
                                2 552 000 540 <span class="b-rub">Р</span>
                            </td>
                            <td class="b-offers-table__cell b-offers-table__cell_buttons">
                                <a class="b-button b-button_small b-offers-table__button b-offers-table__button_left ">
                                    <span class="b-button__text">Редактировать</span>
                                </a>
                                <a class="b-button b-button_small b-offers-table__button ">
                                    <span class="b-button__text">Удалить</span>
                                </a>

                            </td>
                        </tr>
                        <tr class="b-offers-table__row">
                            <td class="b-offers-table__cell">
                                56
                            </td>
                            <td class="b-offers-table__cell ">
                                <a href="javascript:void(0)"> Коммерческое предложение для Михаила ,Коммерческое
                                    предложение для МихаилаКоммерческое предложение для Михаила Коммерческое предложение
                                    для Михаила ,Коммерческое предложение для МихаилаКоммерческое предложение для
                                    Михаила</a>
                            </td>
                            <td class="b-offers-table__cell b-offers-table__cell_date">
                                25.06.2015
                            </td>
                            <td class="b-offers-table__cell b-offers-table__cell_summ">
                                2 552 000 540 <span class="b-rub">Р</span>
                            </td>
                            <td class="b-offers-table__cell b-offers-table__cell_buttons">
                                <a class="b-button b-button_small b-offers-table__button b-offers-table__button_left ">
                                    <span class="b-button__text">Редактировать</span>
                                </a>
                                <a class="b-button b-button_small b-offers-table__button ">
                                    <span class="b-button__text">Удалить</span>
                                </a>

                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="b-section__content">
        <div class="b-tabs-wrapper b-tabs-wrapper_cabinet">
            <ul class="b-tabs list-unstyled">
                <li class="b-tabs__tab ">
                    <a class="b-tabs__link  text-left" href="#orders_history" data-toggle="tab">История заказов</a>
                </li>
                <li class="b-tabs__tab">
                    <a class="b-tabs__link  text-left" href="#personal_data" data-toggle="tab">Персональные данные</a>
                </li>
                <li class="b-tabs__tab active">
                    <a class="b-tabs__link  text-left" href="#offers_2" data-toggle="tab">Коммерческие предложения</a>
                </li>
            </ul>
            <div class="b-tabs-content">
                <div class="b-tabs-content__item b-tabs-content__item_offer fade active in " id="offers_2">


                    <div class="b-offer">
                        <table class="b-offer-header-table">
                            <colgroup>
                                <col style="width: 70%"/>
                                <col style="width: 30%"/>
                            </colgroup>
                            <tr>
                                <td class="b-offer-header-table__cell">
                                    <div class="b-offer-header-table__name  b-editable-field"
                                         ng-editable-field>
                                        <div class="b-editable-field__inner">

                                            <input class=" b-editable-field__field"
                                                   value="Коммерческое предложение для Михаила">
                                            <span class="b-editable-field__hidden">Коммерческое предложение для Михаила</span>
                                        </div>

                                        <svg version="1.1" id="Слой_1" xmlns="http://www.w3.org/2000/svg"
                                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                             viewBox="0 0 21.2 19.2" enable-background="new 0 0 21.2 19.2"
                                             class="b-editable-field__icon" xml:space="preserve">
                        <path id="pensil_15_" class="b-editable-field__icon-path" fill="#CED0D1" d="M20.4,3.1l-2-2.2c-0.5-0.6-1.3-0.6-1.9-0.1L15.1,2l3.8,4.2L20.3,5
                        	C20.9,4.5,20.9,3.7,20.4,3.1z M3.2,12.7l3.8,4.2l11-9.8l-3.8-4.2L3.2,12.7z M1.4,16.1l-0.9,2.7l2.8-0.6l2.6-0.5l-3.6-4.1L1.4,16.1z"
                            />
                        </svg>

                                    </div>
                                </td>
                                <td class="b-offer-header-table__cell text-right">
                                    <div class="text-nowrap">
                                        <span class="b-offer-header-table__id">ID: 21</span>
                                        <span class="b-offer-header-table__date">Дата: 21.21.2121</span>
                                    </div>
                                </td>
                            </tr>
                        </table>
                        <h4 class="b-offer__add"><a href="javascript:void(0)">Добавить помещение в коммерческое
                                предложение</a></h4>
                    </div>


                </div>
            </div>
        </div>
    </div>
    <div class="b-section__content">
        <div class="b-tabs-wrapper b-tabs-wrapper_cabinet">
            <ul class="b-tabs list-unstyled">
                <li class="b-tabs__tab ">
                    <a class="b-tabs__link  text-left" href="#orders_history" data-toggle="tab">История заказов</a>
                </li>
                <li class="b-tabs__tab">
                    <a class="b-tabs__link  text-left" href="#personal_data" data-toggle="tab">Персональные данные</a>
                </li>
                <li class="b-tabs__tab active">
                    <a class="b-tabs__link  text-left" href="#offers_3" data-toggle="tab">Коммерческие предложения</a>
                </li>
            </ul>
            <div class="b-tabs-content">
                <div class="b-tabs-content__item b-tabs-content__item_offer fade in  active" id="offers_3">

                    <div class="b-offer">
                        <table class="b-offer-header-table">
                            <colgroup>
                                <col style="width: 70%"/>
                                <col style="width: 30%"/>
                            </colgroup>
                            <tr>
                                <td class="b-offer-header-table__cell">
                                    <div class="b-offer-header-table__name  b-editable-field"
                                         ng-editable-field>
                                        <div class="b-editable-field__inner">

                                            <input class=" b-editable-field__field"
                                                   value="Коммерческое предложение для Михаила">
                                            <span class="b-editable-field__hidden">Коммерческое предложение для Михаила</span>
                                        </div>

                                        <svg version="1.1" id="Слой_1" xmlns="http://www.w3.org/2000/svg"
                                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                             viewBox="0 0 21.2 19.2" enable-background="new 0 0 21.2 19.2"
                                             class="b-editable-field__icon" xml:space="preserve">
                        <path id="pensil_15_" class="b-editable-field__icon-path" fill="#CED0D1" d="M20.4,3.1l-2-2.2c-0.5-0.6-1.3-0.6-1.9-0.1L15.1,2l3.8,4.2L20.3,5
                        	C20.9,4.5,20.9,3.7,20.4,3.1z M3.2,12.7l3.8,4.2l11-9.8l-3.8-4.2L3.2,12.7z M1.4,16.1l-0.9,2.7l2.8-0.6l2.6-0.5l-3.6-4.1L1.4,16.1z"
                            />
                        </svg>

                                    </div>
                                </td>
                                <td class="b-offer-header-table__cell text-right">
                                    <div class="text-nowrap">
                                        <span class="b-offer-header-table__id">ID: 21</span>
                                        <span class="b-offer-header-table__date">Дата: 21.21.2121</span>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="b-offer-panel">
                        <div class="b-offer-panel__cell">
                            <a href="javascript:void(0)"> Добавить помещение</a>
                        </div>
                        <div class="b-offer-panel__cell">
                            <a href="javascript:void(0)"> Актуализировать цены</a>
                        </div>
                        <div class="b-offer-panel__cell">
                            <a href="javascript:void(0)"> Экспортировать в Excel</a>
                        </div>
                        <div class="b-offer-panel__cell">
                            <a href="javascript:void(0)"> Сохранить КП</a>
                        </div>
                    </div>
                    <div class="b-accommodation">
                        <div class="b-accommodation__name  b-editable-field"
                             ng-editable-field>
                            <div class="b-editable-field__inner">

                                <input class=" b-editable-field__field"
                                       value="Коммерческое предложение для Михаила">
                                <span class="b-editable-field__hidden">Коммерческое предложение для Михаила</span>
                            </div>

                            <svg version="1.1" id="Слой_1" xmlns="http://www.w3.org/2000/svg"
                                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                 viewBox="0 0 21.2 19.2" enable-background="new 0 0 21.2 19.2"
                                 class="b-editable-field__icon" xml:space="preserve">
                        <path id="pensil_15_" class="b-editable-field__icon-path" fill="#CED0D1" d="M20.4,3.1l-2-2.2c-0.5-0.6-1.3-0.6-1.9-0.1L15.1,2l3.8,4.2L20.3,5
                        	C20.9,4.5,20.9,3.7,20.4,3.1z M3.2,12.7l3.8,4.2l11-9.8l-3.8-4.2L3.2,12.7z M1.4,16.1l-0.9,2.7l2.8-0.6l2.6-0.5l-3.6-4.1L1.4,16.1z"
                            />
                        </svg>

                        </div>
                        <hr class="dotted-separator"/>
                        <div class="b-accommodation-panel">
                            <div class="b-accommodation-panel__cell">
                                <a href="javascript:void(0)">Добавить оборудование</a>
                            </div>
                            <div class="b-accommodation-panel__cell">
                                <a href="javascript:void(0)"> Удалить</a>
                            </div>
                            <div class="b-accommodation-panel__cell">
                                <a href="javascript:void(0)"> Сохранить помещение</a>
                            </div>

                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
    <div class="b-section__content">
        <div class="b-tabs-wrapper b-tabs-wrapper_cabinet">
            <ul class="b-tabs list-unstyled">
                <li class="b-tabs__tab ">
                    <a class="b-tabs__link  text-left" href="#orders_history" data-toggle="tab">История заказов</a>
                </li>
                <li class="b-tabs__tab">
                    <a class="b-tabs__link  text-left" href="#personal_data" data-toggle="tab">Персональные данные</a>
                </li>
                <li class="b-tabs__tab active">
                    <a class="b-tabs__link  text-left" href="#offers_4" data-toggle="tab">Коммерческие предложения</a>
                </li>
            </ul>
            <div class="b-tabs-content">
                <div class="b-tabs-content__item b-tabs-content__item_offer fade in active " id="offers_4">

                    <div class="b-offer">
                        <table class="b-offer-header-table">
                            <colgroup>
                                <col style="width: 70%"/>
                                <col style="width: 30%"/>
                            </colgroup>
                            <tr>
                                <td class="b-offer-header-table__cell">
                                    <div class="b-offer-header-table__name  b-editable-field"
                                         ng-editable-field>
                                        <div class="b-editable-field__inner">

                                            <input class=" b-editable-field__field"
                                                   value="Коммерческое предложение для Михаила">
                                            <span class="b-editable-field__hidden">Коммерческое предложение для Михаила</span>
                                        </div>

                                        <svg version="1.1" id="Слой_1" xmlns="http://www.w3.org/2000/svg"
                                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                             viewBox="0 0 21.2 19.2" enable-background="new 0 0 21.2 19.2"
                                             class="b-editable-field__icon" xml:space="preserve">
                        <path id="pensil_15_" class="b-editable-field__icon-path" fill="#CED0D1" d="M20.4,3.1l-2-2.2c-0.5-0.6-1.3-0.6-1.9-0.1L15.1,2l3.8,4.2L20.3,5
                        	C20.9,4.5,20.9,3.7,20.4,3.1z M3.2,12.7l3.8,4.2l11-9.8l-3.8-4.2L3.2,12.7z M1.4,16.1l-0.9,2.7l2.8-0.6l2.6-0.5l-3.6-4.1L1.4,16.1z"
                            />
                        </svg>

                                    </div>
                                </td>
                                <td class="b-offer-header-table__cell text-right">
                                    <div class="text-nowrap">
                                        <span class="b-offer-header-table__id">ID: 21</span>
                                        <span class="b-offer-header-table__date">Дата: 21.21.2121</span>
                                    </div>
                                </td>
                            </tr>
                        </table>

                    </div>
                    <div class="b-offer-panel">
                        <div class="b-offer-panel__cell">
                            <a href="javascript:void(0)"> Добавить помещение</a>
                        </div>
                        <div class="b-offer-panel__cell">
                            <a href="javascript:void(0)"> Актуализировать цены</a>
                        </div>
                        <div class="b-offer-panel__cell">
                            <a href="javascript:void(0)"> Экспортировать в Excel</a>
                        </div>
                        <div class="b-offer-panel__cell">
                            <a href="javascript:void(0)"> Сохранить КП</a>
                        </div>
                    </div>
                    <div class="b-accommodation">
                        <div class="b-accommodation__name  b-editable-field"
                             ng-editable-field>
                            <div class="b-editable-field__inner">

                                <input class=" b-editable-field__field"
                                       value="Коммерческое предложение для Михаила">
                                <span class="b-editable-field__hidden">Коммерческое предложение для Михаила</span>
                            </div>

                            <svg version="1.1" id="Слой_1" xmlns="http://www.w3.org/2000/svg"
                                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                 viewBox="0 0 21.2 19.2" enable-background="new 0 0 21.2 19.2"
                                 class="b-editable-field__icon" xml:space="preserve">
                        <path id="pensil_15_" class="b-editable-field__icon-path" fill="#CED0D1" d="M20.4,3.1l-2-2.2c-0.5-0.6-1.3-0.6-1.9-0.1L15.1,2l3.8,4.2L20.3,5
                        	C20.9,4.5,20.9,3.7,20.4,3.1z M3.2,12.7l3.8,4.2l11-9.8l-3.8-4.2L3.2,12.7z M1.4,16.1l-0.9,2.7l2.8-0.6l2.6-0.5l-3.6-4.1L1.4,16.1z"
                            />
                        </svg>

                        </div>
                        <hr class="dotted-separator"/>
                        <table cellpadding="0" cellspacing="0" border="0"
                               class="b-cart-table b-cart-table_accommodation">
                            <colgroup>
                                <col style="width:16rem;">
                                <col style="width:10rem;">
                                <col style="width:100%">
                                <col style="width:7.5rem;">
                                <col style="width:10.8rem;">
                                <col style="width:10.8rem;">
                                <col style="width:1.3rem;">
                            </colgroup>
                            <tbody>

                            <tr class="cart-line">
                                <td class="b-cart-product-cell  b-cart-product-cell_image">
                                    <a href="/catalog/product/84488/" class="b-cart-product-cell_image__inner">
                                        <img class="b-cart-product-cell__image"
                                             src="/images/series/img_52de7a1bc2b0d.jpg"
                                             alt="LM-CM-1563025-02A-0 white 15Вт, 60°, 3000K">
                                    </a>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_article">
                                    <div class="b-cart-product-cell_article__inner">
                                        84488
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_title">
                                    <h5 class="b-cart-product-cell__title">
                                        <a href="/catalog/product/84488/">LM-CM-1563025-02A-0 white 15Вт, 60°, 3000K</a>
                                    </h5>

                                    <p>Угол свечения - 60⁰</p>

                                    <p>Цвет свечения - Тёплый белый</p>

                                    <p>Цвет корпуса - Белый</p>
                                </td>


                                <td class="b-cart-product-cell  b-cart-product-cell_price">
                                    <div class="b-cart-product-cell_price__inner">
                                        <span class="b-cart-product-cell__price"
                                              ng-init="prodsInfo[84488].price = 4981">4981</span>
                                        <span class="b-rub">Р</span>
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_count">
                                    <div class="b-cart-product-cell_count__inner">
                                        <div class="b-cart-product-counter">
                                            <input
                                                class="b-form-control b-cart-product-counter__input ng-pristine ng-untouched ng-valid"
                                                name="count" ng-model="prodsInfo[84488].count"
                                                ng-change="setProdsInfo(prodsInfo)" ng-value="1" value="1">
                                            <span
                                                class="b-cart-product-counter__button b-cart-product-counter__button_up font-icon-arrow-2"></span>
                                            <span
                                                class="b-cart-product-counter__button b-cart-product-counter__button_down font-icon-arrow"></span>
                                        </div>
                                    </div>
                                </td>

                                <td class="b-cart-product-cell  b-cart-product-cell_result-price">
                                    <div class="b-cart-product-cell_result-price__inner">
                                        <span class="b-cart-product-cell__result-price">4981</span>
                                        <span class="b-rub">Р</span>
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_delete">
                                    <div class="b-cart-product-cell_delete__inner">
                                        <button type="button" class="b-cart-product_delete close">
                                            ×
                                        </button>
                                    </div>
                                </td>

                            </tr>
                            <tr class="cart-line">
                                <td class="b-cart-product-cell  b-cart-product-cell_image">
                                    <a href="/catalog/product/84488/" class="b-cart-product-cell_image__inner">
                                        <img class="b-cart-product-cell__image"
                                             src="/images/series/img_52de7a1bc2b0d.jpg"
                                             alt="LM-CM-1563025-02A-0 white 15Вт, 60°, 3000K">
                                    </a>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_article">
                                    <div class="b-cart-product-cell_article__inner">
                                        84488
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_title">
                                    <h5 class="b-cart-product-cell__title">
                                        <a href="/catalog/product/84488/">LM-CM-1563025-02A-0 white 15Вт, 60°, 3000K</a>
                                    </h5>

                                    <p>Угол свечения - 60⁰</p>

                                    <p>Цвет свечения - Тёплый белый</p>

                                    <p>Цвет корпуса - Белый</p>
                                </td>


                                <td class="b-cart-product-cell  b-cart-product-cell_price">
                                    <div class="b-cart-product-cell_price__inner">
                                        <span class="b-cart-product-cell__price"
                                              ng-init="prodsInfo[84488].price = 4981">4981</span>
                                        <span class="b-rub">Р</span>
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_count">
                                    <div class="b-cart-product-cell_count__inner">
                                        <div class="b-cart-product-counter">
                                            <input
                                                class="b-form-control b-cart-product-counter__input ng-pristine ng-untouched ng-valid"
                                                name="count" ng-model="prodsInfo[84488].count"
                                                ng-change="setProdsInfo(prodsInfo)" ng-value="1" value="1">
                                            <span
                                                class="b-cart-product-counter__button b-cart-product-counter__button_up font-icon-arrow-2"></span>
                                            <span
                                                class="b-cart-product-counter__button b-cart-product-counter__button_down font-icon-arrow"></span>
                                        </div>
                                    </div>
                                </td>

                                <td class="b-cart-product-cell  b-cart-product-cell_result-price">
                                    <div class="b-cart-product-cell_result-price__inner">
                                        <span class="b-cart-product-cell__result-price">4981</span>
                                        <span class="b-rub">Р</span>
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_delete">
                                    <div class="b-cart-product-cell_delete__inner">
                                        <button type="button" class="b-cart-product_delete close">
                                            ×
                                        </button>
                                    </div>
                                </td>

                            </tr>
                            <tr class="cart-line">
                                <td class="b-cart-product-cell  b-cart-product-cell_image">
                                    <a href="/catalog/product/84488/" class="b-cart-product-cell_image__inner">
                                        <img class="b-cart-product-cell__image"
                                             src="/images/series/img_52de7a1bc2b0d.jpg"
                                             alt="LM-CM-1563025-02A-0 white 15Вт, 60°, 3000K">
                                    </a>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_article">
                                    <div class="b-cart-product-cell_article__inner">
                                        84488
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_title">
                                    <h5 class="b-cart-product-cell__title">
                                        <a href="/catalog/product/84488/">LM-CM-1563025-02A-0 white 15Вт, 60°, 3000K</a>
                                    </h5>

                                    <p>Угол свечения - 60⁰</p>

                                    <p>Цвет свечения - Тёплый белый</p>

                                    <p>Цвет корпуса - Белый</p>
                                </td>


                                <td class="b-cart-product-cell  b-cart-product-cell_price">
                                    <div class="b-cart-product-cell_price__inner">
                                        <span class="b-cart-product-cell__price"
                                              ng-init="prodsInfo[84488].price = 4981">4981</span>
                                        <span class="b-rub">Р</span>
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_count">
                                    <div class="b-cart-product-cell_count__inner">
                                        <div class="b-cart-product-counter">
                                            <input
                                                class="b-form-control b-cart-product-counter__input ng-pristine ng-untouched ng-valid"
                                                name="count" ng-model="prodsInfo[84488].count"
                                                ng-change="setProdsInfo(prodsInfo)" ng-value="1" value="1">
                                            <span
                                                class="b-cart-product-counter__button b-cart-product-counter__button_up font-icon-arrow-2"></span>
                                            <span
                                                class="b-cart-product-counter__button b-cart-product-counter__button_down font-icon-arrow"></span>
                                        </div>
                                    </div>
                                </td>

                                <td class="b-cart-product-cell  b-cart-product-cell_result-price">
                                    <div class="b-cart-product-cell_result-price__inner">
                                        <span class="b-cart-product-cell__result-price">4981</span>
                                        <span class="b-rub">Р</span>
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_delete">
                                    <div class="b-cart-product-cell_delete__inner">
                                        <button type="button" class="b-cart-product_delete close">
                                            ×
                                        </button>
                                    </div>
                                </td>

                            </tr>

                            <tr class="cart-line">
                                <td class="b-cart-product-cell  b-cart-product-cell_image">
                                    <a href="/catalog/product/84488/" class="b-cart-product-cell_image__inner">
                                        <img class="b-cart-product-cell__image"
                                             src="/images/series/img_52de7a1bc2b0d.jpg"
                                             alt="LM-CM-1563025-02A-0 white 15Вт, 60°, 3000K">
                                    </a>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_article">
                                    <div class="b-cart-product-cell_article__inner">
                                        84488
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_title">
                                    <h5 class="b-cart-product-cell__title">
                                        <a href="/catalog/product/84488/">LM-CM-1563025-02A-0 white 15Вт, 60°, 3000K</a>
                                    </h5>

                                    <p>Угол свечения - 60⁰</p>

                                    <p>Цвет свечения - Тёплый белый</p>

                                    <p>Цвет корпуса - Белый</p>
                                </td>


                                <td class="b-cart-product-cell  b-cart-product-cell_price">
                                    <div class="b-cart-product-cell_price__inner">
                                        <span class="b-cart-product-cell__price"
                                              ng-init="prodsInfo[84488].price = 4981">4981</span>
                                        <span class="b-rub">Р</span>
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_count">
                                    <div class="b-cart-product-cell_count__inner">
                                        <div class="b-cart-product-counter">
                                            <input
                                                class="b-form-control b-cart-product-counter__input ng-pristine ng-untouched ng-valid"
                                                name="count" ng-model="prodsInfo[84488].count"
                                                ng-change="setProdsInfo(prodsInfo)" ng-value="1" value="1">
                                            <span
                                                class="b-cart-product-counter__button b-cart-product-counter__button_up font-icon-arrow-2"></span>
                                            <span
                                                class="b-cart-product-counter__button b-cart-product-counter__button_down font-icon-arrow"></span>
                                        </div>
                                    </div>
                                </td>

                                <td class="b-cart-product-cell  b-cart-product-cell_result-price">
                                    <div class="b-cart-product-cell_result-price__inner">
                                        <span class="b-cart-product-cell__result-price">4981</span>
                                        <span class="b-rub">Р</span>
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_delete">
                                    <div class="b-cart-product-cell_delete__inner">
                                        <button type="button" class="b-cart-product_delete close">
                                            ×
                                        </button>
                                    </div>
                                </td>

                            </tr>
                            <tr class="cart-line">
                                <td class="b-cart-product-cell  b-cart-product-cell_image">
                                    <a href="/catalog/product/84488/" class="b-cart-product-cell_image__inner">
                                        <img class="b-cart-product-cell__image"
                                             src="/images/series/img_52de7a1bc2b0d.jpg"
                                             alt="LM-CM-1563025-02A-0 white 15Вт, 60°, 3000K">
                                    </a>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_article">
                                    <div class="b-cart-product-cell_article__inner">
                                        84488
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_title">
                                    <h5 class="b-cart-product-cell__title">
                                        <a href="/catalog/product/84488/">LM-CM-1563025-02A-0 white 15Вт, 60°, 3000K</a>
                                    </h5>

                                    <p>Угол свечения - 60⁰</p>

                                    <p>Цвет свечения - Тёплый белый</p>

                                    <p>Цвет корпуса - Белый</p>
                                </td>


                                <td class="b-cart-product-cell  b-cart-product-cell_price">
                                    <div class="b-cart-product-cell_price__inner">
                                        <span class="b-cart-product-cell__price"
                                              ng-init="prodsInfo[84488].price = 4981">4981</span>
                                        <span class="b-rub">Р</span>
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_count">
                                    <div class="b-cart-product-cell_count__inner">
                                        <div class="b-cart-product-counter">
                                            <input
                                                class="b-form-control b-cart-product-counter__input ng-pristine ng-untouched ng-valid"
                                                name="count" ng-model="prodsInfo[84488].count"
                                                ng-change="setProdsInfo(prodsInfo)" ng-value="1" value="1">
                                            <span
                                                class="b-cart-product-counter__button b-cart-product-counter__button_up font-icon-arrow-2"></span>
                                            <span
                                                class="b-cart-product-counter__button b-cart-product-counter__button_down font-icon-arrow"></span>
                                        </div>
                                    </div>
                                </td>

                                <td class="b-cart-product-cell  b-cart-product-cell_result-price">
                                    <div class="b-cart-product-cell_result-price__inner">
                                        <span class="b-cart-product-cell__result-price">4981</span>
                                        <span class="b-rub">Р</span>
                                    </div>
                                </td>
                                <td class="b-cart-product-cell  b-cart-product-cell_delete">
                                    <div class="b-cart-product-cell_delete__inner">
                                        <button type="button" class="b-cart-product_delete close">
                                            ×
                                        </button>
                                    </div>
                                </td>

                            </tr>
                            <tr>
                                <!--                               Пустая строка тут нужна-->
                            </tr>
                            <tr class="cart-line">
                                <td class="b-cart-table_accommodation__total text-right" colspan="5">Сумма:</td>
                                <td class="b-cart-table_accommodation__total">555555<span class="b-rub">Р</span></td>
                                <td></td>
                            </tr>
                        </table>
                        <hr class="dotted-separator"/>
                        <div class="b-accommodation-panel">
                            <div class="b-accommodation-panel__cell">
                                <a href="javascript:void(0)">Добавить оборудование</a>
                            </div>
                            <div class="b-accommodation-panel__cell">
                                <a href="javascript:void(0)"> Удалить</a>
                            </div>
                            <div class="b-accommodation-panel__cell">
                                <a href="javascript:void(0)"> Сохранить помещение</a>
                            </div>

                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>