<div class="b-developers b-section">
    <div class="b-section__content">
        <div class="b-breadcrumbs">
            <a class="b-breadcrumbs__item" href="/">Главная</a>&nbsp;/

            <strong class="b-breadcrumbs__item b-breadcrumbs__item_active">Производители</strong>
        </div>
    </div>
    <div class="b-section__content b-section__content_developers">

        <div class="b-tabs-wrapper b-tabs-wrapper_developers">
            <div class="b-tabs-wrapper_developers__buttons">
                <br/>

                <h2 class="text-center">Светотехнические производители</h2><br/><br/>

                <ul class="b-tabs b-tabs_developers list-unstyled">
                    <li class="b-tabs__tab active">
                        <a class="b-tabs__link  text-center" href="#developers_1" data-toggle="tab">Складские
                            позиции</a>
                    </li>
                    <li class="b-tabs__tab">
                        <a class="b-tabs__link  text-center" href="#developers_2" data-toggle="tab">Проектные
                            партнеры</a>
                    </li>

                </ul>
            </div>
            <div class="b-tabs-content ng-cloak">
                <div class="b-tabs-content__item fade in active" id="developers_1">
                    <div class="b-developer">
                        <div class="b-developer__left">
                            <img src="/Content/images/developers/icon_1.jpg"/>
                        </div>
                        <div class="b-developer__right">
                            <hr class="dotted-separator"/>
                            <h2 class="b-developer__heading">Тайваньский производитель QisDesign</h2>

                            <p><a href="javascript:void(0)">www.phili9ps.ru</a></p>

                            <p class="b-developer__text"
                               text-cut="{'lines':3, 'text' : '.b-developer__cutted-text'}">
                        <span class="b-developer__cutted-text">
                           Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего зд
                            </span><a href="javascript:void(0)" class="b-developer__link-more">читать подробнее</a>
                            </p>
                        </div>
                    </div>
                    <div class="b-developer">
                        <div class="b-developer__left">
                            <img src="/Content/images/developers/icon_2.jpg"/>
                        </div>
                        <div class="b-developer__right">
                            <hr class="dotted-separator"/>
                            <h2 class="b-developer__heading">Тайваньский производитель QisDesign</h2>

                            <p><a href="javascript:void(0)">www.phili9ps.ru</a></p>

                            <p class="b-developer__text"
                               text-cut="{'lines':3, 'text' : '.b-developer__cutted-text'}">
                        <span class="b-developer__cutted-text">
                           Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего зд
                            </span><a href="javascript:void(0)" class="b-developer__link-more">читать подробнее</a>
                            </p>
                        </div>
                    </div>
                    <div class="b-developer">
                        <div class="b-developer__left">
                            <img src="/Content/images/developers/icon_3.jpg"/>
                        </div>
                        <div class="b-developer__right">
                            <hr class="dotted-separator"/>
                            <h2 class="b-developer__heading">Тайваньский производитель QisDesign</h2>

                            <p><a href="javascript:void(0)">www.phili9ps.ru</a></p>

                            <p class="b-developer__text"
                               text-cut="{'lines':3, 'text' : '.b-developer__cutted-text'}">
                        <span class="b-developer__cutted-text">
                           Трудно переоценить важность грамотно организованного освещения для нашего здоровья и

                            </span><a href="javascript:void(0)" class="b-developer__link-more">читать подробнее</a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="b-tabs-content__item fade" id="developers_2">
                    <div class="b-developer">
                        <div class="b-developer__left">
                            <img src="/Content/images/developers/icon_3.jpg"/>
                        </div>
                        <div class="b-developer__right">
                            <hr class="dotted-separator"/>
                            <h2 class="b-developer__heading">Тайваньский производитель QisDesign</h2>

                            <p><a href="javascript:void(0)">www.phili9ps.ru</a></p>

                            <p class="b-developer__text"
                               text-cut="{'lines':3, 'text' : '.b-developer__cutted-text'}">
                        <span class="b-developer__cutted-text">
                           Трудно переоценить важность грамотно организованного освещения для нашего здоровья и

                            </span><a href="javascript:void(0)" class="b-developer__link-more">читать подробнее</a>
                            </p>
                        </div>
                    </div><div class="b-developer">
                        <div class="b-developer__left">
                            <img src="/Content/images/developers/icon_3.jpg"/>
                        </div>
                        <div class="b-developer__right">
                            <hr class="dotted-separator"/>
                            <h2 class="b-developer__heading">Тайваньский производитель QisDesign</h2>

                            <p><a href="javascript:void(0)">www.phili9ps.ru</a></p>

                            <p class="b-developer__text"
                               text-cut="{'lines':3, 'text' : '.b-developer__cutted-text'}">
                        <span class="b-developer__cutted-text">
                           Трудно переоценить важность грамотно организованного освещения для нашего здоровья и

                            </span><a href="javascript:void(0)" class="b-developer__link-more">читать подробнее</a>
                            </p>
                        </div>
                    </div><div class="b-developer">
                        <div class="b-developer__left">
                            <img src="/Content/images/developers/icon_3.jpg"/>
                        </div>
                        <div class="b-developer__right">
                            <hr class="dotted-separator"/>
                            <h2 class="b-developer__heading">Тайваньский производитель QisDesign</h2>

                            <p><a href="javascript:void(0)">www.phili9ps.ru</a></p>

                            <p class="b-developer__text"
                               text-cut="{'lines':3, 'text' : '.b-developer__cutted-text'}">
                        <span class="b-developer__cutted-text">
                           Трудно переоценить важность грамотно организованного освещения для нашего здоровья и...

                            </span><a href="javascript:void(0)" class="b-developer__link-more">читать подробнее</a>
                            </p>
                        </div>
                    </div><div class="b-developer">
                        <div class="b-developer__left">
                            <img src="/Content/images/developers/icon_3.jpg"/>
                        </div>
                        <div class="b-developer__right">
                            <hr class="dotted-separator"/>
                            <h2 class="b-developer__heading">Тайваньский производитель QisDesign</h2>

                            <p><a href="javascript:void(0)">www.phili9ps.ru</a></p>

                            <p class="b-developer__text"
                               text-cut="{'lines':3, 'text' : '.b-developer__cutted-text'}">
                        <span class="b-developer__cutted-text">
                           Трудно переоценить важность грамотно организованного освещения для нашего здоровья и

                            </span><a href="javascript:void(0)" class="b-developer__link-more">читать подробнее</a>
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>