<div class="b-section b-blog">
    <div class="b-blog-header">
        <div class="b-phrase-outer b-blog__phrase">
            <div class="b-phrase">
                <div class="b-phrase-table">
                    <div class="b-phrase-table__left">
                        <div>
                            <img class="b-phrase__icon" src="/Content/images/aledo-logo-small_2_white.svg"/>

                        </div>
                    </div>
                    <div class="b-phrase-table__right">
                        Цветопередача, чем раньше, тем больше, тем меньше и уже, ну
                        как-то
                    </div>
                </div>
            </div>
        </div>
    </div>
<div class="b-blog-articles" ng-cloak>
    <div class="b-blog-article">
        <div class="b-section__content b-blog-article__inner">
            <div class="b-blog-article__left">
                <img class="b-blog-article__image" src="/Content/images/blog/images/1.png"/>
            </div>
            <div class="b-blog-article__right">
                <div class="b-blog-article__preview">
                    <h2 class="b-blog-article__heading">Цветопередача, чем ра ну
                        как-то
                        так.</h2>

                        <div class="b-blog-article-rubrics">
                            Рубрики: <a href="javascript:void(0)" class="b-blog-article-rubrics__item">технологии</a>,
                                <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>
                        </div>
                    <p class="b-blog-article__text"  text-cut="{'lines':3, 'text' : '.b-blog-article__cutted-text', callback : 'alert(1)'}">
                        <span class="b-blog-article__cutted-text">
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и

                        интерьера квартиры или дома....................</span><a href="javascript:void(0)" class="b-blog-article__link-more">читать далее</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="b-blog-article">
        <div class="b-section__content b-blog-article__inner">
            <div class="b-blog-article__left">
                <img class="b-blog-article__image" src="/Content/images/blog/images/1.png"/>
            </div>
            <div class="b-blog-article__right">
                <div class="b-blog-article__preview">
                    <h2 class="b-blog-article__heading">Цветопередача, чем раньше, тем больше, тем
                       </h2>

                    <div class="b-blog-article-rubrics">
                        Рубрики: <a href="javascript:void(0)" class="b-blog-article-rubrics__item">технологии</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>
                    </div>
                    <p class="b-blog-article__text"  text-cut="{'lines':3, 'text' : '.b-blog-article__cutted-text'}">
                        <span class="b-blog-article__cutted-text">
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        самочувствия. Красивые, правильно расположенные светильники являются одной из важнейших

                        интерьера квартиры или дома</span><a href="javascript:void(0)" class="b-blog-article__link-more">читать далее</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="b-blog-article">
        <div class="b-section__content b-blog-article__inner">
            <div class="b-blog-article__left">
                <img class="b-blog-article__image" src="/Content/images/blog/images/1.png"/>
            </div>
            <div class="b-blog-article__right">
                <div class="b-blog-article__preview">
                    <h2 class="b-blog-article__heading">Цветопередача, чем раньше, тем больше, тем меньше </h2>

                    <div class="b-blog-article-rubrics">
                        Рубрики: <a href="javascript:void(0)" class="b-blog-article-rubrics__item">технологии</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>
                    </div>
                    <p class="b-blog-article__text" text-cut="{'lines':3, 'text' : '.b-blog-article__cutted-text'}">
                        <span class="b-blog-article__cutted-text">
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        самочувствия. Красивые, правильно расположенные светильники являются одной из важнейших

                        интерьера квартиры или дома</span><a href="javascript:void(0)" class="b-blog-article__link-more">читать далее</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="b-blog-article">
        <div class="b-section__content b-blog-article__inner">
            <div class="b-blog-article__left">
                <img class="b-blog-article__image" src="/Content/images/blog/images/1.png"/>
            </div>
            <div class="b-blog-article__right">
                <div class="b-blog-article__preview">
                    <h2 class="b-blog-article__heading">Цветопередача</h2>

                    <div class="b-blog-article-rubrics">
                        Рубрики: <a href="javascript:void(0)" class="b-blog-article-rubrics__item">технологии</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>,
                        <a href="javascript:void(0)" class="b-blog-article-rubrics__item">качество</a>
                    </div>
                    <p class="b-blog-article__text" text-cut="{'lines':3, 'text' : '.b-blog-article__cutted-text'}">
                        <span class="b-blog-article__cutted-text">
                        Трудно переоценить важность грамотно организованного освещения для нашего здоровья и
                        самочувствия. Красивые, правильно расположенные светильники являются одной из важнейших

                        интерьера квартиры или дома</span><a href="javascript:void(0)" class="b-blog-article__link-more">читать далее</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

</div></div>