<div class="row">
    <div class="col-md-8 col-md-offset-2" style="text-align: center">
        <h2>Новый пароль был выслан вам на почту.</h2>

    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2" style="text-align: center; min-height: 400px">
        С возвращением! :-) Через несколько секунд вы будете автоматически перенаправлены на главную страницу.
        Если вы не хотите ждать, воспользуйтесь <a href="http://aledo-pro.ru">прямой ссылкой</a>.

    </div>
</div>

<script>
   window.setTimeout(
       function() {
           document.location.href = 'http://aledo-pro.ru';
       },
       5000
   );
</script>