<h1>
    <a href="<?= $this->url('zfcadmin/requests') ?>">Заявки</a>
    >
    Партнерские заявки
</h1>

<div class="section">
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Компания</th>
            <th>Отправитель</th>
            <th>Дата</th>
            <th>Управление</th>
        </tr>
        <tbody>
        <? foreach($reqs as $req){ ?>
            <tr class="entity">
                <td><?= $req->id; ?></td>
                <td><?= $req->company_name; ?></td>
                <td><?= $req->name; ?></td>
                <td><?= \Application\Service\ApplicationService::getFormedDate($req->date); ?></td>
                <td>
                    <a href="#" class="editBtn">Смотреть</a>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    $(function(){
        catalog.editUrl = '<?= $this->url('zfcadmin/requests', array('action'=> 'reqPartnerView')) ?>';
        catalog.init();
    });
</script>