<h1>
    <a href="<?= $this->url('zfcadmin/requests') ?>">Заявки</a>
    >
    <a href="<?= $this->url('zfcadmin/requests', array('action' => 'reqPartner')) ?>">Партнерские заявки</a>
    >
    <?
    /** @var $req \Info\Model\PartnerRequest */
    ?>
    <?= $req->partner_company_name; ?>
</h1>

<div class="section">
    <table class="table table-striped">
        <tbody>
        <tr>
            <td>Имя отправителя</td>
            <td><?= $req->partner_lastname . " " . $req->partner_name . " " . $req->partner_fathername ?></td>
        </tr>
        <tr>
            <td>Название компании</td>
            <td><?= $req->partner_company_name ?></td>
        </tr>
        <tr>
            <td>Сфера деятельности компании</td>
            <td><?= $req->partner_scope ?></td>
        </tr>
        <tr>
            <td>Должность</td>
            <td><?= $req->partner_job_title ?></td>
        </tr>
        <tr>
            <td>Офисный телефон</td>
            <td><?= $req->partner_office_tel ?></td>
        </tr>
        <tr>
            <td>Вебсайт</td>
            <td><?= $req->partner_website ?></td>
        </tr>
        <tr>
            <td>Примеры брендов</td>
            <td><?= $req->partner_brands ?></td>
        </tr>
        <tr>
            <td>Дата</td>
            <td><?= \Application\Service\ApplicationService::getFormedDate($req->date); ?></td>
        </tr>
        </tbody>
    </table>
</div>